Cargo.lock, shared/Cargo.toml, shared/src/types/ethereum_events.rs, shared/src/types/storage.rs, wasm/tx_template/Cargo.lock, wasm/vp_template/Cargo.lock, wasm/wasm_source/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
* Add `BlockHeight` to `MultiSignedEthEvent` as in https://github.com/anoma/specs/commit/2198767818a56bff6632b4df3d47f2af3a358a99
* resync `Cargo.lock` so that only dependencies related to changes in `eth-bridge-integration` branch are updated
=> Changes to eth-bridge-integration branch

apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs
Taken from the [`bat/eth-header-vp`](https://github.com/anoma/anoma/pull/1224) branch of the anoma repo.
This will allow us to load wasms inside `apply_tx`, and we can use such a struct to test `apply_tx` as well.
=> Change apply_tx to accept a ShellParams containing wasm_dir

apps/src/lib/node/ledger/shell/queries.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, shared/src/types/ethereum_events/vote_extensions.rs
Resolves https://github.com/anoma/namada/issues/208
`make test-unit-abci-plus-plus` passes, and I manually verified running a chain with `namadan` doesn't encounter the error from https://github.com/anoma/namada/pull/206 anymore
=> Temporarily add validator address to vote extensions

scripts/make-package.sh
This was mistakenly not rebased out of c8994d2 ('ci: move to github
actions'). There should never be lightweight tags on the CI-bearing
remote, so --tags is either a no-op or an error in CI, and it is
always an error locally if the local user uses a lightweight tag.
--broken is a useful safeguard for weird or inconsistent repository
states, and --dirty distinguishes things which are not exactly the
commit in question.
=> scripts: revert change to package `git describe`

apps/src/lib/node/ledger/ethereum_node/mod.rs, apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/shell/mod.rs
Some noise I've seen while testing eth bridge branches
- sleep between logging attempts to connect to `geth`
- don't log if no Ethereum events were received in vote extensions in the previous round (we also won't derive/apply a state update transaction either)
- make validators log only if they receive >=1 Ethereum events from their Ethereum node
=> Reduce logging and transactions in eth-bridge-integration

Cargo.lock, apps/Cargo.toml, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, shared/src/types/ethereum_events/vote_extensions.rs
This PR implements handling vote extensions in ProcessProposal.
---
In ProcessProposal, each validator must check:
* All the signatures are valid
* All signatures came from an validator in the active validator set at the previous block height,
* The block height is correct,
* The sum of the stake of the validators in the contained vector is at least 2/3 of the total amount staked at the previous block height.
=> Handle vote extensions in ProcessProposal

apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/queries.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs
Motivation is for some of this functionality to be available outside of the `Shell` (e.g. in `apply_tx` some of the current `queries.rs` functionality is duplicated in [this PR](https://github.com/anoma/namada/pull/210/files#diff-e02b60ae4f03bdbcdd62ba79596497e65f9f32ecad4d98a4f353cff428919f6e))
=> Refactor some helpers in queries.rs

apps/src/lib/node/ledger/ethereum_node/mod.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/ethereum_node/test_tools.rs, apps/src/lib/node/ledger/mod.rs
Relates to #269
Tested manually (for now), both with the `namada_apps/eth-fullnode` feature enabled and disabled. A log is emitted indicating the oracle is starting right after we've checked `geth` is reachable
```
...
namada_apps::node::ledger::ethereum_node::eth_fullnode: Finished syncing
2022-08-03T16:11:16.241376Z  INFO namada_apps::node::ledger::ethereum_node::oracle::oracle_process: Ethereum event oracle is starting
...
```
A log is emitted at shutdown indicating it stopped.
```
...
2022-08-03T15:48:13.114802Z  INFO namada_apps::node::ledger: Broadcaster is no longer running.
2022-08-03T15:48:13.114785Z  INFO namada_apps::node::ledger: Anoma ledger node has shut down.
2022-08-03T15:48:13.115287Z  INFO namada_apps::node::ledger::ethereum_node::oracle::oracle_process: Ethereum event …
```
=> Ensure Ethereum oracle starts up

documentation/specs/src/economics/inflation-system.md
This PR updates the inflation system section of the Namada specs to clarify PD-controller calculation details.
For simplicity, I think we can just use fully separate PD-controllers for each asset in the shielded pool for which Namada decides to pay rewards. This requires that we pick parameters and caps independently, but otherwise we have to deal with contention between controllers, which is complicated and likely confusing to users, so I think it's worth the additional parameters.
Also for simplicity, I'm assuming that we do all inflation calculations once-per-epoch and quantise the PD-controllers at that frequency.
=> Clarify inflation system calculation details

apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs
This is a quick PR to add some more visibility around what is happening during block proposal and finalization. Especially:
- logging when we reject a block proposal as a validator
- logging when we receive an unsupported transaction in `apply_tx`
=> More logging during PrepareProposal, ProcessProposal, FinalizeBlock

apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs
Closes #308 
When a new ethereum event is seen, it is put in a queue to be included in a vote extension. Once that event is included on chain, it should be removed from the queue so that the validator that saw it stops including it in vote extensions.
=> Events voted on by validators are not voted on again

documentation/specs/src/interoperability/ethereum-bridge.md
We are no longer using the ethereum sentinel since the no transaction should ever modify the `/eth_msgs/` storage. This can be enforced by the EthBridge vp.
=> Remove the Ethereum sentinel from the specs

apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/queries.rs
Relates to https://github.com/anoma/namada/issues/309 , functionality like in this PR will be needed for https://github.com/anoma/namada/pull/284
This PR isn't a pure refactor but changes how transactions are dispatched slightly during `FinalizeBlock`. `apply_tx` becomes `dispatch_tx` which may call either `apply_wasm_tx` or `apply_protocol_tx`. `apply_wasm_tx` meters gas and can update storage via the wasm environment, updates are checked by validity predicates. `apply_protocol_tx` lets us update storage directly without going via wasm. Gas doesn't apply and validity predicates aren't checked.
`dry_run_tx` and the application of governance proposal transactions now go directly via `apply_wasm_tx`. When iterating over transactions in `finalize_block.rs`, we do `dispatch_tx` and pass a …
=> Accommodate natively updating blockchain state based on protocol transactions

.changelog/unreleased/testing/1142-expectrl-switch-from-fork.md, Cargo.lock, tests/Cargo.toml, tests/src/e2e/setup.rs
moved from https://github.com/anoma/anoma/pull/1142
follow-up to https://github.com/anoma/anoma/pull/1095, based on it
=> e2e tests: switch dep expectrl from fork to release

apps/src/lib/node/ledger/ethereum_node/events.rs, apps/src/lib/node/ledger/ethereum_node/test_tools.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/wallet/pre_genesis.rs, shared/src/types/vote_extensions/ethereum_events.rs, shared/src/types/vote_extensions/validator_set_update.rs
Small changes to make it so that
- `cargo doc` can compile for ABCI++ on our branch
- `cargo check` does not show dead code warnings when the `eth-fullnode` feature is not enabled
=> Fix up cargo doc / cargo check

.github/workflows/build-and-test.yml
based on #351 
In preparation for #257 - we need to d/l MASP params in the CI before we run e2e tests, otherwise the ledger start-up times 
out while it's trying to download them. Because of the changes in https://github.com/anoma/namada/pull/346 (and its follow-ups), the CI doesn't use the .github/workflow files from the source branch, instead it uses the base, so we need to get the CI change merged before #257 can pass e2e tests. The commits in here are cherry-picked from #257 so we can remove them from there.
=> CI: d/l masp params

apps/src/lib/config/ethereum.rs, apps/src/lib/config/mod.rs, apps/src/lib/node/ledger/ethereum_node/mod.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/mod.rs
Closes https://github.com/anoma/namada/issues/416
Moves the current `ledger.ethereum_url` config var to `ledger.ethereum.oracle_rpc_endpoint`
Can be overridden like so:
```shell
ANOMA_LEDGER__ETHEREUM__ORACLE_RPC_ENDPOINT='blah' target/debug/namadan ledger run
```
Also added a couple of log changes to log out the Ethereum endpoint so that overriding it can be verified.
More settings to be added as part of other PRs (e.g. https://github.com/anoma/namada/pull/294)
=> Add a configuration section for the Ethereum bridge

Cargo.lock, apps/Cargo.toml, apps/src/lib/config/ethereum.rs, apps/src/lib/node/ledger/ethereum_node/mod.rs, apps/src/lib/node/ledger/ethereum_node/test_tools.rs, apps/src/lib/node/ledger/mod.rs
Closes https://github.com/anoma/namada/issues/227
When the `namada_apps/eth-fullnode` feature is not enabled, there is a config option - `ledger.ethereum.oracle_event_endpoint` - which if set to true, makes it so that a server is started by the oracle exposing an endpoint at `http://127.0.0.1:3030` for submission of Borsh-serialized `EthereumEvent`s. Any events submitted there will be included in validator's vote extensions.
Enabling this functionality at runtime can be done like so:
```shell
ANOMA_LEDGER__ETHEREUM__ORACLE_EVENT_ENDPOINT=true target/debug/namadan ledger run
```
This functionality can be tested out using a devtool built from https://github.com/anoma/devtool/pull/2
```shell
devtool submit-fake-transfer-to-namada \
--nonce 1 \
--receiver …
```
=> Add endpoint for direct submission of Ethereum events

Makefile
this is follow-up to https://github.com/anoma/namada/pull/405
=> make: use build-doc to only check rustdoc build

apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs
This PR changes the following: during PrepareProposal, we return `ProtocolTxType::VoteExtension` instances in the tx arguments back to the replication engine. We do this so Tendermint can remove these protocol txs from its mempool.
=> Return the VoteExtension protocol txs from PrepareProposal

apps/src/lib/node/ledger/ethereum_node/oracle.rs
(this PR was split out from https://github.com/anoma/namada/pull/253)
Closes https://github.com/anoma/namada/issues/464
This PR has the oracle back off a bit after having gotten the latest block from the Ethereum JSON-RPC endpoint being used, otherwise we call the Ethereum RPC endpoint very fast over and over. Also adding some extra logging, so we can see what the latest block height is.
```
2022-08-04T12:56:01.158995Z  WARN namada_apps::node::ledger::ethereum_node::oracle::oracle_process: 
Couldn't get the latest Ethereum block height, will keep trying
error=FailedToSend(Connect(Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))
```
```
2022-08-04T12:53:54.587542Z DEBUG namada_apps::node::ledger::ethereum_node::oracle::oracle_process:
Got latest Ethereum block …
```
=> Add rate limiting to the Ethereum event oracle

.changelog/unreleased/bug-fixes/419-fix-rustdoc.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs
Resolves some conflicts where `cargo doc` had been fixed differently in `main`
=> Update `eth-bridge-integration` with `main`

tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/ledger_tests.rs
Ignoring e2e tests based on what failed in the latest CI run for `eth-bridge-integration` - https://github.com/anoma/namada/actions/runs/3129415031/jobs/5078474786
https://github.com/anoma/namada/issues/418 will track re-enabling them
=> Ignore failing end-to-end tests for `eth-bridge-integration`

apps/src/lib/node/ledger/ethereum_node/mod.rs
Waiting for `geth` to finish had no `.await` points in an infinite loop. This meant waiting for it to finish starved other tasks from making progress on one of the runtime's threads. This PR fixes that.
=> Avoid starving other Tokio tasks while waiting for geth to exit

apps/src/lib/node/ledger/ethereum_node/events.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/ethereum_node/test_tools.rs
In the audit on the Ethereum bridge, an error in the formula checking that the minimum number of confirmations was reached was discovered. This PR fixes that.
Old:
`self.confirmations >= height.clone() - self.block_height.clone()`
New:
`self.confirmations <= height.clone() - self.block_height.clone()`
This also highlighted a bug in testing the oracle. This PR fixes that as well.
=> Fixed the confirmations calculation for ethereum events

apps/src/lib/node/ledger/ethereum_node/events.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs
This is a bug fix. When sending an message over a bounded channel, if the receiver is dropped, the send method will still block indefinitely. This is despite the  documentation stating that it should error. So we need to add a check that the channel is still open.
=> Shutdown oracle when the receiver of it's channel is dropped

apps/src/lib/node/ledger/ethereum_node/events.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/ethereum_node/test_tools/events_endpoint.rs, apps/src/lib/node/ledger/ethereum_node/test_tools/mod.rs, apps/src/lib/node/ledger/mod.rs
This is a quick PR to improve the fake Ethereum events endpoint
- refactor and add some docstrings
- make it so that it shuts down correctly (fixes https://github.com/anoma/namada/issues/507)
- listen on `0.0.0.0:3030` rather than `127.0.0.1:3030` so that the endpoint can be more easily exposed from within Docker containers (as will be used in [anoma/ethereum-bridge-e2e-tests](https://github.com/anoma/ethereum-bridge-e2e-tests))
=> Ensure Ethereum events endpoint shuts down correctly

apps/src/lib/config/ethereum.rs, apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/mod.rs
Closes https://github.com/anoma/namada/issues/417 and https://github.com/anoma/namada/issues/464
This PR makes it so that the ledger will not start up `geth` if the `ledger.ethereum.mode = "Remote"`. The motivation for this PR is to be able to test the ledger more easily (with a separately managed `geth` process or some standin like `npx hardhat node`, or some remote Ethereum endpoint). I've manually tested using a separate `geth` process and passing envvars to override the appropriate config e.g.
```shell
export ANOMA_LEDGER__ETHEREUM__MODE='Remote'
target/debug/namadan ledger run
```
=> Allow the use of custom Ethereum JSON-RPC endpoint

apps/src/lib/node/ledger/ethereum_node/events.rs
Implements part of https://github.com/anoma/namada/issues/561
Update the `TransferToNamada` event signature to match the latest smart contracts - https://github.com/anoma/ethereum-bridge/blob/87056f4c1fa5472e49adaf0793af1f2ecda9b5da/contracts/interface/IBridge.sol#L7
Also update the decoding logic
=> Update TransferToNamada event signature

apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/protocol/transactions/mod.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs
Building `eth-bridge-integration` with the `abcipp` features enabled was failing, this PR updates the code to get it compiling again.
We no-op when applying protocol transactions for ABCI++ - the `ethereum_events` protocol tx logic is being further worked on for just ABCI for now.
Running `make test-unit-abcipp` and `make clippy-abcipp` passes locally (we can eventually set up a simple CI job to maintain the code we currently have - https://github.com/anoma/namada/issues/497 )
=> Fix ABCI++ compilation

Makefile
`make install-release` installs the Namada binaries without the tendermint binaries.
=> Add install-release target

.github/workflows/build-tendermint.yml, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
Relates to https://github.com/anoma/namada/issues/418
- turn off Ethereum bridge componentry in e2e tests for the time being
- re-enable the `run_ledger` test which seems to pass in CI again (even with old Tendermint)
- Tendermint CI changes are being cherry picked in a separate PR, https://github.com/anoma/namada/pull/593
```
running 19 tests
test e2e::eth_bridge_tests::everything ... ignored
test e2e::gossip_tests::match_intents ... ignored
test e2e::gossip_tests::run_gossip ... ignored
test e2e::ledger_tests::invalid_transactions ... ignored
test e2e::ledger_tests::ledger_many_txs_in_a_block ... ignored
test e2e::ledger_tests::ledger_txs_and_queries ... ignored
test e2e::ledger_tests::pos_bonds ... ignored
test e2e::ledger_tests::pos_init_validator ... ignored
test …
```
=> Re-enable `run_ledger` e2e test for `eth-bridge-integration`

wasm/checksums.json, wasm/wasm_source/Makefile
The wasm `tx_bond` is not being built because of a small mistake in the `Makefile`. This PR addresses that.
=> Fix wasms build

apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs
When verifying voting powers of validators, for validator set update vote extensions, we should fetch data from the new epoch, not from the epoch of the block height at which the extension was signed.
=> Fix valset upd verification

apps/src/lib/config/ethereum_bridge/ledger.rs, apps/src/lib/config/ethereum_bridge/mod.rs, apps/src/lib/config/ethereum_bridge/params.rs, apps/src/lib/config/genesis.rs, apps/src/lib/config/mod.rs, apps/src/lib/node/ledger/mod.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
Relates to https://github.com/anoma/namada/issues/365 and https://github.com/anoma/namada/issues/562
This PR adds *preliminary* chain parameters for the Ethereum bridge, and also renames ledger runtime configuration to be under `[ledger.ethereum_bridge]` rather than just `[ledger.ethereum]`. We can change/add extra validation for these configuration parameters in other PRs.
In a network config file, Ethereum bridge parameters will be able to be specified like so:
```toml
[ethereum_bridge_params]
min_confirmations = 100
[ethereum_bridge_params.contracts]
native_erc20 = "0x1721b337BBdd2b11f9Eef736d9192a8E9Cba5872"
[ethereum_bridge_params.contracts.bridge]
address = "0x237d915037A1ba79365E84e2b8574301B6D25Ea0"
version = 1
[ethereum_bridge_params.contracts.governance]
address = …
```
=> Add chain parameters for the Ethereum bridge

apps/src/lib/node/ledger/ethereum_node/oracle.rs, apps/src/lib/node/ledger/ethereum_node/test_tools/mod.rs
Relates to https://github.com/anoma/namada/issues/560
This PR makes some changes to the Ethereum oracle
- add more logging
- when the oracle starts up, process all Ethereum blocks in sequence starting from block #0, rather than the latest confirmed block
- make the oracle sleep time configurable (it is currently hardcoded to be 1s between blocks in production, but in tests we want it much shorter)
- make the oracle emit the block heights it processes for observability (in tests)
Processing blocks from 0 every time the ledger starts up is not the final behaviour - validators should process Ethereum blocks only from when they become an active validator, and should stop processing Ethereum blocks once they are no longer an active validator.
=> Update the Ethereum bridge oracle to process blocks in sequence from zero

shared/src/ledger/eth_bridge/bridge_pool_vp.rs, shared/src/ledger/eth_bridge/storage/bridge_pool.rs, shared/src/types/storage.rs, wasm/wasm_source/src/tx_bridge_pool.rs
This PR closes #422 
This PR depends on #579 which added a merkle tree to our storage for the bridge pool. This PR actually switches to using this tree and the necessary updates to the VP and wasm have been made.
=> Update bridge pool vp to use merkle tree

shared/src/types/vote_extensions/ethereum_events.rs, shared/src/types/vote_extensions/validator_set_update.rs
Implementing `BorshSchema` ourselves is a recipe for disaster, when the underlying types are subject to change.
Before the changes in [this PR](https://github.com/anoma/namada/pull/461), vote extension schemas had the same identifier: `Vext` and `VextDigest`, for both ethereum events and validator set update vote extensions. This led to collisions, which were detected by `namada-encoding-spec`. The linked PR kept the same naming for these types, but manually implemented `BorshSchema` to disambiguate between the schemas.
[The shimming changes](https://github.com/anoma/namada/pull/437) to the representation of vote extensions introduced a fault in their schemas(*). To prevent further bugs of this kind, it is better to give different names to our vote extensions types, such that we can …
=> Derive BorshSchema on vote extension types

apps/src/lib/node/ledger/protocol/transactions/ethereum_events/mod.rs, apps/src/lib/node/ledger/protocol/transactions/utils.rs, apps/src/lib/node/ledger/protocol/transactions/validator_set_update/mod.rs
Based on #684
This PR refactors `get_voting_powers` to accept different kinds of items that have been voted on (e.g. ethereum events and validator set updates).
=> Refactor `get_voting_powers` when applying protocol tx state changes

apps/src/lib/node/ledger/protocol/transactions/ethereum_events/eth_msgs.rs, apps/src/lib/node/ledger/protocol/transactions/ethereum_events/mod.rs, apps/src/lib/node/ledger/protocol/transactions/mod.rs, apps/src/lib/node/ledger/protocol/transactions/votes.rs
This PR:
- changes the `seen_by` field that we store for every Ethereum event from `BTreeSet<Address>` to `BTreeMap<Address, BlockHeight>` (`Votes` type)
- propagates this change through the rest of the Ethereum event code that exists in `eth-bridge-integration`
This change to start recording the block heights will be necessary for tallying votes against validator set updates - when a validator set update has enough votes behind it, the relayer should look in the specified `BlockHeight`s for the protocol txs containing the signatures.
=> Record the block heights at which validators vote for Ethereum events

Makefile, apps/src/lib/node/ledger/shell/queries.rs
Instead of spamming the chain with validator set update protocol txs, now we only send these once per epoch, at the second block height offset within the epoch.
=> Send a validator set update only once per epoch

apps/src/lib/node/ledger/protocol/transactions/validator_set_update/mod.rs
Based on #683
Count votes on validator set updates signed off for some epoch. Currently, nothing happens when we reach a complete proof (i.e. more than 2/3 of the voting power) on some set of validators, but we could, e.g. emit some kind of event which would be consumed by a relayer.
=> Aggregate votes for validator set updates in storage

apps/src/lib/client/rpc.rs
Use `crate::facade` for tendermint imports in `rpc.rs` (this happened during https://github.com/anoma/namada/pull/723 so this is already the case in `main`)
=> fix: use `crate::facade` for importing tendermint crates

.changelog/unreleased/bug-fixes/765-ethbridge-ci-fix.md, .github/workflows/build-and-test-bridge.yml
PR https://github.com/anoma/namada/pull/765 but for `eth-bridge-integration`
This should fix e2e tests to start running again in CI on eth bridge PRs (but need to merge this PR to try)
=> Fix up `build-and-test-bridge.yml` (for `eth-bridge-integration`)

apps/src/lib/node/ledger/ethereum_node/test_tools/events_endpoint.rs, apps/src/lib/node/ledger/mod.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
Closes https://github.com/anoma/namada/issues/781
This PR changes the fake Ethereum events endpoint to be managed using `AbortableSpawner` and an abort channel, and adds an end-to-end test to check that it starts up.
This mode will be used in end-to-end tests for https://github.com/anoma/namada/pull/768.
=> Ensure fake Ethereum events endpoint doesn't shut down immediately

.github/workflows/build-and-test-bridge.yml
Should run e2e CI for PRs that target other Ethereum bridge branches
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-based-on-the-head-or-base-branch-of-a-pull-request-1
I'm not sure if this will actually work until we try merging it to `eth-bridge-integration` (and maybe `main` also?)
=> Run Ethereum bridge CI for stacked PRs

shared/src/proto/types.rs, shared/src/types/vote_extensions/validator_set_update.rs
Closes https://github.com/anoma/namada/issues/767 (current e2e flakes in CI)
The issue was that `VotingPowersMap::get_abi_encoded` wasn't completely deterministic if there were validators present in the `HashMap` with the same voting power. Interestingly, this issue only occurred in tests run with the `--release` profile.
This PR:
- makes `VotingPowersMap::get_abi_encoded` deterministic
- adds some test coverage regarding the ordering of `VotingPowersMap` items
- updates some docstrings to mention requirements around determinism
=> Fix end-to-end test flakes involving more than one validator

apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs
=> Only dequeue Ethereum events if the vext signer is equal to the validator executing `FinalizeBlock`

.changelog/unreleased/ci/834-ethbridge-ci-stacked-prs.md, .github/workflows/build-and-test-bridge.yml
This should go into `main` as well in https://github.com/anoma/namada/pull/834
I accidentally overwrote https://github.com/anoma/namada/pull/798 when merging `v0.10.1` into `eth-bridge-integration`, this puts that change back
=> Run Ethereum bridge CI against more branches (`eth-bridge-integration`)

Cargo.lock, shared/Cargo.toml, shared/src/vm/mod.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Should enable us to ditch docker to build wasms for local testnets.
=> Allow sign extend opcodes in wasms

Cargo.lock, Cargo.toml, apps/Cargo.toml, shared/Cargo.toml, tests/Cargo.toml, wasm/Cargo.lock, wasm/Cargo.toml, wasm_for_tests/wasm_source/Cargo.lock, wasm_for_tests/wasm_source/Cargo.toml
Relates to https://github.com/anoma/namada/issues/825
This PR makes it so that we pull in tendermint-related dependencies directly via a `git` source as we used before. e.g.
```toml
tendermint = {package = "tendermint", git = "https://github.com/heliaxdev/tendermint-rs", rev = "e6c684731f21bffd89886d3e91074b96aee074ba"}
```
This makes more sense as the namada code does hard depend on our forks, and doesn't work with upstream tendermint-rs packages. By specifying our forks as direct dependencies, there is no longer a need to patch in the correct versions via the workspace `Cargo.toml`s. Unfortunately we obscure the versions of our forks from our `Cargo.toml`s, but the versions will still show up in `cargo tree` and when running `cargo build`, `cargo check`, etc.
The motivation for changing …
=> Updates to tendermint patching

shared/src/ledger/queries/shell.rs, shared/src/ledger/storage/merkle_tree.rs, shared/src/ledger/storage/mod.rs, shared/src/ledger/storage/traits.rs, shared/src/types/storage.rs
The design of the merkle tree is that each subtree should handle it's own particulars and the top level storage should be unaware of these details. The MerkleValue type violated this principal by requiring top level storage to correctly cast values to the right type which would then be checked by the sub-trees. This caused bugs and made strained the storage API. This PR removes this type.
PR #846 is the corresponding PR to main.
=>  Removed MerkleValue type.

documentation/docs/src/user-guide/ledger/pos.md
- replace `voting-power` cmd with `bonded-stake`
- added 2 new args for `init-validator` for their commission rate
- removed staking reward accounts - the rewards will be instead auto-bonded in the validator account
=> docs: update PoS user docs for 0.11.0

.changelog/unreleased/docs/440-replay-protection-specs.md, documentation/specs/src/SUMMARY.md, documentation/specs/src/base-ledger/replay-protection.md
Specs for replay protection (#178)
=> Replay protection specs

Makefile
This is mostly added to stay on par with `eth-bridge-integration`, and smooth out future merges.
=> Add a new Makefile target to print stack traces after running failing unit tests

apps/src/lib/node/ledger/ethereum_node/events.rs
Closes https://github.com/anoma/namada/issues/598
This PR makes sure that when building a `PendingTransfer` from a`RawTransfersToNamada` or`RawTransfersToEthereum` event, if the custom confirmations specified is less than (the protocol specified) `min_confirmations`, then `min_confirmations` is used instead.
=> Ensure minimum confirmations are enforced for pending Ethereum events

apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs
Partially resolve https://github.com/anoma/namada/issues/367
We check if:
1) A transaction is successfully validated by `process_tx`.
2) A transaction is not a decrypted tx, because these can only be crafted by block proposers.
We are not charging base fees to invalid encrypted txs, yet. This needs to be specced out, first.
=> Add extra `CheckTx` validation

.changelog/unreleased/ci/824-abcipp-ci.md, .github/workflows/checks.yml
Implicitly depends on https://github.com/anoma/namada/pull/754, which adds `make check-abcipp`
This PR makes it so that we run `make check-abcipp` in CI, to ensure that code continues to compile with the `abcipp` feature.
=> Run `make check-abcipp` in CI

shared/src/ledger/protocol/transactions/ethereum_events/mod.rs, shared/src/ledger/protocol/transactions/utils.rs, shared/src/ledger/protocol/transactions/validator_set_update/mod.rs, shared/src/ledger/protocol/transactions/votes.rs, shared/src/ledger/protocol/transactions/votes/update.rs, shared/src/types/voting_power.rs
Closes https://github.com/anoma/namada/issues/197
This PR makes it so that votes are applied for things (e.g. Ethereum events) which already exist in storage but that are not yet `seen = true`. There are also a couple of small changes to the `FractionalVotingPower` type.
=> Handle acting on tallied pieces of data that take longer than one round to confirm

.github/workflows/build-and-test-bridge.yml
Before running e2e tests in CI, we wait for a job with the name `namada-release-eth (ubuntu-latest, 1.7.0, ABCI Release build, namada-e2e-release, v2)` to finish. Currently, this job is called `namada-release-eth (ubuntu-latest, 1.7.0, ABCI Release build, anoma-e2e-release, v2)`, this PR attempts to update it so that it matches the expected name.
CI won't pass in this PR - we need to merge this branch and then see with another PR whether it worked or not.
=> Fix cache key in build-and-test-bridge.yml

.github/workflows/build-and-test-bridge.yml, apps/src/lib/config/genesis.rs, apps/src/lib/node/ledger/tendermint_node.rs
- make sure there are no `cargo check` warnings when `dev` feature isn't enabled (this isn't yet checked in CI I don't think)
- make sure abcipp compiles
- update nightly version in CI for eth bridge (this is fixed in `main` already)
=> Fix some CI in `eth-bridge-integration`

.changelog/unreleased/miscellaneous/667-tendermint-v0.1.4-abciplus.md, .github/workflows/build-and-test-bridge.yml, .github/workflows/build-and-test.yml, .github/workflows/build-tendermint.yml, docker/namada/Dockerfile, scripts/get_tendermint.sh
the versioning is not semver compliant - it's just for temp fork releases
=> switch to tendermint fork release v0.1.4-abciplus

.github/workflows/build-and-test-bridge.yml, apps/src/lib/config/genesis.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/tendermint_node.rs
Based on #771
Fixes ABCI++
The only relevant files are:
* `apps/src/lib/node/ledger/shell/vote_extensions.rs`
* `apps/src/lib/node/ledger/shell/prepare_proposal.rs`
Sorry about the shitty diff
=> Fix ABCI++ builds in `PrepareProposal`

documentation/specs/src/base-ledger/multisignature.md
* Replaced non-breaking space with space to fix faulty formatting. It caused header 2 to be formatted wrongly.
=> fix/931 Replaced non-breaking space with space to fix faulty formatting

apps/src/lib/node/ledger/shell/process_proposal.rs, documentation/specs/src/base-ledger/block-space-allocator.md
We were not checking if encrypted txs should have been rejected at a certain block height. This is now fixed.
=> Fix allocator logic in `ProcessProposal`

.github/workflows/release.yml
This misordering caused release CI to fail on 0.12.2.
=> ci: install cargo-about after sccache server up

ethereum_bridge/src/parameters.rs
Needed for https://github.com/anoma/namada/pull/810
This PR adds an `EthereumBridgeConfig::read` method and makes some other miscellaneous changes to the structs in `parameters.rs`
This is the only file being changed in PR https://github.com/anoma/namada/pull/810 that is under the `shared` directory, and so may move to `core`
=> Add `EthereumBridgeConfig::read` method

Makefile, apps/src/lib/node/ledger/shell/block_space_alloc/states.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, core/src/ledger/eth_bridge/storage/bridge_pool.rs
Minor PR that renames `ANOMA_DEV` to `NAMADA_DEV` in the makefile, and fixes the build of rust docs.
=> Fix `cargo doc` and the makefile

apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/queries.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs, ethereum_bridge/src/storage/mod.rs, proof_of_stake/src/pos_queries.rs, shared/src/ledger/eth_bridge.rs
This removes ethereum bridge related queries from the PosQueries trait and moves them under the ethereum bridge subcrate. Will extend it later to address review comments in PR #988
=> Add EthBridgeQueries trait for storage

apps/src/lib/cli.rs, documentation/docs/src/user-guide/ibc.md, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/helpers.rs, tests/src/e2e/ibc_tests.rs, tests/src/e2e/ledger_tests.rs
It's more common to refer to the cli option that connects to a fullnode as '--node'.
Created by running `git grep -l 'ledger-address' | xargs sed -i '' 's/ledger-address/node/g'`
Fixes #864
=> Rename '--ledger-address' to '--node'

apps/src/lib/config/ethereum_bridge/ledger.rs, apps/src/lib/node/ledger/mod.rs, apps/src/lib/node/ledger/shell/mod.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
This closes Issue #540. The size of the channel between the oracle and the ledger had a hardcoded default of 1000. This is now configurable in the oracle config params.
=> Added config parameter for the size of the oracle buffer

ethereum_bridge/Cargo.toml, ethereum_bridge/src/lib.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/mod.rs, shared/Cargo.toml, shared/src/ledger/protocol/mod.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
This PR adds test cases to cover a couple of scenarios discussed where a validator could attempt to vote twice on the same event:
- by including the same Ethereum event twice in a single vote extension
- by submitting multiple vote extensions for the same block height, each vote extension containing a same Ethereum event
=> Add some tests covering the application of duplicate Ethereum events/vote extensions

apps/src/lib/node/ledger/ethereum_node/events.rs, apps/src/lib/node/ledger/ethereum_node/oracle/mod.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, core/src/types/ethereum_events.rs
To calculate a transfer hash from this TransferToEthereum event
The latest smart contract returns [the event](https://github.com/anoma/ethereum-bridge/blob/c6389e5d8aeae0eb24d33dd83836c9ff4aace6a6/contracts/contract/Bridge.sol#L119) with the transfer info.
`TransferToErc`: https://github.com/anoma/ethereum-bridge/blob/c6389e5d8aeae0eb24d33dd83836c9ff4aace6a6/contracts/interface/ICommon.sol#L23
=> Update TransferToEthereum event definition

apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, core/src/ledger/eth_bridge/storage/mod.rs, core/src/types/vote_extensions.rs, core/src/types/vote_extensions/bridge_pool_roots.rs, ethereum_bridge/src/parameters.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs, shared/src/lib.rs
* Adds a storage key indicating the active status of the bridge. 
* Adds a quick query method to check if the bridge is active.
* Makes sure the vexts / protocol txs for eth events and bridge pool roots are not issued if the bridge is not active.
* Makes sure the vexts / protocol txs are not accepted if the the bridge is not active.
=> Change vext behavior if the bridge is inactive

apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, core/src/ledger/eth_bridge/storage/bridge_pool.rs, core/src/ledger/storage/merkle_tree.rs, core/src/ledger/storage/mod.rs, core/src/ledger/storage/traits.rs, core/src/types/eth_bridge_pool.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, ethereum_bridge/src/test_utils.rs, shared/src/ledger/queries/shell.rs, shared/src/ledger/queries/shell/eth_bridge.rs
- Add the inserted height to the Merkle tree of the bridge pool for the timeout checking
- Handle TransferToEthereum event
- Delete the pending transfers contained in the event
- Refund and delete for timed-out transfers
=> Handle TransferToEthereum

apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs
Closes https://github.com/anoma/namada/issues/1041
This PR makes it so that we don't unnecessarily check if we need to start the Ethereum oracle after every commit anymore (see https://github.com/anoma/namada/pull/810#discussion_r1073270956)
Most Ethereum bridge parameters should only ever be configured by hardforking and updating the network config toml (e.g. smart contract Ethereum addresses), that is, they shouldn't be changed via a transaction in a block (i.e. not via a governance proposal). For this reason, there are only two places we need to initially configure the oracle:
- `InitChain` - if the Ethereum bridge parameters are in the network config toml, we can start our oracle
- when creating the `Shell` on node start up - if we have synced/committed at least one block, then we're …
=> Optimize checking for whether we need to configure the Ethereum oracle or not

core/src/types/token.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/helpers.rs
Closes https://github.com/anoma/namada/issues/989
This PR makes it so that NAM is released from the bridge's account's balance, for confirmed wNAM transfers. Also adds an e2e helper `find_balance` for getting the balance of a Namada address for a specific regular token (e.g. NAM, i.e. not multitoken)
The end-to-end test currently gives the bridge VP an initial balance of NAM, which isn't realistic - this test should be updated so that the bridge VP gets it's balance of NAM from a transfer on chain.
=> Release NAM from the bridge pool to redeem wNAM transfers from Ethereum

apps/src/bin/namada-relayer/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge/validator_set.rs, shared/src/ledger/queries/shell/eth_bridge.rs
Based on #1159.
Implements item 6) of #242.
=> Relay validator set updates

ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, shared/src/ledger/native_vp/ethereum_bridge/authorize.rs, shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs, shared/src/ledger/native_vp/ethereum_bridge/vp.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/e2e/helpers.rs
Closes https://github.com/anoma/namada/issues/432 and relates to https://github.com/anoma/namada/issues/508
This PR
- ensures we check the relevant VPs are being executed for wrapped ERC20 transfers
- adds end-to-end tests covering
- transfers of DAI from Ethereum to implicit and established Namada accounts
- authorized transfers of wrapped DAI between implicit <-> established accounts once on Namada
- rejecting transactions that attempt to transfer wrapped DAI from implicit/established accounts, if the transactions aren't signed by the key which controls the sending account
NB: some helper fns added/used in this PR are also in https://github.com/anoma/namada/pull/886/files#diff-b26bbd416d9d500f8f12aee8f7b3182f35b5cacb748898d9c07fe2cdd41e69b8
=> Ensure wrapped ERC20 transfers are correctly authorized and add end-to-end tests for them

apps/src/bin/namada-relayer/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge/bridge_pool.rs, apps/src/lib/node/ledger/shell/mod.rs, core/src/types/ethereum_structs.rs, core/src/types/keccak.rs, core/src/types/storage.rs, ethereum_bridge/src/oracle/config.rs, ethereum_bridge/src/storage/proof.rs, shared/src/ledger/queries/shell/eth_bridge.rs, tests/src/e2e/eth_bridge_tests.rs
This PR adds more cli commands to `namadar` relating to the bridge pool.
* Constructing a proof manually returns more data about the batch
* Batches can now be relayed to the smart contracts directly with a new cli command
* A recommendation for a batch to be relayed can be generated.
=> Add bp relaying functionality to Namadar

tests/src/e2e/eth_bridge_tests.rs
This fills out an e2e test that now does the following:
* Adds a transfer to the pool
* Queries that it is added correctly
* Constructs a proof to be relayed
* Submits and ethereum event indicating successful relaying
* Checks that the transfer is removed from the bridge pool
=> Roundtrip Bridge pool test

apps/src/lib/node/ledger/ethereum_node/oracle/mod.rs, apps/src/lib/node/ledger/ethereum_node/test_tools/mod.rs, core/src/types/ethereum_structs.rs
The oracle correctly ensures whether or not it is syncning with the fullnode. A heartbeat is implemented to check responsiveness of the fullnode with a timeout in place. Exceeding the timeout shuts down the ledger.
=> Timeout unresponsive oracle

apps/src/lib/node/ledger/ethereum_oracle/control.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, core/src/ledger/eth_bridge/storage/mod.rs, core/src/ledger/parameters/mod.rs, core/src/ledger/parameters/storage.rs
This PR resolves issue #1080.
* Oracle storage has been moved under the control of the `Parameters` vp. This allows it to be changed by storage.
* Once an epoch, the shell sends the config in storage to the oracle.
* Since the oracle has no notion of epochs, after processing every ethereum blocks, checks if a new config has been sent.
=> Once an epoch, the ethereum oracle configuration gets updated

Cargo.lock, apps/Cargo.toml, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, core/src/types/storage.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs
* Only start proposing validator set updates an epoch before the bridge is enabled through governance, or while the bridge is active.
* Reject all current vote extension protocol transactions from the mempool, if the bridge is not active.
* Change `tracing::error!()` log lines to `tracing::debug!()` log lines, so node logs aren't spammed with validation logic.
* Remove the `index-set` crate from `apps`, as that was only required by the remaining txs allocator (now defunct).
* Convert PrepareProposal into CheckTx mempool tests.
=> Polish vote extension code

apps/src/lib/node/ledger/ethereum_oracle/events.rs, core/src/types/ethereum_events.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, shared/src/ledger/protocol/mod.rs
* Fix the `Ord` and `PartialOrd` implementation of Namada's `Uint` type.
+ Deriving `Ord` on `Uint` makes us compare the inner array, which has a little-endian representation. Some comparisons will be faulty, because of this, e.g. type `(1300).to_bytes(4, 'little') > (1236).to_bytes(4, 'little')` into a python repl.
* Implement `Copy` on `Uint`, for convenience.
=> Amend the `Ord` implementation of `Uint`

apps/src/lib/node/ledger/ethereum_oracle/events.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/storage/rocksdb.rs, core/src/ledger/eth_bridge/storage/bridge_pool.rs, core/src/ledger/storage/mockdb.rs, core/src/ledger/storage/mod.rs, core/src/types/ethereum_events.rs, core/src/types/storage.rs, ethereum_bridge/src/bridge_pool_vp.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs, ethereum_bridge/src/storage/vote_tallies.rs, shared/src/ledger/protocol/mod.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs
* Increment the nonce of the Bridge pool when we process `TransfersToEthereum` Ethereum events
* Increment the nonce of `TransfersToNamada` Ethereum events
* Reject Ethereum events with invalid nonces in `CheckTx` and `ProcessProposal`
* Process `TransfersToNamada` Ethereum events in order
**TODO:** Handle nonces derived from updates to the token whitelist
=> Handle Ethereum event nonces

apps/src/bin/namada-relayer/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge/validator_set.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, core/src/types/vote_extensions/ethereum_events.rs, core/src/types/vote_extensions/validator_set_update.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/utils.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs, ethereum_bridge/src/test_utils.rs, proof_of_stake/src/pos_queries.rs, shared/src/ledger/queries/shell/eth_bridge.rs
This should make our validator set naming schemes consistent with `main`.
=> Rename `active` to `consensus` validators

apps/src/lib/node/ledger/shell/finalize_block.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
The Bridge pool nonce should be incremented regardless of the validity of the relayed transfers to Ethereum. If we do not increment the nonce when processing a transfers to Ethereum event comprised solely of invalid transfers, Namada will fall out of sync with the nonce in the Ethereum bridge's smart contract.
=> Fix BP nonce increment

shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
Fix a bug in the Bridge pool's `escrow_check` method(*) and refactor the VP code a bit, for clarity.
(*) The code path of the bug was not being triggered. The logic of this method was faulty nonetheless.
=> Refactor Bridge pool VP

.github/workflows/build-and-test-bridge.yml, .github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/release.yml
follow-up to #1306 
added GITHUB_TOKEN to protoc installation to avoid GH API rate limit as per https://github.com/arduino/setup-protoc/issues/63
=> Install protoc to build with the new prost (3/n) 

apps/src/bin/namada-client/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge/bridge_pool.rs, apps/src/lib/client/eth_bridge/validator_set.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/wallet/mod.rs, shared/src/ledger/queries/shell/eth_bridge.rs
Closes https://github.com/anoma/namada/issues/1291
---
**TODO:** write e2e test that deletes a proof from storage, and uses the new `namadac` sub-command to generate the missing proof. on-going effort here: <https://p.sicp.me/nHvwQ>
=> Broadcast validator set update protocol txs from `namadac`

apps/src/lib/client/eth_bridge/bridge_pool.rs
Adjustment to https://github.com/anoma/namada/pull/1340
=> PR #1340 (adjustment 1)

apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge/bridge_pool.rs
Adjustment to https://github.com/anoma/namada/pull/1340
Addresses a review comment
=> PR #1340 (adjustment 2)

scripts/release.sh
It looks like no config file changes are required here.
=> release: bump supported cargo-release version to 0.24.4

apps/src/bin/namada-node/cli.rs, apps/src/lib/cli.rs, apps/src/lib/node/ledger/mod.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/e2e/helpers.rs
* Add e2e test that deletes a proof from storage, and uses the new `namadac` sub-command to generate the missing proof.
* Fix a docstring.
=> PR #1338 (adjustment 1)

.github/workflows/build-and-test.yml
We want CIs to start if the target branch is `main` or `maint-*`.
=> ci: run with maint-* target branch

.changelog/unreleased/bug-fixes/1405-bugfix-replay-prepare.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs
Implements stateful replay protection in `prepare_proposal` to avoid adding the same transaction more than once in a block
=> Stateful replay protection

Cargo.lock, tests/Cargo.toml, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
In order to use a more secure version of 'nix', bump expectrl to 0.7.0.
=> tests: bump expectrl to 0.7.0

.changelog/unreleased/features/1344-find-validator-by-tm.md, apps/src/bin/namada-client/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/rpc.rs, shared/src/ledger/args.rs, shared/src/ledger/queries/vp/pos.rs
adds `namadac find-validator --tm-address <>`
=> pos: add a query to find validator by Tendermint address

shared/src/ledger/tx.rs
follow-up to https://github.com/anoma/namada/pull/925
=> shared/tx/submit_validator_commission_change: print err even with force

apps/src/lib/cli.rs, shared/src/ledger/args.rs, shared/src/ledger/tx.rs
follow-up to https://github.com/anoma/namada/pull/925
=> cli: rename Tx arg `tx_code_path` to `tx_reveal_code_path`

shared/src/ledger/inflation.rs
=> Common sub-expression elimination in inflation calculation

Cargo.lock, Makefile, apps/Cargo.toml, core/Cargo.toml, shared/Cargo.toml
Closes https://github.com/anoma/namada/issues/1447
=> Remove ABCI++ dependencies

.changelog/unreleased/bug-fixes/1455-persist-epoch-update-delay.md, apps/src/lib/node/ledger/storage/rocksdb.rs, core/src/ledger/storage/mockdb.rs, core/src/ledger/storage/mod.rs
Persists a newly added storage field for epoch update blocks delay to be available after node restart when not `None`.
=> storage: persist `update_epoch_blocks_delay`

.changelog/unreleased/bug-fixes/1456-fix-max-wait-tries.md, apps/src/bin/namada-client/cli.rs
Based on #1258.
Fix off-by-one error. Stop waiting for start or catch-up when max tries are reached.
=> client: stop waiting for catch-up when max tries are reached

.changelog/unreleased/bug-fixes/1558-fix-slash-logging.md, apps/src/lib/client/rpc.rs, apps/src/lib/node/ledger/shell/mod.rs, proof_of_stake/src/lib.rs
Based on v0.17.1.
Fixes the output of the slash rate in `query_slashes`. Cleans up redundant logs when a misbehavior is detected and reported.
=> Small logging fixes for slashing

.changelog/unreleased/improvements/1491-utils-base-dir.md, apps/src/bin/namada-client/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/utils.rs
Add a utility command to print the default base directory that would be
used by the Namada command line if a base directory were not provided
on the command line or in the environment.
=> apps: add namadac utils default-base-dir

.changelog/unreleased/improvements/1404-ibc-event-query.md, Cargo.lock, apps/src/lib/node/ledger/shell/finalize_block.rs, shared/src/ledger/events.rs, shared/src/ledger/events/log/dumb_queries.rs, shared/src/ledger/queries/mod.rs, shared/src/ledger/queries/shell.rs, tests/Cargo.toml, tests/src/e2e/ibc_tests.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
closes #1358
To get IBC "update_client", "send_packet" and "write_acknowledgement" events for an IBC relayer without Tendermint index because Tendermint index is disabled by default.
=> Add IBC event queries

wasm/wasm_source/src/tx_change_validator_commission.rs
Fix for an invalid input as occurred here: https://github.com/anoma/namada/actions/runs/5289661416/jobs/9573106351#step:8:1107 - A range given to a strategy must have high > low.
=> test/wasm/tx_change_validator_commission: avoid low == high in gen range

.changelog/unreleased/bug-fixes/1588-fix-masp-missing-await.md, apps/src/lib/client/rpc.rs, shared/src/ledger/masp.rs
based on #1238 that introduced the change, fixes a missing `.await` as caught in #1586 by a new clippy version
=> shared/masp: add missing await on async load and save calls

tests/src/e2e/ledger_tests.rs
fix for https://github.com/anoma/namada/actions/runs/5347531283/jobs/9696134725 where the client tried to send a tx before the node's RPC was ready
=> test/e2e/invalid_txs: wait for a block after restart

.changelog/unreleased/features/1578-fix-init-validator-tm-mode.md, Cargo.lock, Cargo.toml, apps/Cargo.toml, apps/src/bin/namada-client/main.rs, apps/src/bin/namada-node/main.rs, apps/src/bin/namada/main.rs, apps/src/lib/logging.rs
=> add tracing-appender for log to files and rolling logs

.changelog/unreleased/improvements/64-clap-up-v4.md, Cargo.lock, Cargo.toml, apps/src/lib/cli.rs, apps/src/lib/cli/utils.rs
=> Update clap to the latest v4 version

.changelog/unreleased/bug-fixes/1582-slash-validator-delay-set-update.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, proof_of_stake/src/lib.rs, proof_of_stake/src/tests.rs, proof_of_stake/src/tests/state_machine.rs
Based on v0.17.4.
As caught by e.g. https://github.com/anoma/namada/actions/runs/5280174696/jobs/9551903699?pr=1569
When the epoch change conditions are met, we send validator set update to TM, which takes 2 blocks before the change applies. To stay in sync with TM, we delay epoch update by 2 blocks as well. However, when we receive slashable evidence and the validator set update has already been applied but we're not yet on the new epoch, we have to queue up slashed validator removal from validator set by another epoch.
=> PoS: delay slash validator set update when next epoch is done in TM

.changelog/unreleased/improvements/1604-update-wasmer-wasmparser.md, Cargo.lock, Cargo.toml, shared/Cargo.toml, shared/src/vm/host_env.rs, shared/src/vm/mod.rs, shared/src/vm/wasm/run.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
updating wasmer to 2.3.0 (not the latest which has breaking changes - wip in #1559) and wasmparser to latest to fix the warning that their transitive deps will not be compatible with future rust versions
=> deps: update wasmer and wasmparser crates

.changelog/unreleased/bug-fixes/1615-fix-optional-prefix-iter.md, apps/src/lib/node/ledger/storage/rocksdb.rs
Based on v0.17.4
The optional prefix iter did nothing when given `None` for prefix as shown by the test added in [3bf41d5](https://github.com/anoma/namada/pull/1615/commits/3bf41d54c213e3d5ea493a6755e5044fccdc818a). The problem was with the upper bound set on the iterator that should only be set when there is a non empty prefix - fixed in [82a07d8](https://github.com/anoma/namada/pull/1615/commits/82a07d8e731eb1cc8bb376a97d919d1a2165d11e). The same issue was already present before changes from #1478 on prefix iter with an empty key (i.e. `Key::default()`).
This affects the rollback command that relies on the iterator with no prefix.
=> fix optional prefix iter

scripts/release.sh
In `scripts/release.sh`, the command toward the end of the routine `unclog release --version $TAG_NAME` fails because `--version` is not a valid option.
=> Fix `unclog release` command

core/src/proto/types.rs, core/src/types/key/common.rs, core/src/types/key/ed25519.rs, core/src/types/key/mod.rs, core/src/types/key/secp256k1.rs, core/src/types/vote_extensions/validator_set_update.rs
Hash data to be signed with SHA256 by default, unless we specifically choose another hashing algorithm.
=> Ethereum related signing changes

.changelog/unreleased/improvements/1642-iter-prefix-full-match.md, apps/src/lib/node/ledger/storage/rocksdb.rs, core/src/ledger/storage/mockdb.rs
=> storage prefix iter: skip keys that don't match the full prefix segments

apps/src/lib/cli.rs
Without this fix, masp keys cannot be added using the client
=> missing arg for alias-force

tests/src/e2e/ledger_tests.rs
Looks like this change didn't make it into the 0.19.0 release, which still has this test failing. We found this resolution when initially trying to make the release before we ran into git issues.
=> Fix `test_genesis_validators`

tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
as seen in e.g. https://github.com/anoma/namada/actions/runs/5541777593/jobs/10115627826, sometimes the validator-0-copy is created after the original validator-0 has finished compiling its wasm, in which case the copy is created with the wasm cache. With this change, the copy is created only after original is done compiling
=> test/e2e/slashing: wait for wasm on original validator

Makefile
The MASP proof generation is taking too long and timing out in CI. Skipping until resolved.
=> CI: skip integration tests

.changelog/unreleased/bug-fixes/1774-fix-dec-display.md, core/src/types/dec.rs
The `Display` trait for `Dec` is buggy such that if I have a number `14000.000`, the number is displayed as `14`. We attempt to strip the zeros to the right of the `.` and the `.` itself, but we end up stripping all the zeros left-adjacent to the `.` as well. The stripping is fixed now.
v0.20.1
=> Fix Display for Dec

.changelog/unreleased/bug-fixes/1793-fix-unjail-bug.md, proof_of_stake/src/lib.rs, proof_of_stake/src/tests.rs, wasm/checksums.json
Resolves a bug in the error handling of `fn unjail_validator`.
This bug led to a failure in the testnet based on v0.20.1. In the testnet, a validator who had previously been jailed, and was eligible to unjail themselves, seems to have submitted an unjail transaction twice. The second submission mistakenly did not throw an error, leading to a second insertion of the validator back into the consensus set, which then led to a panic from CometBFT for duplicate validators.
closes #1790
v0.20.1
=> Fix bug in unjail-validator that crashed testnet v0.20.1

.changelog/unreleased/bug-fixes/1801-fix-available-memory.md, apps/src/lib/node/ledger/mod.rs
The available_memory unit was changed from `KB` to `Byte` when `sysinfo` was updated from v0.21.1 to v0.29.4 at #1695.
v0.21.1: https://docs.rs/sysinfo/0.21.1/sysinfo/trait.SystemExt.html#tymethod.available_memory
> Returns the amount of available RAM in KB.
v0.29.4: https://docs.rs/sysinfo/0.29.4/sysinfo/trait.SystemExt.html#tymethod.available_memory
> Returns the amount of available RAM in bytes.
The WASM cache size and the RocksDB cache size were huge due to this issue.
```
2023-08-09T19:07:13.014083Z  INFO namada_apps::node::ledger: VP WASM compilation cache size not configured, using 1/6 of available memory.
2023-08-09T19:07:13.014154Z  INFO namada_apps::node::ledger: Available memory: 29.93 TiB
2023-08-09T19:07:13.014163Z  INFO namada_apps::node::ledger: VP WASM compilation cache …
```
=> Fix available_memory

.changelog/unreleased/bug-fixes/1778-fix-wasm-vm-aarch64-mac.md, Cargo.lock, shared/Cargo.toml, shared/src/vm/wasm/run.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Switch to a wasmer revision based on 2.3.0 that fixes pointer misalignment issues on Apple silicon
Fixes https://github.com/wasmerio/wasmer/issues/4072
`v0.21.1`
=> Fix wasm pointer misalignment issues on Apple silicon

core/src/types/address.rs, core/src/types/masp.rs
We replace io::Error with an ErrorKind and String, and String when the error kind is not available.
This should allow future work to make the API for errors in our codebase easier to satisfy various traits we may wish to derive.
=> Remove io::Error from DecodeError

core/src/types/address.rs, core/src/types/masp.rs
These trait derivations should make it easier for code who wish
to ingest this type to themselves derive traits like Eq and Clone.
This Topic relies on #1818 as it sets the ground work for being able
to derive this information. However, this work can be done by hand
another way, and alternative strategies can be had to derive such
information
=> Deriving Traits for Address::DecodeError

shared/src/ledger/tx.rs, shared/src/vm/mod.rs
This topic simply makes `namada::ledger::tx::Error` cloneable. 
This will be used in future work
=> Make namada::ledger::tx::Error cloneable

apps/src/lib/client/tx.rs, shared/src/ledger/tx.rs
This commit simply removes a fair amount of boilerplate around building transaction. Before the same logic would be repeated 14 times. Which make future refactoring annoying, as the same solution would have to be done around 14 times.
Now we've abstracted it in a generic function called build, which prepares and builds the transaction
=> Abstract out the transaction builder into a generic build function

.changelog/unreleased/improvements/1828-feature-guard-masp-proof-load.md, Makefile, shared/src/ledger/masp.rs, shared/src/types/control_flow.rs
To avoid issues with using shared crate for web wasm build, the newly added #1768 is put behind "testing" feature. Additionally, `make check-crates` that runs in the CI is extended to ensure that the wasm for web can be built from shared crate.
=> "testing" feature guard masp proofs load/save

.changelog/unreleased/improvements/1848-wallet-bridge-pool-addr.md, apps/src/lib/wallet/defaults.rs
Adds the Bridge pool internal address as a default wallet address. This can be useful for checking the escrow of tokens under the Bridge pool.
`v0.21.1`
=> Add the Bridge pool as a default wallet address

.changelog/unreleased/improvements/1849-call-msg-parse.md, core/src/types/key/secp256k1.rs
When calling into `libsecp256k1` functions, we do not need to attempt to parse message digests. This is because we have a `[u8; 32]` value ready to be passed to the library code.
`v0.21.1`
=> Call `Message::parse` directly

.changelog/unreleased/improvements/1850-cli-parse-eth-addrs.md, apps/src/lib/cli/context.rs
Parse `Address` values from Ethereum addresses. This is useful for users who want to interact with wrapped ERC20 assets in Namada, without going through the pain of manually finding the bech32 encoding of the address (I did, it sucks).
`v0.21.1`
=> Parse Eth addresses from the CLI

.changelog/unreleased/bug-fixes/1860-duped-eth-tally-votes.md, ethereum_bridge/src/protocol/transactions/votes/update.rs
=> Log proper duped validator votes on Ethereum tallies

.changelog/unreleased/improvements/1863-unmerkle-replay-protection.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, core/src/ledger/replay_protection.rs, core/src/ledger/storage/mod.rs, core/src/ledger/storage/wl_storage.rs
Avoid adding the replay protection storage subkey to the merkle tree.
This does **NOT** address (not even partially) #1566.
v0.21.1
=> Don't merkelize replay protection keys

.changelog/unreleased/improvements/1468-custom-height-db-dump.md, apps/src/lib/cli.rs, apps/src/lib/node/ledger/mod.rs, apps/src/lib/node/ledger/storage/rocksdb.rs
Closes #1192.
Accepts an optional `height` parameter for the `dump-db` command to allow dumping the state at a specific block height.
Also buffers the write to the resulting file.
v0.20.1
=> Custom height db dump

.changelog/unreleased/bug-fixes/1835-fix-parallel-vps.md, core/src/ledger/gas.rs, shared/src/ledger/protocol/mod.rs
Currently, during the parallel execution of vps (more specifically in the `try_fold` function we use the `set` method of `VpsGas` to set the gas cost of the current Vp. This function only updates the `max` field as it assumes the `VpsGas` instance to have been just initialized and, therefore, be empty. From the rayon documentation though (https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.fold), it is stated that the sequence might be subdivided before being folded. In this case, more than on VP would be aggregated in one of these chunks and all of the VP following the first one would see a non-default `VpsGas` instance, i.e. an instance with the `max` field containing the gas cost of the previous vp. Given that the current implementation of `set` only overwrites …
=> Parallel vps' gas accounting rework

.changelog/unreleased/improvements/1865-eth-voting-power.md, core/src/types/token.rs, core/src/types/voting_power.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/utils.rs, ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs, ethereum_bridge/src/protocol/transactions/votes.rs, ethereum_bridge/src/protocol/transactions/votes/storage.rs, ethereum_bridge/src/protocol/transactions/votes/update.rs, ethereum_bridge/src/test_utils.rs, proof_of_stake/src/lib.rs, proof_of_stake/src/pos_queries.rs, shared/src/ledger/protocol/mod.rs, shared/src/ledger/queries/shell/eth_bridge.rs
Closes #1288
This PR changes the way voting across epochs on Ethereum tallies works. Instead of accounting for the average voting power available across all epochs $E$ some tally $t$ takes place in, $t$ is considered `seen` if its accumulated voting power is greater than $2/3 \max(\sigma(e) : e \in E)$, where $\sigma$ is the function that returns the voting power available in the input epoch.
With this strategy, tallies won't stall if they cross epoch boundaries, while still respecting the Tendermint BFT protocol's safety property (i.e. linearizability is preserved).
`v0.22.0`
=> Rework voting on Ethereum tallies across epoch boundaries

.changelog/unreleased/improvements/1874-remove-redundant-struct.md, benches/vps.rs, shared/src/ledger/protocol/mod.rs, shared/src/vm/wasm/run.rs
Removes enum `WasmPayload` in favor of `Commitment`.
v0.22.0
=> Removes redundant `WasmPayload` enum

.changelog/unreleased/improvements/1876-updating-contributing.md, CONTRIBUTING.md
=> Update CONTRIBUTING.md to properly outline how to document SDK changes

.changelog/unreleased/improvements/1877-refactor-get-fee-unshield.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, core/src/proto/types.rs, shared/src/ledger/protocol/mod.rs
Shared function to retrieve the masp `Transaction` object for fee unshielding.
v0.22.0
=> Refactor get fee unshield

.changelog/unreleased/SDK/1878-remove-sdk-fee-panics.md, .changelog/unreleased/bug-fixes/1878-remove-sdk-fee-panics.md, shared/src/ledger/signing.rs, shared/src/ledger/tx.rs, shared/src/types/error.rs
Removes some wrong `panic!` that were mistakenly brought into the sdk by the gas&fee pr.
v0.22.0
=> Removes fee panics from sdk

.changelog/unreleased/improvements/1882-minimum-gas-price.md, apps/src/lib/config/genesis.rs, apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, core/src/ledger/parameters/mod.rs, core/src/ledger/parameters/storage.rs, core/src/ledger/storage/mod.rs, genesis/dev.toml, genesis/e2e-tests-single-node.toml
The genesis file had `gas_cost` to indicate the `minimum_gas_price`, this hopefully makes it more clear what the parameter means.
`Namada v0.22.0`
=> changes gas_cost -> minimum_gas_price in the genesis file

.changelog/unreleased/improvements/1886-validators-by-hostnames.md, apps/src/lib/cli.rs, apps/src/lib/client/utils.rs, apps/src/lib/config/utils.rs, genesis/e2e-tests-single-node.toml, tests/src/e2e/helpers.rs, tests/src/e2e/setup.rs
Closes #576.
Closes #929.
Allows the usage of hostnames instead of IP addresses for validators in configuration.
v0.22.0
=> Support validators' hostnames in config

.changelog/unreleased/bug-fixes/1889-respect-force-option.md, shared/src/ledger/tx.rs
=> Respect force option for proposal vote transaction

.changelog/unreleased/improvements/1892-bridge-pool-zero-fees.md, shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
This patch makes the ledger validate Bridge pool transfers that move no value (either gas fees, or token amounts). This is not necessarily an incorrect behavior per se, albeit an unlikely one, with honest actors in the system. Might be useful to some people, though.
`v0.22.0`
=> Validate txs moving 0 value to the Bridge pool

.changelog/unreleased/bug-fixes/1893-bridge-pool-roots-signing.md, core/src/types/storage.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/storage/vote_tallies.rs, shared/src/ledger/protocol/mod.rs
Only write signed Bridge pool proofs to storage if they are more recent than the previously available proof in storage.
`v0.22.0`
=> Never overwrite recent Bridge pool proofs in storage

.changelog/unreleased/SDK/1894-sdk-async-traits-send.md, .changelog/unreleased/improvements/1894-sdk-async-traits-send.md, apps/src/lib/client/tx.rs, apps/src/lib/node/ledger/shell/testing/node.rs, benches/lib.rs, shared/Cargo.toml, shared/src/ledger/masp.rs, shared/src/ledger/queries/mod.rs, shared/src/ledger/queries/types.rs
Requires the `Send` bound on the `async_traits`s in the SDK. This allow the usage of the SDK in an environment which is both async and multithread (see https://rust-lang.github.io/async-book/07_workarounds/03_send_approximation.html).
v0.22.0
=> Makes async traits in the SDK be `Send`

.changelog/unreleased/improvements/1865-eth-voting-power.md, .changelog/unreleased/improvements/1899-retransmit-expired-eth-events.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, core/src/ledger/storage/mod.rs, core/src/types/internal.rs, core/src/types/token.rs, core/src/types/voting_power.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/utils.rs, ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs, ethereum_bridge/src/protocol/transactions/votes.rs, ethereum_bridge/src/protocol/transactions/votes/storage.rs, ethereum_bridge/src/protocol/transactions/votes/update.rs, ethereum_bridge/src/test_utils.rs, proof_of_stake/src/lib.rs, proof_of_stake/src/pos_queries.rs, shared/src/ledger/protocol/mod.rs, shared/src/ledger/queries/shell/eth_bridge.rs
In case an Ethereum event times out with $>\frac{1}{3}$ voting power accumulated behind it, it may be proposed once more during the **COMMIT** phase of the protocol, such that its state updates may be reconsidered. BFT protocols often have this notion of weak certificates on proposed data (e.g. see Sousa et al. in Mod-SMaRt).
Based on #1865
=> Retransmit some timed out Ethereum events

Makefile, ethereum_bridge/Cargo.toml
Enables to e.g. `cd ethereum_bridge && cargo test` with default features
- ~~[ ] I have added a changelog~~
=> fix and check namada_ethereum_bridge crate build with default features

.changelog/unreleased/bug-fixes/1904-ibc-host-fn-workaround.md, shared/src/vm/host_env.rs, shared/src/vm/mod.rs, shared/src/vm/wasm/host_env.rs, tx_prelude/src/lib.rs, vm_env/src/lib.rs, wasm/wasm_source/src/tx_ibc.rs
As a workaround for #1831, the IBC tx execution is added as a native host fn.
0.22.0
=> add ibc tx host fn to workaround M1/2 WASM compilation issue

.github/workflows/build-and-test.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/triggerable.yml
- added `ubuntu22` and `windows` to the build release binaries step
=> ci: support more os when building release binaries 

.changelog/unreleased/bug-fixes/1991-fix-pgf-payment-crash.md, apps/src/lib/node/ledger/shell/governance.rs
Fixes a bug for which the ledger crashed in case of a failed PGF payment.
Commit 3f979bf3b2707db4d065a4fae6e8c2340ae1d54b from `base` branch
=> Prevent crash on failed pgf payment

.changelog/unreleased/bug-fixes/1999-fix-pgf-stewards-funding.md, apps/src/lib/node/ledger/shell/finalize_block.rs
Makes the reward of pff stewards constant regardless of the number of stewards.
v0.23.1
=> Fixes pgf inflation

.changelog/unreleased/improvements/2001-no-tx-broadcast-on-sync.md, apps/src/lib/node/ledger/broadcaster.rs
=> Wait for a node to sync before broadcasting protocol txs

.changelog/unreleased/improvements/2012-sign-eth-txs.md, apps/src/lib/cli/relayer.rs, apps/src/lib/cli/utils.rs
Introduce an environment variable to load a secp256k1 private key from, which is used to sign transactions originating from Namada's relayer sent to Ethereum.
This implementation is kinda hacky, but it should allow immediate testing with e.g. [Sepolia](https://sepolia.dev/). There are for sure ways to improve it, in the future, namely:
- Loading keys from other sources (e.g. `namadaw`, `ledger`, or `aws kms`)
- Deriving the `ethereum-address` SDK/CLI argument from a `Signer` implementation (see [this link](https://docs.rs/ethers/2.0.6/ethers/signers/trait.Signer.html#tymethod.address))
Notice that the SDK code remains unchanged. This is because it accepts a `Middleware` client, which may or may not sign txs.
`v0.23.0`
=> Sign relayer Ethereum transactions

.changelog/unreleased/improvements/1973-refine-commission-tx.md, proof_of_stake/src/lib.rs, shared/src/sdk/tx.rs
Add some missing checks for validator commissione rate change tx and clean up some old code.
v0.23.0
=> Refine commission rate change tx

.changelog/unreleased/bug-fixes/1964-fix-protocol-txs.md, .changelog/unreleased/testing/1976-int-test-services.md, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/ethereum_oracle/test_tools/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/testing/node.rs, tests/src/integration/masp.rs, tests/src/integration/setup.rs
=> Mock ledger services in integration tests

.changelog/unreleased/improvements/1979-proposal-result-in-storage.md, apps/src/lib/client/rpc.rs, apps/src/lib/node/ledger/shell/governance.rs, core/src/ledger/governance/storage/keys.rs, core/src/ledger/governance/utils.rs
Store the result of a governance proposal under the corresponding storage subkey. This allows to recover the result even after the validator set has changed.
Also, update the client to leverage this key in storage if present to avoid recomputing the result. 
Commit 3f979bf3b2707db4d065a4fae6e8c2340ae1d54b on `base` branch
=> Write governance proposal results to storage

.changelog/unreleased/bug-fixes/1984-rm-redundant-writes.md, core/src/ledger/storage_api/collections/lazy_map.rs, core/src/ledger/storage_api/collections/lazy_set.rs
=> core/lazy_map+set: avoid calling delete when given key is not present

.changelog/unreleased/bug-fixes/1989-fix-ibc-client-validation.md, Cargo.lock, core/Cargo.toml, wasm/Cargo.lock
Apply the [patched ibc-rs](https://github.com/heliaxdev/cosmos-ibc-rs/commit/206cb5fa74a7ca38038b937d202ae39fbbd63c19) (based on `v0.41.0`) for ibc-rs [#911](https://github.com/cosmos/ibc-rs/issues/911)
We will update `ibc-rs` to `v0.46.0` including the fix.
`v0.23.0`
=> update ibc-rs for ibc-rs/#911

.changelog/unreleased/bug-fixes/1949-pow-solution-fix.md, apps/src/lib/node/ledger/shell/process_proposal.rs, core/src/types/transaction/wrapper.rs
Removal of the `pub pow_solution: Option<crate::ledger::testnet_pow::Solution>` field from `WrapperTx` broke hardware wallet support for Namada `Tx`s. This PR reintroduces the field, albeit in a degenerate form.
v0.23.0 .
=> Dummy PoW solution field for hardware wallet

.changelog/unreleased/miscellaneous/1958-k256.md, .changelog/unreleased/miscellaneous/1958-zeroize-secret-keys.md, Cargo.lock, Cargo.toml, apps/src/lib/node/ledger/shell/mod.rs, core/Cargo.toml, core/src/types/key/ed25519.rs, core/src/types/key/mod.rs, core/src/types/key/secp256k1.rs, ethereum_bridge/Cargo.toml, shared/Cargo.toml, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
- Tag `ed25519` keys with `ZeroizeOnDrop`, to indicate their bytes are cleared uppon the key being dropped.
- ~~Switch to `k256` for `secp256k1` keys. It natively implements `Zeroize`~~ - done in base #1958
#1958 (first commit here 609e70d62ce56842633b85aab5958d0324122416)
=> Add `ZeroizeOnDrop` to ed25519 keys

.changelog/unreleased/miscellaneous/1958-k256.md, Cargo.lock, Cargo.toml, apps/src/lib/node/ledger/shell/mod.rs, core/Cargo.toml, core/src/types/key/mod.rs, core/src/types/key/secp256k1.rs, ethereum_bridge/Cargo.toml, shared/Cargo.toml, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
We already have k256 in transitive deps from e.g. `tendermint-rs`. See also a post describing k256: https://iqlusion.blog/k256-crate-pure-rust-projective-secp256k1-library
0.23.0
=> deps: switch from libsecp256k1 to k256

.changelog/unreleased/bug-fixes/1964-fix-protocol-txs.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs
A bug was introduced by #1899 where no protocol txs are broadcasted to the network, unless the Ethereum oracle is enabled. This PR fixes the underlying issue.
`v0.23.0`
=> Fix transmitting protocol txs if validator node

.changelog/unreleased/improvements/1888-ledger-test-vector-generator-fix-0.22.0.md, scripts/generator.sh, shared/src/sdk/signing.rs, shared/src/sdk/tx.rs
* Updated the hardware wallet test vector generation script to be compatible with latest CLI
* Updated the formatting of various test vectors and changed vector content where necessary
* Made vote proposal respect the force flag and made unjail validator generate vector even if the action is not possible
This is based on the previous branch `aleks/ledger-test-vector-generator-fix-0.21.1`
=> Ledger test vector formatting changes

.changelog/unreleased/improvements/1954-gas-in-sig-ver.md, benches/host_env.rs, core/src/proto/types.rs, core/src/types/key/mod.rs, shared/src/vm/host_env.rs, tests/src/vm_host_env/mod.rs
Moves the gas accounting for the signature verification in the `verify_signature` method of `Signature` for higher resolution (i.e. being able to short circuit early in case of an out-of-gas event).
v0.23.0
=> Moves signatures verification gas in `Signature`

.changelog/unreleased/improvements/1955-avoid-testing-feature-in-workspace.md, Cargo.lock, apps/Cargo.toml, apps/src/lib/bench_utils.rs, apps/src/lib/config/genesis.rs, apps/src/lib/mod.rs, benches/Cargo.toml, benches/README.md, benches/native_vps.rs, benches/process_wrapper.rs, benches/txs.rs, benches/vps.rs
The changes from #1907 inadvertently affected the whole workspace as benches have non-dev dependency on `namada` and `namada_apps` with `"testing"` feature on, which in turn enables the `"dev"` feature. This means that in 0.23.0 building from the root would switch on these features by default even for the build of the binaries (e.g. `cargo build` or `cargo run`).
- To fix this 0613ac2c3a1bcc749cb4f1112e1b923220f76c5d moves the library code of benches that requires the `"testing"` feature into namada_apps crate and feature-guard it with the same feature `"testing"`. This allowed to switch all the `[dependencies]` in benches to `[dev-dependencies]` and so the workspace build is no longer affected by these.
- 4dc0304d2f38ac49c0779000f61b77baf6eecece - updates docs for bench
- …
=> avoid enabling "testing" feature in workspace from benches

.changelog/unreleased/bug-fixes/2047-win-build.md, apps/Cargo.toml
rocksdb (tikv-)jemalloc is not supported on windows (https://github.com/tikv/jemallocator#platform-support)
0.25.0
=> apps: turn off rocksdb jemalloc on windows

.changelog/unreleased/improvements/2064-wasm-download.md, apps/src/lib/wasm_loader/mod.rs
Let the user configure from where to download the precompiled wasm files.
0.24.0
=> wasm server download via env

apps/src/lib/node/ledger/shell/mod.rs, shared/src/vm/wasm/compilation_cache/common.rs
Remove `loope` size check for wasm vp/tx caching.
0.24.0
=> fix: vp/tx wasm caching

.changelog/unreleased/SDK/2128-governance-abstain-vote.md, .changelog/unreleased/features/2128-governance-abstain-vote.md, apps/src/lib/client/rpc.rs, apps/src/lib/node/ledger/shell/governance.rs, core/src/ledger/governance/cli/offline.rs, core/src/ledger/governance/cli/onchain.rs, core/src/ledger/governance/storage/vote.rs, core/src/ledger/governance/utils.rs, sdk/src/signing.rs, tests/src/e2e/ledger_tests.rs
Closes #2090.
Implements the `Abstain` governance vote. Also reviews the tally process for the different proposal types.
Commit 3a0ecd89e8bfea1ca1eda7887d562666674a41d8 on `base` (v0.25.0)
=> Governance `Abstain` vote

.changelog/unreleased/bug-fixes/2133-fix-governance-bugs.md, apps/src/lib/node/ledger/shell/finalize_block.rs, proof_of_stake/src/lib.rs, shared/src/ledger/governance/mod.rs
Closes #1107.
Fixes the `is_delegator` function in the governance vp which could return true also for validators with self bonds.
Corrects the inflation mechanism for pgf.
Commit 3a0ecd89e8bfea1ca1eda7887d562666674a41d8 on `base` (v0.25.0)
=> Fix governance bugs

.changelog/unreleased/bug-fixes/2100-win-build.md, Cargo.toml
Follow-up to #2047, we have to remove jemalloc from rocksdb workspace features to support win build.
0.25.0
=> Win build, attempt #2

.changelog/unreleased/improvements/2046-ibc-token-addr.md, apps/src/lib/client/rpc.rs, core/src/ledger/ibc/storage.rs, core/src/types/address.rs, core/src/types/ibc.rs, sdk/src/rpc.rs, tests/src/native_vp/pos.rs
Precursor to #2018
This PR swaps IBC token hashes stored in the `Address` type as `String` values with new `IbcTokenHash` values, which internally are represented by an array of 20 bytes.
`v0.25.0`
=> IBC token hash type for addresses

.changelog/unreleased/improvements/2132-better-err-reports.md, apps/src/lib/config/genesis/templates.rs, apps/src/lib/node/ledger/shell/mod.rs, shared/src/ledger/protocol/mod.rs
Helps to add more context to some errors.
0.26.0
=> print eyre errors with inner errors

.changelog/unreleased/miscellaneous/2145-pos-vp-no-catch.md, shared/src/ledger/pos/vp.rs, shared/src/ledger/protocol/mod.rs
closes #21. We are safe to remove the temp panic catcher as the PoS VP currently only handles PoS params validation.
v0.25.0
=> protocol: remove `panic::catch_unwind` for PoS VP

.changelog/unreleased/improvements/2163-init-validator-own-keys.md, apps/src/lib/bench_utils.rs, apps/src/lib/client/tx.rs, benches/host_env.rs, benches/native_vps.rs, benches/process_wrapper.rs, benches/txs.rs, benches/vps.rs, core/src/proto/types.rs, core/src/types/key/mod.rs, sdk/src/signing.rs, shared/src/vm/host_env.rs, shared/src/vm/wasm/host_env.rs, tests/src/vm_host_env/mod.rs, tests/src/vm_host_env/tx.rs, tx_prelude/src/lib.rs, vm_env/src/lib.rs, wasm/wasm_source/src/tx_init_validator.rs
=> init validator tx - verify ownership of used keys

.changelog/unreleased/bug-fixes/2164-fix-sdk-feature-flag.md, sdk/Cargo.toml
=> Add rand flag for sdk

.changelog/unreleased/improvements/2169-pos-sigs-for-vp.md, .github/workflows/scripts/e2e.json, proof_of_stake/src/storage.rs, tests/src/e2e/ledger_tests.rs, vp_prelude/src/lib.rs, wasm/wasm_source/src/vp_implicit.rs, wasm/wasm_source/src/vp_user.rs, wasm/wasm_source/src/vp_validator.rs
=> More checks for certain PoS transactions in validator VP

.changelog/unreleased/SDK/2140-sdk-redelegate.md, sdk/src/args.rs, sdk/src/lib.rs, sdk/src/tx.rs
Most of the redelegation functionality was already there, I just added the high level functions to the sdk to be called.
v0.26.0
Rebased version of #2140
=> Add redelegation functionality

.changelog/unreleased/improvements/2178-misc-pos-tasks.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, ethereum_bridge/src/test_utils.rs, proof_of_stake/src/epoched.rs, proof_of_stake/src/lib.rs, proof_of_stake/src/pos_queries.rs, proof_of_stake/src/rewards.rs, proof_of_stake/src/tests.rs, proof_of_stake/src/types.rs
Closes #17, closes #1270. Some other things addressed in this PR:
- rename `store_total_consensus_stake` to `compute_and_store_total_consensus_stake`
- Improves docstrings, comments, and logging
- Removes outdated TODOs in PoS
- `is_delegator` issue
v0.26.0
=> Misc PoS tasks

.changelog/unreleased/bug-fixes/2184-fix-abci-last-height-queries.md, sdk/src/queries/shell.rs
=> Fix ABCI queries at the last committed height

.changelog/unreleased/improvements/2189-save-conversion-state.md, apps/src/lib/bench_utils.rs, apps/src/lib/client/rpc.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/init_chain.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/storage/mod.rs, apps/src/lib/node/ledger/storage/rocksdb.rs, core/src/ledger/masp_conversions.rs, core/src/ledger/mod.rs, core/src/ledger/storage/mockdb.rs, core/src/ledger/storage/mod.rs, core/src/types/token.rs, sdk/src/queries/shell.rs, sdk/src/rpc.rs
=> Save conversion state into the state storage

.changelog/unreleased/miscellaneous/2233-upgrade-borsh.md, Cargo.lock, Cargo.toml, apps/Cargo.toml, core/src/types/key/ed25519.rs, core/src/types/key/secp256k1.rs, encoding_spec/src/main.rs, sdk/Cargo.toml, sdk/src/masp.rs, shared/Cargo.toml, shared/src/ledger/mod.rs, wasm/Cargo.lock, wasm/tx_template/Cargo.toml, wasm/vp_template/Cargo.toml, wasm/wasm_source/Cargo.toml, wasm_for_tests/wasm_source/Cargo.lock
Closes #1563
* Needs the following downstream dependency upgrades:
* ~~https://github.com/anoma/masp/tree/adrian/upgrade_borsh~~ - [released as v1.0.0](https://github.com/anoma/masp/releases/tag/v1.0.0)
* https://github.com/heliaxdev/sparse-merkle-tree/tree/adrian/upgrade_borsh
* ~~https://github.com/heliaxdev/index-set/tree/adrian/upgrade_borsh~~ - [released as v0.8.1](https://github.com/heliaxdev/index-set/releases/tag/v0.8.1)
* ~~https://github.com/heliaxdev/borsh-ext/tree/adrian/upgrade_borsh~~ - [released as v1.2.0](https://github.com/heliaxdev/borsh-ext/releases/tag/v1.2.0)
`v0.27.0`
=> Upgrade borsh to v1.2.0

.changelog/unreleased/improvements/2246-fix-liveness.md, proof_of_stake/src/lib.rs, sdk/src/queries/vp/pos.rs, sdk/src/rpc.rs, sdk/src/tx.rs
The client checks for submitting an unjail tx were not updated to consider jailing due to liveness only. More specifically, now an unjail tx should be allowed if no data is found for the last infraction epoch of a currently jailed validator, since the validator can be jailed due to liveness requirements. This is resolved in the PR.
v0.27.0
=> Fix liveness unjailing

.changelog/unreleased/bug-fixes/2035-outdated-eth-nonces.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/storage/eth_bridge_queries.rs
Fixes Ethereum event validation/state updates when more than one validator is running the chain.
Specifically, before this patchset, validators would reject block proposals containing vote extensions storing Ethereum events with an invalid (outdated) nonce. This would hinder in the best case the latency of Ethereum bridge operations, and in the worst case its liveness, since events with nonces that could be processed would be mixed with events with outdated nonces.
With these changes, we allow extensions with at least one good event to be processed, and ignore state updates from events with invalid nonces.
`v0.23.0`
=> Outdated Ethereum event nonce fixes

.changelog/unreleased/improvements/2215-vp-less-permissive.md, shared/src/vm/wasm/compilation_cache/common.rs
=> wasm: handle cache loading errors

.changelog/unreleased/improvements/2217-upgrade-pos-rewards.md, apps/src/lib/cli.rs, apps/src/lib/cli/client.rs, apps/src/lib/client/rpc.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, proof_of_stake/src/lib.rs, sdk/src/args.rs, sdk/src/queries/vp/pos.rs, tests/src/e2e/ledger_tests.rs
Some upgrades related to proof-of-stake rewards:
- provide a CLI query for the pending rewards of a bond
- fix a bug in the slash computation when computing rewards
v0.27.0
=> Pos Reward Updates

.changelog/unreleased/SDK/2225-remove-sdk-lifetimes.md, apps/src/bin/namada-client/main.rs, apps/src/bin/namada-relayer/main.rs, apps/src/lib/bench_utils.rs, apps/src/lib/cli/client.rs, apps/src/lib/cli/context.rs, apps/src/lib/cli/relayer.rs, apps/src/lib/client/rpc.rs, apps/src/lib/client/tx.rs, apps/src/lib/node/ledger/shell/testing/client.rs, benches/native_vps.rs, benches/txs.rs, sdk/src/args.rs, sdk/src/eth_bridge/bridge_pool.rs, sdk/src/eth_bridge/validator_set.rs, sdk/src/lib.rs, sdk/src/masp.rs, sdk/src/rpc.rs, sdk/src/signing.rs, sdk/src/tx.rs
Modified the `Namada` trait and implementation to own its their clients, streams, wallet, and shielded utilities. Then removed all the redundant lifetimes. This was relatively straightforward because it was rare that after a `NamadaImpl` has been instantiated that any other object would want to own the client, streams, wallet, or shielded utilities.
Namada 0.27.0
=> Removed uses of lifetimes in the SDKs Namada trait and implementation

.changelog/unreleased/bug-fixes/2230-masp-rewards.md, core/Cargo.toml, core/src/ledger/masp_conversions.rs, core/src/types/dec.rs
Added a test for `fn update_allowed_conversions` and fixed a possible underflow ([b41393e](https://github.com/anoma/namada/pull/2230/commits/b41393ea59634eb199949e77c29052d7f571c0f2)).
v0.27.0
=> fix masp rewards underflow

.changelog/unreleased/bug-fixes/2325-db-rm-recursion.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/storage/rocksdb.rs, core/src/ledger/replay_protection.rs, core/src/ledger/storage/mockdb.rs, core/src/ledger/storage/mod.rs, core/src/ledger/storage/types.rs, core/src/ledger/storage/write_log.rs
Also fixed replay protection prefix iterator that was causing this recursion stack size to grow with every tx. To help avoid these issues in future, I also added `tracing::warn` for when we get an unmatched prefix (which falls back to go to the next iterator item). 
0.28.1
=> rocksdb: replace recursion from prefix iterator with a loop

core/src/types/dec.rs
- updated comment provides a detailed explanation of how trunc_div works
=> docs for trunc_div functio

.changelog/unreleased/features/2260-wallet-cli-revamping-main-rebased.md, apps/src/lib/cli.rs, apps/src/lib/cli/wallet.rs, sdk/src/args.rs, sdk/src/wallet/mod.rs, sdk/src/wallet/store.rs, tests/src/e2e/helpers.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/wallet_tests.rs
This PR introduces a revamped structure of the wallet CLI suggested in #2135. The changes are based on v0.28.0.
The following changes were additionally introduced.
- For consistency, `--alias` argument is made obligatory for `gen` / `derive` commands.
- Raw (non-HD) key generation functionality is restored, hidden under `--raw` flag.
Example: `namadaw gen --raw --alias key1`
- Fix alias string normalization
- Implemented `export` for MASP spending keys
- Implemented `import` for secret keys / MASP spending keys
- Implement `add` for secret keys
- Simplified interface of `add` command. Example: `namadaw add --alias my_entry --value val`. The supported values: 
+ secret key
+ public key
+ namada address
+ MASP spending key / viewing key / payment address
- Introduced bi-map for the …
=> CLI revamp - 0.28.0

.changelog/unreleased/improvments/2285-remove-hardcoded-masp-tokens.md, apps/src/lib/cli.rs, apps/src/lib/cli/client.rs, apps/src/lib/client/rpc.rs, core/src/ledger/masp_conversions.rs, sdk/src/queries/shell.rs, sdk/src/rpc.rs
Fixes #2283 
Previously, a hardcoded set of tokens were expected to be used in Masp conversions.
If these tokens did not have configs in genesis, this would lead to a panic after the first 
epoch change. This PR fixes this to use the tokens found in genesis belonging to the MASP
rewards whitelist instead of hardcoding the tokens.
v0.28
=> Masp conversions doesn't require all tokens be in genesis

.changelog/unreleased/improvements/2294-move-gain-params-to-pos.md, apps/src/lib/config/genesis.rs, apps/src/lib/config/genesis/chain.rs, apps/src/lib/config/genesis/templates.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/storage/mod.rs, core/src/ledger/masp_conversions.rs, core/src/ledger/parameters/mod.rs, core/src/ledger/parameters/storage.rs, core/src/ledger/storage/mod.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml, proof_of_stake/src/parameters.rs
=> Move pos gain params to PosParams

.changelog/unreleased/bug-fixes/2310-wait-for-genesis-time.md, apps/src/lib/node/ledger/mod.rs, sdk/src/control_flow/mod.rs
Make the ledger wait for genesis before starting up any processes
v0.28
=> Wait for genesis time

.changelog/unreleased/SDK/2308-fix-ibc-gen-shielded.md, .changelog/unreleased/bug-fixes/2308-fix-ibc-gen-shielded.md, apps/src/lib/cli.rs, sdk/src/args.rs, sdk/src/rpc.rs, sdk/src/tx.rs, tests/src/e2e/ibc_tests.rs
closes #2308
closes #2309
`ibc-gen-shielded` should get not only a Namada token but also a non-Namada token to transfer it from non-Namada chains
`v0.28.1`
=> Fix ibc-gen-shielded to receive a non-Namada token

.changelog/unreleased/SDK/2321-ibc_shielded_transfer.md, .changelog/unreleased/features/2321-ibc_shielded_transfer.md, apps/src/lib/cli.rs, apps/src/lib/client/tx.rs, core/src/ledger/ibc/mod.rs, core/src/ledger/vp_env.rs, core/src/types/ibc.rs, sdk/src/args.rs, sdk/src/lib.rs, sdk/src/tx.rs, tests/src/e2e/ibc_tests.rs
closes #2314 
- Change the `source` type in `ibc-transfer` to `TransferSource` to set a spending key
- Add `MsgShieldedTransfer` to pass `token::Transfer` and MASP tx with `MsgTransfer`
- Call `handle_masp_tx` after `send_transfer_execute` in `IbcActions` if it's a shielded transfer
- Modify an E2E test to send a token from a spending key to a payment key on another Namada
`v0.28.1`
=> IBC transfer from a spending key

.changelog/unreleased/SDK/1995-eth-tx-emits-events.md, .changelog/unreleased/improvements/1995-eth-tx-emits-events.md, apps/src/lib/node/ledger/shell/finalize_block.rs, core/src/types/ethereum_structs.rs, core/src/types/keccak.rs, core/src/types/transaction/mod.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, sdk/src/eth_bridge/bridge_pool.rs, sdk/src/events/mod.rs, sdk/src/queries/mod.rs, sdk/src/queries/shell/eth_bridge.rs, shared/src/ledger/protocol/mod.rs
Ethereum Bridge pool transfer events are useful to the Namada web interface. They should allow informing users whether their transfers have expired from the Bridge pool, or if they have been successfully relayed.
Since Namada's event log size is finite (currently, IIRC it's hard-coded to 50k slots), the query may fail with an "incomplete" state. The gist is, when a transfer is neither in the Bridge pool nor in the event log, it's because it has either been relayed or expired. The only way to consult this is to go through each block height since the transfer was first sent to the Bridge pool, until a Bridge pool event containing the transfer hash is found. This is not implemented on purpose, as it requires querying a potentially huge number of blocks.
`v0.28.0`
=> Emit Ethereum Bridge pool transfer events

.changelog/unreleased/improvements/2127-basic-abstraction.md, apps/src/lib/client/tx.rs, apps/src/lib/client/utils.rs, apps/src/lib/node/ledger/tendermint_node.rs
Cleaning up logic pertaining to writing and reading configuration files.
This code has no outward affects, purely for code quality
0.28.1
=> Abstract tendermint_node

.changelog/unreleased/improvements/2213-vp-less-permissive.md, benches/vps.rs, core/src/types/address.rs, core/src/types/ibc.rs, proof_of_stake/src/storage.rs, wasm/wasm_source/src/vp_implicit.rs, wasm/wasm_source/src/vp_user.rs
fixes #408
Unknown changes in vp_user and vp_implicit now require valid signature(s). 
For PoS changes, we have to check against all possible storage changes that can be applied from a tx and require signature(s) for those that have to be authorized by the source (for vp_user it can be both delegator and validator actions, for vp_implicit only delegator actions). If the change within PoS account subspace is not recognized we default to require sig(s).
To ease debugging in vp_user and vp_implicit, I changed the logging of rejected keys to also be be emitted in release build.
v0.28.0
=> less permissive VPs

.changelog/unreleased/testing/2218-update-consensus-key-change.md, .github/workflows/scripts/e2e.json, apps/src/lib/cli.rs, apps/src/lib/client/tx.rs, benches/txs.rs, sdk/src/args.rs, sdk/src/lib.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/e2e/helpers.rs, tests/src/e2e/ibc_tests.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs, wasm/wasm_source/src/tx_change_consensus_key.rs
Add an e2e test and require to sign the tx with the new consensus key.
v0.28.1
=> Update consensus key change

.changelog/unreleased/bug-fixes/2240-nullifier-uniqueness.md, core/src/ledger/masp_utils.rs, core/src/ledger/mod.rs, core/src/ledger/storage/write_log.rs, core/src/types/token.rs, shared/src/ledger/native_vp/ibc/context.rs, shared/src/ledger/native_vp/masp.rs, shared/src/vm/host_env.rs, tx_prelude/src/ibc.rs, tx_prelude/src/token.rs, wasm/wasm_source/src/tx_transfer.rs
Addresses #1373.
Implements a nullifier set to prevent double spending in masp transactions. Updates the masp VP to check that the transactions writes the correct nullifiers and that these haven't already been revealed.
**NOTE**: testing this with an integration or e2e test is impossible cause we cannot force the submission of the tx if the builder fails to construct the shielded `Transaction`. We'd need to test this with a unit test (which I think would be the correct way regardless of the `force` issue) but at the moment we don't have the tools to write unit tests for the masp vp (at least to my knowledge)
v0.27.0
=> MASP nullifier uniqueness

.changelog/unreleased/improvements/2295-refactor-apply-inflation.md, apps/src/lib/node/ledger/shell/finalize_block.rs, core/src/ledger/pgf/inflation.rs, core/src/ledger/pgf/mod.rs, proof_of_stake/src/lib.rs
Clean up `finalize_block::apply_inflation` by moving the respective code into pos and pgf modules.
0.28.1
=> Refactor `apply_inflation`

proof_of_stake/src/parameters.rs, proof_of_stake/src/tests/state_machine.rs, proof_of_stake/src/tests/state_machine_v2.rs
v0.27.0
- ~~[ ] I have added a changelog~~ - not relevant, testing only
=> PoS SM fixes

.changelog/v0.29.0/improvements/2289-ethbridge-move-from-apps.md, Cargo.lock, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, ethereum_bridge/Cargo.toml, ethereum_bridge/src/protocol/mod.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs, ethereum_bridge/src/protocol/validation.rs, ethereum_bridge/src/protocol/validation/bridge_pool_roots.rs, ethereum_bridge/src/protocol/validation/ethereum_events.rs, ethereum_bridge/src/protocol/validation/validator_set_update.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Move Ethereum bridge components from `apps` to the `ethereum_bridge` crate. This is part of the modularization effort of Namada.
`v0.29.0`
=> Move Ethereum bridge components from `apps` to their own crate

.changelog/unreleased/SDK/2345-masp-vp-panics.md, .changelog/unreleased/improvements/2345-masp-vp-panics.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/init_chain.rs, benches/native_vps.rs, core/src/ledger/masp_conversions.rs, core/src/ledger/masp_utils.rs, core/src/types/token.rs, sdk/src/masp.rs, shared/src/ledger/native_vp/masp.rs
Removes panics from the native masp vp. Introduces helper functions to construct masp keys.
v0.29.0
=> MASP vp panics

.changelog/unreleased/bug-fixes/1910-fix-tok-bal-query-errs.md, apps/src/lib/client/rpc.rs
Closes #1910
Supersedes #2089, by rebasing it on `v0.29.0` and squashing irrelevant history.
`v0.29.0`
=> Fix querying error while checking token balance

.changelog/unreleased/improvements/2368-lookup-validator-consensus-key.md, apps/src/lib/cli.rs, apps/src/lib/client/rpc.rs, proof_of_stake/src/storage.rs, sdk/src/args.rs, sdk/src/queries/vp/pos.rs, sdk/src/rpc.rs
closes #2367
CLI example:
```shell
> namadac find-validator --validator validator-0
Consensus key: tpknam1qqq8nts0j99jylpx74ks48hsasvclu2syhfh0gfy2853dr8v4ehq654ck6n
Tendermint key: 3AD4F16E9BE4364D4B5660772939E7587A79E9CE
Consensus key hash: 3EA0322AB6800890B79B8494E40E8427EC6D7065
```
v0.29.0
=> look-up validator by native address and query consensus key

.changelog/unreleased/SDK/2372-light-sdk-deps.md, Cargo.lock, Makefile, light_sdk/Cargo.toml
Removes the unused `ibc` dependency of the light sdk. Also adds the light sdk crate to the Makefile.
v0.29.0
=> Light sdk dependencies cleanup

.changelog/unreleased/improvements/2374-fix-bond-amount.md, proof_of_stake/src/lib.rs
The `bond_amount` that is used primarily to compute a delegator's votes in governance is fixed to properly account for slashed redelegated tokens.
v0.29.0
=> Fix bond amount for addresses

.changelog/unreleased/improvements/2375-masp-vp-expiration.md, shared/src/ledger/native_vp/masp.rs
Adds tx expiration check in the masp validity predicate.
v0.29.0
=> MASP vp expiration

.changelog/unreleased/SDK/2376-remove-masp-key.md, .changelog/unreleased/improvements/2376-remove-masp-key.md, core/src/types/address.rs, sdk/src/signing.rs
Removes the hardcoded masp key from the codebase. Updates `tx_signers` to return an empty vector of keys if the source of the tx is MASP since there's no need to sign the tx in that case.
v0.29.0
=> Removes the hardcoded masp sentinel key

.changelog/unreleased/bug-fixes/2384-wasmer-alignment-fixes.md, .changelog/unreleased/bug-fixes/2385-wasm-vm-addr-sanitize.md, Cargo.lock, shared/Cargo.toml, shared/src/vm/wasm/memory.rs, shared/src/vm/wasm/run.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
=> Sanitize wasm vm addresses

.changelog/unreleased/improvements/2382-fee-refactor.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs
Refactors `wrapper_fee_check` into three different functions, one for each consensus state (`CheckTx`, `PrepareProposal` and `ProcessProposal`). Extract the fee unshield processing to a separate function. Also changes some methods of `Shell` to just be functions since we don't really need a reference to the shell.
v0.29.0
=> Fee validation refactor

.changelog/unreleased/improvements/2383-comet-timestamp.md, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/testing/node.rs
Removes `get_block_timestamp` method. In `process_proposal` always require CometBFT to attach a valid timestamp to the block.
v0.29.0
=> Mandatory CometBFT timestamp

.changelog/unreleased/improvements/2395-gas-sentinel-fix.md, shared/src/vm/host_env.rs
Small update to set the gas sentinel for ibc transactions to allow them to be rewrapped and resubmitted.
v0.30.0
=> Sets gas sentinel in `ibc_tx_charge_gas`

crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/shell/queries.rs, crates/state/src/wl_storage.rs
On a live chain, we typically receive `InitChain` request with `initial_height = 1`, but the apps `TestShell` was using 0.
#2312 
diff for review: https://github.com/anoma/namada/pull/2380/files/72c1fff90bf35dfc5e2f54fa7fcd5dfa708a4a86..99ac08e70c883020f30bc2b67a7c9f52917bd297
- ~~[ ] I have added a changelog~~ - test changes only
=> fix fst epoch start height in apps tests

.changelog/unreleased/bug-fixes/2408-fix-burn-function.md, Cargo.lock, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/ibc/src/actions.rs, crates/trans_token/Cargo.toml, crates/trans_token/src/storage.rs
Closes #2364. Fix the burn function.
v0.30.1
=> Fix `token::burn`

.changelog/unreleased/bug-fixes/2415-governance-tally.md, crates/apps/src/lib/node/ledger/ethereum_oracle/mod.rs, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/governance/src/storage/mod.rs, crates/governance/src/utils.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs, crates/tests/src/e2e/ledger_tests.rs
=> Fix governance tally

.changelog/unreleased/features/2417-wallet-zip32-0.30.1.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/wallet.rs, crates/apps/src/lib/client/tx.rs, crates/apps/src/lib/wallet/mod.rs, crates/sdk/src/args.rs, crates/sdk/src/wallet/derivation_path.rs, crates/sdk/src/wallet/mod.rs, crates/sdk/src/wallet/store.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs, crates/tests/src/e2e/wallet_tests.rs, crates/tests/src/strings.rs
The PR features the following changes:
- implements ZIP32 functionality for MASP (shielded) keys
- introduces m/32'/877'/0' as a default derivation path for shielded keys
- introduces BIP44 / ZIP32 compliance checks for user derivation paths
- introduces a command line option to allow non-compliant derivation paths
Additionally, the PR undoes some erroneous changes in wallet introduced in 0.28.0 rc1
The PR is based on v0.30.1
=> Integrate ZIP32 functionality for MASP keys

.changelog/unreleased/bug-fixes/2428-fix-shielded-actions.md, crates/namada/src/ledger/native_vp/masp.rs, crates/sdk/src/tx.rs
Adds a check on the changes to the masp balance key in the masp vp to match the amount stated in the `Transfer` object (required for incoming ibc packets)
v0.30.1
=> Validate balance in masp vp

.changelog/unreleased/improvements/2435-opt-jemalloc.md, Makefile, crates/apps/Cargo.toml, crates/apps/src/lib/mod.rs, crates/apps/src/lib/node/ledger/mod.rs, crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs, crates/apps/src/lib/node/ledger/storage/rocksdb.rs
RocksDB tikv-jemalloc-sys takes a long time to build in rust-analyzer. This change disable RocksDB jemalloc feature by default and only uses it for make build-release
0.30.1
=> enable rocksdb jemalloc only for make build-release

.changelog/unreleased/improvements/2438-new-storage-write.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/init_chain.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/storage/mod.rs, crates/apps/src/lib/node/ledger/storage/rocksdb.rs, crates/benches/host_env.rs, crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, crates/ethereum_bridge/src/protocol/transactions/read.rs, crates/ethereum_bridge/src/protocol/transactions/update.rs, crates/ethereum_bridge/src/protocol/transactions/votes/storage.rs, crates/ethereum_bridge/src/storage/parameters.rs, crates/ethereum_bridge/src/storage/vp/ethereum_bridge.rs, crates/ibc/src/storage.rs, crates/namada/src/ledger/ibc/mod.rs, crates/namada/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs, crates/namada/src/ledger/native_vp/ethereum_bridge/vp.rs, crates/parameters/src/lib.rs, crates/sdk/src/queries/shell/eth_bridge.rs, crates/state/src/lib.rs, crates/state/src/write_log.rs, crates/storage/src/db.rs, crates/storage/src/lib.rs, crates/storage/src/mockdb.rs, wasm/wasm_source/src/tx_bridge_pool.rs
An alternate implementation of #2355.
With the new changes, if a key is not merklized, then it also may not be persisted in the diffs. There is no longer an either/or option.
v0.30.1
=> New Storage Write API REDO

.changelog/unreleased/features/2417-wallet-zip32-0.30.1.md, .changelog/unreleased/improvements/2442-bip39-optional-0.30.1.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/wallet.rs, crates/apps/src/lib/client/tx.rs, crates/apps/src/lib/wallet/mod.rs, crates/sdk/src/args.rs, crates/sdk/src/wallet/derivation_path.rs, crates/sdk/src/wallet/mod.rs, crates/sdk/src/wallet/store.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs, crates/tests/src/e2e/wallet_tests.rs, crates/tests/src/strings.rs
- Added a CLI option for BIP39 passphrase prompt.
Based on #2417 - diff https://github.com/anoma/namada/pull/2442/files/b6bc0e976d50a5df55e56165068c41ffaa49e07a..92e2b0dd58e6ff941971eab967a5c319552597a4
=> Make BIP39 passphrase optional

.changelog/unreleased/bug-fixes/2443-fix-multitoken-vp.md, crates/namada/src/ledger/native_vp/multitoken.rs
The diff had only `I256` type, however, it could be an overflow because `post` and `pre` is `Amount` (`U256`).
v0.30.1
=> Fix Multitoken VP to avoid overflow

.changelog/unreleased/SDK/2452-masp-vp-refactor.md, .changelog/unreleased/improvements/2452-masp-vp-refactor.md, crates/apps/src/lib/bench_utils.rs, crates/benches/native_vps.rs, crates/benches/txs.rs, crates/namada/src/ledger/native_vp/masp.rs, crates/sdk/src/masp.rs, crates/trans_token/src/storage_key.rs, crates/vp_env/src/lib.rs
This PR modifies the masp VP to validate the changed keys in storage instead of validating the `Transfer` object. It also updates the client to retrieve the data from the changed keys instead of the tx data since this doesn't get validated from the vp. Unfortunately it wasn't possible to completely remove the dependency on `Transfer` since we still need it for one thing, retrieve the masp `Transaction` object whose commitment is included in the tx data. Because of this, the masp VP only allows for a single value transfer when a transparent address is involved (whereas the other VPs technically support multiple transfers).
In addition, this PR also makes the operations in the masp VP checked. It has to be noted that operations on `I128Sum` underneath use check operations even though, in …
=> MASP VP refactor

Cargo.lock, Cargo.toml, crates/apps/Cargo.toml, crates/apps/src/lib/mod.rs, crates/apps/src/lib/node/ledger/mod.rs, crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs, crates/apps/src/lib/node/ledger/storage/rocksdb.rs, crates/core/src/types/token.rs, crates/sdk/src/masp.rs
This is needed for `cargo-release` used by `scripts/release.sh` that compiles with all features enabled.
Using a fork from https://github.com/heliaxdev/rust-rocksdb/pull/1 (upstream in https://github.com/rust-rocksdb/rust-rocksdb/pull/857).
#2456 - diff https://github.com/anoma/namada/pull/2457/commits/f4c030a3039ce21c4a09862ff0248ae9fd57a39b
=> fix all features build (forked rocksdb jemalloc on non-windows only)

.changelog/unreleased/bug-fixes/2459-fix-governance-underflow.md, crates/apps/src/lib/client/rpc.rs, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/governance/src/lib.rs, crates/governance/src/storage/keys.rs, crates/governance/src/storage/proposal.rs, crates/governance/src/storage/vote.rs, crates/namada/src/ledger/governance/mod.rs, crates/namada/src/vm/host_env.rs, crates/sdk/src/rpc.rs
A bug was found by  @zenodeapp during a public testnet regarding an underflow in governance VP. This PR aims to fix it.
- Avoid logging and underflow bug
- Use validator stake instead of total validator when computing vote tally
- `PGFAction` for both pgf steward and pgf funding proposal must have unique targets
- When executing PGF proposals, collect the `PGFAction` into a sorted collection to avoid inconsistent states due to ordering
- Enforce a voter to submit all the complete list of validator for which he has a delegation
=> Fix several issue with governance and pgf

.changelog/unreleased/bug-fixes/2471-genesis-native-token.md, crates/apps/src/lib/config/genesis/templates.rs, crates/core/src/types/token.rs, genesis/starter/balances.toml
A commit was accidentally removed from https://github.com/anoma/namada/pull/2467 to validate native token balance based on its configured name. The validation before the changes would still pass with a rename, but the check would be skipped as it wouldn't match the hard-coded value.
0.30.3
=> genesis: use the configured native token name for validation

.changelog/unreleased/bug-fixes/2473-wallet-fix-empty-password-panic.md, crates/apps/src/lib/cli/wallet.rs, crates/sdk/src/wallet/keys.rs
- This PR fixes panic in the case when user provided decryption password is empty.
- Further improvement: output of `list` and `find` commands has been unified for transparent / shielded settings.
Based on 0.30.2
=> Fix empty password panic; unify `list` and `find` commands output

.changelog/unreleased/bug-fixes/2478-fix-hostenv-panic.md, crates/core/src/types/token.rs, crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, crates/ethereum_bridge/src/protocol/transactions/update.rs, crates/namada/src/ledger/native_vp/ibc/context.rs, crates/namada/src/vm/host_env.rs, crates/sdk/src/eth_bridge/bridge_pool.rs, crates/tests/src/native_vp/pos.rs, crates/tx_prelude/src/token.rs
- Replace `unreachable!` with `Error`
- Fix `amount.spend`/`recieve` to return `Result`
`v0.30.3`
=> Fix to avoid panic in host env functions

.changelog/unreleased/bug-fixes/2489-bip39-optional-derive.md, crates/apps/src/lib/cli/wallet.rs, crates/sdk/src/wallet/mod.rs, crates/sdk/src/wallet/store.rs
- Fix: respect the optional bip39-flag for key derivation.
- Improvement: print the alias if the derived key already exists.
Based on v0.30.2
=> Fix handling of the optional BIP39 passphrase flag

.changelog/unreleased/improvements/2490-wallet-display-gen-payment-addr.md, crates/apps/src/lib/cli/wallet.rs
Improvement: print the generated payment address.
Based on v0.31.0
=> Print generated payment address

.changelog/unreleased/improvements/2502-wait-for-genesis-logs.md, Makefile, crates/apps/src/lib/node/ledger/broadcaster.rs, crates/apps/src/lib/node/ledger/mod.rs, crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs
Resolves #2495
It now fully initializes the node and outputs logs before sleeping until genesis start time. Previously it would not start any processes until genesis times, giving no feedback to users until genesis time was reached.
=> Reworks the way the ledger waits for genesis start.

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: allow to pass in the binaries name

.changelog/unreleased/bug-fixes/2547-order-txs.md, crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs
In a previous set of changes, the method that enqueued ABCI calls did so asynchronously. These calls must be handled in the order received, so this is a bug. This PR makes sure that the enqueing is done synchronously.
=>  Ensure ABCI commands are handled synchronously

.changelog/unreleased/improvements/2558-fix-query-protocol-parameters.md, crates/apps/src/lib/client/rpc.rs
Several PoS params were missing from this query, and the general output is reformatted to look nicer as well.
v0.31.2
=> Fix query of protocol params

.changelog/unreleased/bug-fixes/2579-governance-fix.md, crates/governance/src/utils.rs
Governance tallying didn't used to work for delegators. Now it does.
0.31.2
=> Governance: fix tally computation

.changelog/unreleased/bug-fixes/2653-fix-validator-set-update-with-ck.md, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/proof_of_stake/src/lib.rs, crates/proof_of_stake/src/tests/helpers.rs, crates/proof_of_stake/src/tests/test_validator.rs, crates/proof_of_stake/src/types/mod.rs, crates/proof_of_stake/src/validator_set_update.rs
A consensus failure occurred on the SE that appears to be due to a bug in the communication of validator set updates to CometBFT for the change to epoch 9.
To summarize, there is a validator in the below-capacity set in epoch 8, to become a consensus validator in epoch 9, and whose consensus key was changed and to become active in epoch 9. In addition to a ConsensusValidator update, we also sent a DeactivateValidator update with the old consensus key, though this should not have been done since the validator was not previously a Consensus validator.
A test case that reproduces the error is added, followed by a fix. Then a more thorough refactor of `validator_set_update_tendermint` is done. Another refactor of the types used to hold voting power is done at the end.
v0.31.4
=> Fix CometBFT validator set update

.changelog/unreleased/improvements/2611-show-help-for-query-proposal-votes.md, crates/apps/src/lib/cli.rs
Show help message for query-proposal-votes subcommand instead of crashing when no arg provided.
```
$ ./namadac query-proposal-votes
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: crates/apps/src/lib/cli/utils.rs:204
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
```
$ ./namadac query-proposal-votes
Query votes for the proposal.
Usage: namadac query-proposal-votes [OPTIONS]
Options:
--node <node>                Address of a ledger node as "{scheme}://{host}:{port}". If the scheme is not supplied, it is assumed to be TCP.
--proposal-id <proposal-id>  The proposal identifier.
--voter <voter>              The address of the proposal voter.
-h, …
```
=> Show help for query-proposal-votes when no arg provided

.changelog/unreleased/bug-fixes/2625-fix-shielded-balance-query.md, crates/apps/src/lib/client/rpc.rs, crates/sdk/src/masp.rs, crates/sdk/src/tx.rs
The shielded balance query sometimes doesn't know the received IBC tokens.
By modifing `precompute_asset_types` to get all tokens received over IBC, the query can get the balances of these tokens.
=> Fix the balance query for IBC tokens

.changelog/unreleased/bug-fixes/2657-commit-failure.md, crates/apps/src/lib/node/ledger/shell/mod.rs
Rather than allowing CometBFT to keep processing blocks after a storage write has failed in Namada, we crash the ledger to avoid any potential corruption of state.
This PR is eligible for non-breaking draft.
`v0.31.4`
=> Crash the ledger if committing a block fails

.changelog/unreleased/improvements/2658-allow-http-url-cli.md, Cargo.lock, crates/apps/Cargo.toml, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/api.rs, crates/apps/src/lib/cli/context.rs, crates/apps/src/lib/config/genesis/transactions.rs, crates/apps/src/lib/node/ledger/shell/testing/client.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/tests/src/e2e/helpers.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/masp.rs
Allow a user to input http/https protocol when supplying `--node` or `--ledger-address`
=> Allow use of other protocol in CLI

.changelog/unreleased/improvements/2668-time-out.md, crates/apps/src/lib/node/ledger/broadcaster.rs
Closes #2662
This change increase the timeout of the broadcaster from 30 to 180 seconds. In the last upgrade of the Shielded Expedition some validators couldn't restart their node because of the timeout. Increasing this value solved it and avoid restarting from scratch.
=> fix: increase timeout from 30 to 180

.changelog/unreleased/bug-fixes/2679-fix-proposal-loading.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/mod.rs
=> Proposals execution order must be deterministic

.changelog/unreleased/features/2516-consensus-key-to-tm-key.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/wallet.rs, crates/apps/src/lib/node/ledger/tendermint_node.rs, crates/sdk/src/args.rs
I made a new cli command for namadw  caused by #2515 
```
Usage: namadaw [OPTIONS] <COMMAND>
Commands:
gen               Generates a new transparent / shielded secret key.
derive            Derive transparent / shielded key from the mnemonic code or a seed stored on the hardware wallet device.
gen-payment-addr  Generates a payment address from the given spending key.
list              List known keys and addresses in the wallet.
find              Find known keys and addresses in the wallet.
export            Exports a transparent keypair / shielded spending key to a file.
convert           Convert to tendermint priv_validator_key.json with your consensus key alias
import            Imports a transparent keypair / shielded spending key from a file.
add               Adds the given key or …
```
=> Feature : add a new cli 'wallet convert' command for coverting tendermnint key json file

.changelog/unreleased/improvements/2545-cli-flexible-global-args-pos.md, crates/apps/src/lib/cli.rs
=> cli: allow to use global args at any position (before or after subcmd)

Cargo.lock, crates/governance/Cargo.toml, crates/governance/src/cli/onchain.rs, crates/governance/src/pgf/storage/mod.rs, crates/governance/src/storage/proposal.rs, crates/namada/src/ledger/governance/mod.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Better formatting of proposals.
This includes the additional data required to fully review a proposal when using `namada client query-proposal`:
- Default (optional hash of WASM code)
- PGF Steward (add/remove addresses)
- PGF Payment (actions)
Fixes #2570.
Based on my "typos" PR #2569 for easier merging.
Right now it uses debug formatting for some of the types.  Let me know if this is the right approach and I can implement formatting for the remaining types too.
=> Show additional proposal data in namada client query-proposal

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/triggerable_sync.yml, docker/namada-wasm/Dockerfile, docker/namada/Dockerfile
=> ci+docker: update toolchain versions to 1.76

.changelog/unreleased/improvements/2588-test-vectors-0.30.2-rev-1.md, Cargo.lock, crates/governance/src/storage/proposal.rs, crates/sdk/src/lib.rs, crates/sdk/src/masp.rs, crates/sdk/src/signing.rs, crates/tx/src/data/pos.rs, examples/Cargo.toml, examples/generate_txs.rs
Various changes in order to increase the detail presented in test vectors, increase the variety of test vectors, and ease the implementation of hardware wallet apps. Specifically the changes are as follows:
* Test vector generator now sometimes generates signed transactions
* Greatly increased the level of detail presented in Init Proposal transactions
* Increased the coverage PGF steward transactions to include the IBC variants
* Started including memos in generated transactions sometimes, both in hashed and full form
* Now print out the section hashes in debug vectors to facilitate constructing signing test vectors
* Improved the formatting of Update Steward Commission transactions for the hardware wallet
Namada v0.30.2
=> Murisi/test vectors 0.30.2 rev 1

.changelog/unreleased/bug-fixes/2634-fix-ibc-shielded-transfer-back.md, crates/ibc/src/lib.rs, crates/tests/src/e2e/ibc_tests.rs
When trying to transfer a token back to the source Namada, the token address was always `IbcToken` in `ibc-gen-shielded`. If the destination Namada is the origin of the token, the address should be an established address.
And, added a test to transfer back over IBC shielded transfer.
`v0.31.4`
=> Fix the token address when shielded transfer back to Namada

.changelog/unreleased/bug-fixes/2701-fix-default-node.md, crates/apps/src/lib/cli/context.rs, crates/tests/src/e2e/ledger_tests.rs
Closes #2702
This fixes a bug introduced in #2658 which causes all cli requests to fail when no `--node` param is provided:
```
builder error for url (tcp://127.0.0.1:26657): URL scheme is not allowed
```
0.31.6
=> Fix default node param protocol for cli calls

.changelog/unreleased/SDK/2762-pub-masp-types.md, crates/sdk/src/masp.rs
this got accidentally hidden in 0.31.7 with flattening of core types
0.31.7
=> sdk: re-pub masp types from core

.changelog/unreleased/improvements/2724-git2-deps.md, Cargo.lock, Cargo.toml
We are using `git2` dependency only to fetch git data and create `version.rs`. The build script of `git2` with default feature is very heavy, taking 90s to build and we don't need any of the default features.
=> disable default features for git2

.changelog/unreleased/improvements/2748-more-client-improvements.md, crates/sdk/src/error.rs, crates/sdk/src/queries/vp/pos.rs, crates/sdk/src/tx.rs
Various client improvements.
- #2723
- #2636
- #2736
v0.31.8
=> Various client improvements 2

.changelog/unreleased/bug-fixes/2774-fix-ibc-pgf-timestamp.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/ibc/src/actions.rs
- Non-deterministic issue happened because the timeout timestamp was set with `DateTimeUtc::now()` in PGF over IBC
- Taking IBC events after PGF inflation executing IBC transfers
v0.31.8
=> Fix timeout timestamp for PGF over IBC

.changelog/unreleased/SDK/2775-fix-shielded-context-dry-run.md, .changelog/unreleased/bug-fixes/2775-fix-shielded-context-dry-run.md, crates/apps/src/lib/bench_utils.rs, crates/sdk/src/masp.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs
Closes #2750.
Fixed a bug for which the speculative shielded context was updated even when dry running a transaction.
v0.31.8
=> Update speculative shielded context only when required

docker/namada/Dockerfile
The updated Dockerfile in #2687 implicitly uses Debian Bookworm instead of Bullseye, which causes the following issues:     
1. it doesn't have clang-tools-11
2. it is inconsistence with the base image used by namada-wasm Dockerfile which explicitly uses bullseye image 
Fixes https://github.com/anoma/namada/actions/runs/8192271541/job/22403401963
=> Update Dockerfile base image to use bullseye instead of bookworm

.changelog/unreleased/bug-fixes/2850-clear-ibc-events.md, crates/state/src/write_log.rs
=> Clear ibc events on rejected txs

.changelog/unreleased/improvements/2604-prep-pos-vp.md, crates/namada/src/ledger/pos/vp.rs
=> Prepare PoS VP

.changelog/unreleased/bug-fixes/2617-fix-vp-user.md, crates/proof_of_stake/src/lib.rs, wasm/wasm_source/src/vp_user.rs
Fix the unjailing bug observed in the SE, when unjailing that involves demoting another consensus validator the the below-capacity set is involved.
Closes #2663.
v0.31.9
=> Fix vp_user

Makefile, scripts/repeat-e2e-test.sh
Many of the `make test-*` take a long time to rebuild and use a lot of mem for building `--bins` and `--examples`. Explicitly using `--lib` target avoids that (see https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection)
0.32.1
- ~~[ ] I have added a changelog~~ - makefile only
=> make: use `--lib` for cargo tests to avoid building bins and examples

.changelog/unreleased/sdk/3037-sdk-change-consensus-keys.md, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/client/tx.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/tx.rs
- Now `change_consensus_key` is part of the sdk
=> sdk: refactor `change_consensus_key`

.changelog/unreleased/improvements/2574-imrpove-slash-queue.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/proof_of_stake/src/slashing.rs, crates/proof_of_stake/src/tests/state_machine.rs, crates/proof_of_stake/src/tests/state_machine_v2.rs, crates/proof_of_stake/src/tests/test_slash_and_redel.rs, crates/proof_of_stake/src/types/mod.rs
Make the enqueued slashes in the PoS state machine test compatible with #2574
#2574
- diff https://github.com/anoma/namada/pull/3072/commits/e77da8a934760de081f8139de8191b9973dad182
- ~~[ ] I have added a changelog~~ - testing only
=> Fix enqueued slashes in SM test

.changelog/unreleased/bug-fixes/2735-fix-vps-api.md, crates/namada/src/ledger/vp_host_fns.rs, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/wasm/run.rs, crates/state/src/lib.rs, crates/state/src/write_log.rs
Closes #2683.
Fixes the `has_key` method provided to the vp env to not return an error on temporary write values (the `read` method was already fine).
Adds a new `read_persistent` method on `WriteLog` that ignore temporary writes and modifies the `read` and `has_key` implementation of `impl_storage_read` to call this new method.
Modifies `tx_iter_next` to skip temporary writes.
Refactors `fetch_or_compile` to call `state.read` (which should include possible updated in the write log of the wasm codes).
Updates `write_temp` in `WriteLog` to return an error when trying to overwrite a `StorageModification::Write` with a `StorageModification::Temp`.
Updates `iter_prefix_post` in `WriteLog` to iterate also on the precommit bucket.
Updates `write`, `write_temp` and `delete` in `WriteLog` to take …
=> Fix temporary values read

.changelog/unreleased/improvements/2845-limit-metadata-size.md, crates/apps/src/lib/config/genesis/transactions.rs, crates/proof_of_stake/src/parameters.rs, crates/sdk/src/error.rs, crates/sdk/src/tx.rs, wasm/wasm_source/src/vp_user.rs
=> Limit metadata size

.changelog/unreleased/features/2842-nam-transferable.md, crates/apps/src/lib/config/genesis/chain.rs, crates/apps/src/lib/config/genesis/templates.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/storage/mod.rs, crates/core/src/parameters.rs, crates/namada/Cargo.toml, crates/namada/src/ledger/native_vp/multitoken.rs, crates/parameters/Cargo.toml, crates/parameters/src/lib.rs, crates/parameters/src/storage.rs, crates/shielded_token/Cargo.toml, crates/shielded_token/src/conversion.rs, crates/state/src/lib.rs, crates/tests/src/vm_host_env/ibc.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
=> Add a param to enable/disable nam transfers

.changelog/unreleased/bug-fixes/2848-ibc-tx-simplify.md, crates/ibc/src/actions.rs, crates/ibc/src/lib.rs, crates/namada/src/vm/host_env.rs
=> IBC tx - simplify storage iter prefix

.changelog/unreleased/improvements/2852-vps-use-storage-err.md, crates/ethereum_bridge/src/storage/parameters.rs, crates/namada/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs, crates/namada/src/ledger/native_vp/ethereum_bridge/nut.rs, crates/namada/src/ledger/native_vp/ethereum_bridge/vp.rs, crates/namada/src/ledger/native_vp/mod.rs, crates/storage/src/error.rs
Replace `eyre!()` errors with `namada_storage` errors. This change will be useful in a future PR, to allow easily downcasting to the error contained in a boxed `namada_storage` result.
`v0.32.0`
=> Always use storage errors on native VPs

.changelog/unreleased/bug-fixes/2928-fst-addr-vps.md, crates/apps/src/lib/bench_utils.rs, crates/benches/native_vps.rs, crates/benches/vps.rs, crates/core/src/storage.rs, crates/state/src/write_log.rs, crates/tx_prelude/src/proof_of_stake.rs, crates/tx_prelude/src/token.rs, wasm/wasm_source/src/tx_init_proposal.rs, wasm/wasm_source/src/tx_resign_steward.rs, wasm/wasm_source/src/tx_update_account.rs, wasm/wasm_source/src/tx_update_steward_commission.rs, wasm/wasm_source/src/tx_vote_proposal.rs
first step toward #2629 - the next step is to update VPs to enforce that `insert_verifier` has been called with an address that has to authorize the tx (#2934).
0.32.0
=> only trigger VPs from a fst addr of a key segment

.changelog/unreleased/improvements/2932-fix-ledger-significant-digits.md, crates/sdk/src/signing.rs
Modified the printing of numbers in Ledger test vectors so that the `.0` suffix is not added to whole numbers. So now all unnecessary zeros and decimals at the end of decimal numbers are removed before printing.
Namada v0.32.0
=> Remove the superfluous addition of .0 to Ledger test vectors.

.changelog/unreleased/bug-fixes/2964-fix-non-persisted-diffs.md, crates/apps/src/lib/node/ledger/storage/mod.rs, crates/apps/src/lib/node/ledger/storage/rocksdb.rs, crates/core/src/storage.rs, crates/state/src/wl_state.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs
=> fix non-persisted diffs

.changelog/unreleased/improvements/3002-remove-from-total-supply.md, crates/governance/src/pgf/inflation.rs, crates/proof_of_stake/src/rewards.rs, crates/proof_of_stake/src/tests/test_pos.rs, crates/sdk/src/queries/vp/token.rs, crates/shielded_token/src/conversion.rs, crates/trans_token/src/storage.rs
=> Remove PGF balance from total native supply

crates/tests/src/e2e/ledger_tests.rs
The test often fails with `InsufficientVotes` on the first node as the second validator is bonded with the same stake and when it's not signing by the time it enters the consensus set we don't get enough votes to continue.
To fix this I moved the calls to restart the new validator's node right after its `init-validator` tx.
v0.32.1
- ~~[ ] I have added a changelog~~ - tests only
=> test/e2e/init_validator: restart new validator node right after its tx

.changelog/unreleased/bug-fixes/2621-fix-nullifier-check.md, crates/namada/src/ledger/native_vp/masp.rs
Closes #2594.
Call `valid_nullifiers_reveal` regardless of the transaction source to make sure that a shielding tx doesn't reveal any nullifier. Enforces that at least one shielded input is present if the source of the tx is the MASP.
Refactors the checks on the bundles and fixes the check on the shielded outputs when the target is MASP which was previously wrong (was not taking into account the case in which `shielded_outputs` was `None`.
v0.33.0
=> Fix nullifiers check

.changelog/unreleased/improvements/2861-shim-audit.md, crates/apps/src/lib/node/ledger/shims/abcipp_shim.rs, crates/apps/src/lib/node/ledger/shims/abcipp_shim_types.rs
After auditing the abci++ shims, found some small cleanups.
v0.33.0
=> Cleanup from auditing abci shims

.changelog/unreleased/improvements/2956-refactor-reprot.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs, crates/apps/src/lib/node/ledger/shell/process_proposal.rs, crates/apps/src/lib/node/ledger/storage/rocksdb.rs, crates/namada/src/ledger/protocol/mod.rs, crates/replay_protection/src/lib.rs, crates/state/src/wl_state.rs, crates/state/src/write_log.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs
Closes #2922.
Since there's no more need to keep track and possibly act on tx cases from different block, this PR removes the `ReProtStorageModification` enum and uses a simple `HashSet` to keep track of the transaction hashes.
Also improves replay protection unit tests.
v0.33.0
=> Replay protection refactor

.changelog/unreleased/improvements/3087-fix-governance-proposal-execution.md, crates/apps/src/lib/client/rpc.rs, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/governance/src/storage/proposal.rs, crates/namada/src/ledger/governance/mod.rs
- Closes #3081 
- Closes #3082 
- Closes #2884
=> fix governance proposal execution

.changelog/unreleased/improvements/2981-default-gas-limit.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/config/genesis/transactions.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs, crates/sdk/src/lib.rs, crates/tx/src/data/mod.rs, crates/tx/src/data/wrapper.rs
Closes #2981.
Defines a common default value for `GasLimit` shared between the sdk and the client.
Removes the `Default` derive from `GasLimit`.
v0.33.0
=> Common default gas limit

.changelog/unreleased/improvements/3110-write-log-t-safety.md, crates/namada/src/ledger/native_vp/ibc/context.rs, crates/namada/src/ledger/vp_host_fns.rs, crates/namada/src/vm/host_env.rs, crates/state/src/lib.rs, crates/state/src/wl_state.rs, crates/state/src/write_log.rs
=> state/write_log: refactor temp key-vals for better type-safety

.changelog/unreleased/miscellaneous/3121-remove-show-transfer.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/client/rpc.rs
=> remove `show-transfer`

.changelog/unreleased/improvements/3122-test-vectors-0.33.0.md, crates/governance/src/storage/proposal.rs, crates/sdk/src/signing.rs
Made the adjustments to facilitate the hardware wallet's printing of transactions. More specifically, the ordering used to print the `commission` field of an update steward commission transaction has been changed to reflect its serialization order. Also removed some dead code pertaining to printing out proposal types.
Namada v0.33.0
=> Adjusted test vector printing to simplify hardware wallet implementations

.changelog/unreleased/improvements/2620-clean-gas-limit.md, crates/tx/src/data/wrapper.rs
Closes #2620.
Refactors `GasLimit` and removes unused methods and constants.
v0.33.0
=> `GasLimit` cleanup

.changelog/unreleased/improvements/2794-merkle-masp-hashes.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/shielded_token/src/storage_key.rs
Closes #2794.
Adds the masp commitment tree anchor keys to the merkle tree so that they can be tracked in the app hash.
v0.33.0
=> Merklize commitment tree anchor keys

.changelog/unreleased/bug-fixes/3130-gen-in-current-era.md, crates/sdk/src/lib.rs
Restricted the date-time generator to only generate valid RFC 3339 dates. This means that the date-time generator now only generates date-times in the current era, which ranges from 0000AD to 9999AD. This change is necessary to ensure that `DateTimeUtc`s, and hence `Tx`s (whose `Tx::header` contains the fields `Header::expiration` and `Header::timestamp`) deserialize correctly.
Namada v0.33.0
=> Keep generated dates in the current era so that parsing RFC 3339 works.

.changelog/unreleased/miscellaneous/3137-tower-abci-upstream.md, Cargo.lock, Cargo.toml
I can no longer reproduce the issue that we fixed in #2152 with the query error handling. When the service is overloaded, CometBFT simply reports e.g. `failed to write responses module=rpc-server err="write tcp 127.0.0.1:27657->127.0.0.1:36888: i/o timeout` and both Namada and Comet continue to run without any issues.
v0.33.0
=> deps: switch back to upstream tower-abci v0.11.1

scripts/gen_localnet.py
Rounds the epoch length to the closest integer to prevent writing a float value to the config file.
v0.33.0
=> No float `epoch_length` in localnet script

.changelog/unreleased/testing/2232-ibc-namada-gaia-e2e.md, .github/workflows/scripts/e2e.json, crates/tests/src/e2e/helpers.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/setup.rs
closes #2232 
- ~~Need upgraded Hermes~~
`v0.34.0`
=> Add IBC E2E test with Gaia

.changelog/unreleased/improvements/2832-cli-fallible-conversions.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/cli/relayer.rs, crates/apps/src/lib/cli/wallet.rs
This PR closes #1815. I've refactored the `CliToSdk` trait to propagate errors (such as I/O) from _fallible_ conversions between SDK and CLI types, this way we can avoid panics.
Based on `v0.31.8`
=> cli: Propagating errors from fallible `CliToSdk` conversions

.changelog/unreleased/improvements/3029-token-balance-update-fns.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/init_chain.rs, crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, crates/ethereum_bridge/src/protocol/transactions/read.rs, crates/ethereum_bridge/src/protocol/transactions/update.rs, crates/trans_token/src/storage.rs
- Closes #3003
- Closes #2287
v0.34.0
=> Functions to update token balance and supply

.changelog/unreleased/bug-fixes/3119-check-wasm-digests-after-download.md, crates/apps/src/lib/wasm_loader/mod.rs
Verify the checksum of dowloaded wasm artifacts, before completing the ledger's bootup procedure.
`v0.34.0`
=> Verify the checksum of downloaded wasm files

.changelog/unreleased/improvements/3154-minor-cli-fixe4s.md, crates/governance/src/pgf/cli/steward.rs, crates/sdk/src/error.rs, crates/sdk/src/tx.rs
Closes #2671 and supersedes #2747
Closes #2807
=> More client side checks

.changelog/unreleased/bug-fixes/3065-abci-query-height.md, crates/apps/src/lib/node/ledger/shell/queries.rs, crates/namada/src/ledger/mod.rs, crates/sdk/src/queries/mod.rs, crates/sdk/src/queries/router.rs, crates/sdk/src/queries/shell.rs, crates/sdk/src/queries/shell/eth_bridge.rs, crates/sdk/src/queries/types.rs
=> Set height for abci_query

crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/shell/process_proposal.rs
=> Fix unused import build warnings

about.toml
fixing the last failed release where deps with "Zlib" license got rejected
0.35.0
- ~~[ ] I have added a changelog~~ not relevant
=> add Zlib to the list of accepted deps licenses

.changelog/unreleased/improvements/2975-upgrade-docker-images-to-bookworm.md, docker/namada-wasm/Dockerfile, docker/namada/Dockerfile
Bullseye official security support ends in 4 months (31 Jul 2024)   
Also, the `GLIBC` on bullseye is outdated, see https://github.com/anoma/namada-shielded-expedition/issues/360   
This PR includes:
- Upgrade docker base images to use Debian Bookworm (v12) instead of Bullseye (v11)    
- Upgrade GLIBC v2.31 to GLIBC to v2.36    
There was a failed attempt to upgrade docker images,  #2680 , but later reverted https://github.com/anoma/namada/commit/f38accc33af15d3a82622f197b9fe45fbbec8674 due to inconsistency between dependency versions
=> upgrade docker base images to Debian 12 (Bookworm)

.changelog/unreleased/miscellaneous/3215-warn-on-non-64bit-arch.md, crates/apps/src/lib/node/ledger/mod.rs
=> Emit CLI warning log msg on non 64-bit hardware

.changelog/unreleased/bug-fixes/3220-max-proposal-bytes-validation.md, crates/apps/src/lib/node/ledger/tendermint_node.rs, crates/core/src/chain.rs
Closes #3189
Indeed, Namada ignores the `max_tx_bytes` parameter from CometBFT, which may shrink dynamically based on the presence of evidence of misbehavior data in blocks.
This parameter is only passed as an argument to `PrepareProposal` ABCI calls, and (crucially) never to `ProcessProposal` calls, forcing it to be available under `ProcessProposal` via some other means.
As such, `max_proposal_bytes` (a semantically equivalent Namada-only parameter) was introduced in #843. To ensure the application never exceeds `max_tx_bytes`, CometBFT was configured with a much larger maximum block size (100 MiB, and 90 MiB max for `max_proposal_bytes`).
In #2187, we modified these bounds, setting the max block size to 16 MiB and the max value of `max_proposal_bytes` to 6 MiB. Evidence data is the only …
=> Harden max proposal bytes configuration and deserialization

.changelog/unreleased/improvements/3226-cli-line-wrapping.md, Cargo.lock, crates/apps/Cargo.toml, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/utils.rs
Closes #1796 
Extends claps `Arg` and `Command` types with namada traits. These add configurable line wrapping and hyphenation policies. Also sets help to always be on the next line, but this is easily changeable later.
=> Add line wrapping to the cli commands

.changelog/unreleased/bug-fixes/3228-fix-validator-gas-prices.md, crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs
=> Address block rejections resulting from lower validator gas prices

.changelog/unreleased/improvements/3258-dont-export-wasm-mem.md, crates/namada/src/vm/wasm/host_env.rs, crates/namada/src/vm/wasm/run.rs
The wasm execution environment instantiated a block of memory that went unused by txs/vps. In this PR, we remove the code that instantiated that memory block.
`v0.35.1`
=> Remove unused WASM memory export

.changelog/unreleased/bug-fixes/2817-light-sdk-clone.md, crates/light_sdk/src/transaction/account.rs, crates/light_sdk/src/transaction/bridge.rs, crates/light_sdk/src/transaction/governance.rs, crates/light_sdk/src/transaction/ibc.rs, crates/light_sdk/src/transaction/mod.rs, crates/light_sdk/src/transaction/pgf.rs, crates/light_sdk/src/transaction/pos.rs, crates/light_sdk/src/transaction/transfer.rs
Derives `Clone` and `Debug` for the light sdk structs.
v0.35.1
=> added clone to transaction structs

.changelog/unreleased/improvements/3209-disable-wasm-floats.md, crates/namada/src/vm/mod.rs
=> namada/vm: disable floats in wasm

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/test.yml, .github/workflows/triggerable_sync.yml, docker/namada-wasm/Dockerfile, docker/namada/Dockerfile
In preparation for #3254 updating versions in CI and docker files
0.35.1
- ~~[ ] I have added a changelog~~
=> ci: update rust stable to 1.78 and nightly 2024-05-15

Cargo.lock, Cargo.toml, crates/sdk/src/masp.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
0.36.0
- ~~[ ] I have added a changelog~~ no change, just pointing to a different branch with the same code
=> dep: update to main branch of masp

.changelog/unreleased/bug-fixes/3287-no-default-mainnet.md, crates/apps/Cargo.toml
Undoes accidentally switched on "mainnet' by default in #3259
0.36.0
=> apps: switch off "mainnet" by default

.github/workflows/release.yml
this should fix the release job (see https://github.com/anoma/namada/actions/runs/9179421750/job/25241527344) by updating to later transitive dep `krates` that fixes the cause
=> update cargo-about used for release

.changelog/unreleased/improvements/3284-reprot-merklized-commitment.md, crates/core/src/address.rs, crates/core/src/address/raw.rs, crates/core/src/hash.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/src/shell/finalize_block.rs, crates/replay_protection/src/lib.rs, crates/state/src/wl_state.rs
Replay protection entries need to be verifiable and thus should contribute to the app hash. This PR makes a cryptographic commitment to all replay protection entries (the root of some implicit merkle tree) which is itself merklized.
=> Replay protection contributes to App Hash

.changelog/unreleased/features/3293-merklized-not-diffed.md, crates/merkle_tree/Cargo.toml, crates/merkle_tree/src/lib.rs, crates/node/src/shell/mod.rs, crates/node/src/storage/mod.rs, crates/node/src/storage/rocksdb.rs, crates/state/Cargo.toml, crates/state/src/lib.rs, crates/state/src/wl_state.rs, crates/storage/src/mockdb.rs, crates/storage/src/types.rs
- Update some data in the subspace and the merkle tree, but not update the diffs
- Add `diff_key_filter` to check if the data should be stored to diffs even if `merkle_tree_key_filter` is true
- Add `NoDiff` subtree in Merkle tree
- Need it because we can't rebuild each subtree when some data aren't in diffs
`v0.36.1`
=> Merklized but not diffed

.github/workflows/scripts/e2e.json, .github/workflows/scripts/integration.py
Removes from the GitHub scripts some tests that are no longer part of the codebase.
v0.36.1
=> Removes old tests from workflow scripts

.changelog/unreleased/improvements/2972-masp-parallel-verification.md, Cargo.lock, Cargo.toml, crates/benches/Cargo.toml, crates/benches/native_vps.rs, crates/benches/process_wrapper.rs, crates/gas/src/lib.rs, crates/sdk/src/masp.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Closes #2959.
Parallelize the masp vp verification step.
<s>Currently this doesn't work. The parallel verification process succeeds for every check (even the proofs) except for the signature one and more specifically for the final check on the result point being of small order (https://github.com/ZcashFoundation/reddsa/blob/56d52195608f3830f027f7109176a30175a5c1aa/src/batch.rs#L272)
To get batch signature verfication to work, the following three issues needed fixing:
* In computing the nonce for RedDSA, the concatenation of public key and msg does not need to be handled in the masp crate, this is done automatically by  From<...> impl
* The H* function which hashes data to elliptic curve points has a different personalization ("Zcash_RedjubjubH" vs "MASP__RedjubjubH")
* The batch …
=> Masp vp parallel verification

.changelog/unreleased/improvements/3232-masp-no-transfer-dep.md, crates/core/src/masp.rs, crates/events/src/extend.rs, crates/namada/src/ledger/native_vp/masp.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/src/bench_utils.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/governance.rs, crates/sdk/src/masp.rs, crates/shielded_token/src/utils.rs, crates/state/src/wl_state.rs, crates/tx/src/action.rs, crates/tx/src/data/mod.rs, crates/tx/src/types.rs, crates/vp_env/src/lib.rs, wasm/tx_ibc/src/lib.rs, wasm/tx_transfer/src/lib.rs, wasm/vp_implicit/src/lib.rs, wasm/vp_user/src/lib.rs
Closes #3148.
Partially addresses #2597.
Removes the last dependency on `Transfer` from the masp vp by using a new masp `Action`. Creates a new event for this and updated the sdk to fetch data relying on this event. 
v0.37.0
=> Remove masp vp dependency on `Transfer`

.changelog/unreleased/improvements/3268-track-caller-events.md, crates/events/Cargo.toml, crates/events/src/lib.rs, crates/events/src/tracer.rs
Track the source code origin of some emitted event in Namada.
`v0.36.1`
=> Track caller's emitted events

.changelog/unreleased/bug-fixes/3075-force-fee-payment.md, crates/namada/src/ledger/mod.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/governance.rs, crates/tests/src/integration/ledger_tests.rs, crates/tx/src/data/protocol.rs
Closes #3075.
Restructures `finalize_block` to collect the fees from all the transactions before executing the inner txs, putting this back in line with the validation logic of `process_proposal` and removing an attack vector.
v0.37.0
=> Enforce fee payment

.changelog/unreleased/improvements/3296-test-vectors-with-randomness2.md, Cargo.lock, Cargo.toml, crates/sdk/src/lib.rs, crates/sdk/src/masp.rs, examples/Cargo.toml, examples/tx_schema.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Augment the MASP test vectors with the used randomness parameters. Also add the schema for the randomness parameters to the `tx-schema` example.
Namada v0.26.1
https://github.com/anoma/masp/pull/84
=> Start including MASP randomness in the test vectors.

.changelog/unreleased/improvements/3305-update-config-rs.md, Cargo.lock, Cargo.toml, crates/apps_lib/src/config/global.rs, crates/apps_lib/src/config/mod.rs
Rebased from #2999 as I couldn't push to source branch.
Closes https://github.com/anoma/namada/issues/2993
As discussed in linked issue `yaml-rust` is not maintened and poses a risk as future vulnerabilities or bugs in yaml-rust will not be addressed. Also it makes noise if you run `cargo-audit`. As advised in [RUSTSEC-2024-0320](https://rustsec.org/advisories/RUSTSEC-2024-0320.html) `yaml-rust2` is a fully compliant YAML 1.2 implementation written in rust and works faster than its predecessor `yaml-rust` and fully compatible with it.
`crates/app` is the affected crate and it fetches `yaml-rust` from `config` crate. 
I've udpated `config` crate to the latest [version](https://github.com/mehcode/config-rs/pull/554) and fixed compilation errors and warnings.
The reason why I'm using commit …
=> remove deprecated dependency from app crate

.changelog/unreleased/improvements/3308-wasmer-upgrade.md, Cargo.lock, Cargo.toml, crates/benches/Cargo.toml, crates/benches/wasm_opcodes.rs, crates/namada/Cargo.toml, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/memory.rs, crates/namada/src/vm/wasm/compilation_cache/common.rs, crates/namada/src/vm/wasm/host_env.rs, crates/namada/src/vm/wasm/memory.rs, crates/namada/src/vm/wasm/run.rs, crates/tests/src/vm_host_env/tx.rs, crates/tests/src/vm_host_env/vp.rs, wasm/Cargo.lock, wasm/Cargo.toml, wasm/tx_bond/Cargo.toml, wasm/tx_change_validator_commission/Cargo.toml, wasm/tx_redelegate/Cargo.toml, wasm/tx_unbond/Cargo.toml, wasm/tx_withdraw/Cargo.toml, wasm/vp_implicit/Cargo.toml, wasm/vp_user/Cargo.toml, wasm_for_tests/Cargo.lock, wasm_for_tests/Cargo.toml
Closes #821 
Closes #1691
`v0.37.0`
=> Upgrade wasmer to 4.3.1

.changelog/unreleased/improvements/3310-scheduled-migrations.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/node/src/bench_utils.rs, crates/node/src/lib.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/testing/node.rs, crates/node/src/shims/abcipp_shim.rs, crates/node/src/storage/rocksdb.rs, crates/sdk/src/migrations.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/setup.rs
Allow nodes to schedule a migrations json to be read and run to facilitate hard-forking. This is done by taking a migrations json and passing the path, a hash of the contents, and a block height to the node when starting the ledger.
=> Scheduled migrations

.changelog/unreleased/improvements/3317-store-ibc-trace-when-minting.md, crates/ibc/src/actions.rs, crates/ibc/src/context/nft_transfer.rs, crates/ibc/src/context/storage.rs, crates/ibc/src/context/token_transfer.rs, crates/ibc/src/event.rs, crates/ibc/src/lib.rs, crates/namada/src/ledger/native_vp/ibc/context.rs, crates/tx_prelude/src/ibc.rs
closes #3317, closes #3229 
Also,
- Remove `get_ibc_events` and IBC event conversion functions
- Fix `is_receiving_success` without checking events
`v0.37.0`
=> Store IBC trace when minting

about.toml
to fix https://github.com/anoma/namada/actions/runs/9312054507/job/25632231677 used in `xxhash-rust` (transitive dep of wasmer)
=> accept BSL-1.0 license

.changelog/unreleased/improvements/3315-wasmer-read-only-mem.md, crates/namada/src/vm/wasm/memory.rs, crates/namada/src/vm/wasm/run.rs
Closes #3314
Based on `v0.38.1`
=> Only grow wasm memory with write ops

.changelog/unreleased/improvements/3333-sync-default-node-addr.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/sdk/src/args.rs
A tiny change - when the `--node` is not specified for `shielded-sync` cmd it should default to the address from local config
v0.38.0
=> cli: use the default configured node addr for shielded sync

.changelog/unreleased/bug-fixes/3340-validator--by-tm-addr.md, crates/sdk/src/queries/vp/pos.rs
Fixes an issue where an invalid input to `validator_by_tm_addr` may cause a node crash. The problem is that the parameter is used as an unsanitized string in input to `namada_proof_of_stake::storage_key::validator_address_raw_hash_key` which only expects valid inputs and panics otherwise.
0.38.1
=> sdk/queries/vp/pos: sanitize the input of `validator_by_tm_addr`

.changelog/unreleased/improvements/3350-diposable-keys-cleanup.md, crates/core/src/time.rs, crates/sdk/src/wallet/mod.rs
Closes #3239
Garbage collect disposable signing keys.
`v0.38.1`
=> Remove old disposable keys from the wallet

Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Bumps `smooth-operator` to [`v0.7.0`](https://github.com/heliaxdev/smooth-operator/tree/v0.7.0), which supports assign ops (e.g. `checked!(x += 1)`).
`v0.38.1`
=> Upgrade smooth-operator to v0.7.0

.changelog/unreleased/improvements/3343-shell-complete.md, Cargo.lock, Cargo.toml, crates/apps/Cargo.toml, crates/apps/src/bin/namada/cli.rs, crates/apps_lib/src/cli.rs, crates/sdk/Cargo.toml, crates/sdk/src/args.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Adds `namada complete` command to generate shell completions. Requires `--shell` with one of:
-  bash
- elvish
- fish
- powershell
- zsh
- nushell
To use in e.g. bash, run `namada complete --shell bash > /usr/share/bash-completion/completions/namada.bash`.
0.39.0
=> cli: add shell completions generator

.changelog/unreleased/features/3356-vectorize-transfers.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/tx.rs, crates/benches/host_env.rs, crates/benches/native_vps.rs, crates/benches/process_wrapper.rs, crates/light_sdk/src/transaction/transfer.rs, crates/node/src/bench_utils.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/masp.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs, crates/tests/src/integration/ledger_tests.rs, crates/token/src/lib.rs, crates/tx_prelude/src/token.rs, wasm/tx_shielding_transfer/src/lib.rs, wasm/tx_transparent_transfer/src/lib.rs, wasm/tx_unshielding_transfer/src/lib.rs
Closes #2596.
Required modification to enable #2597.
Modifies transparent and masp transactions to allow for multi-party transfers. Transparent transfers allow for multiple sources, targets token and amounts.
Shielding and unshielding masp transfers are instead vectorized in a slightly different way: shieldings are vectorized in a fan-in fashion: multiple sources, amounts and tokens but the target is a single `PaymentAddress`. Unshieldings are fan-out: multiple targets, tokens and amount but the source is a single `SpendingKey`.
Ibc shielded actions remain unchanged as I believe we can't vectorize them because of the way packets are designed. 
This PR does NOT update the client to support vectorized transfers as at the moment it's unclear to me how to achieve that maintaining a decent UX: …
=> Vectorize transfers

.changelog/unreleased/improvements/3366-remove-max-block-time-param.md, .github/workflows/scripts/hermes.txt, Cargo.lock, crates/apps_lib/src/client/rpc.rs, crates/apps_lib/src/config/genesis.rs, crates/apps_lib/src/config/genesis/chain.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/core/src/parameters.rs, crates/core/src/time.rs, crates/ibc/src/context/common.rs, crates/ibc/src/context/validation.rs, crates/namada/src/ledger/native_vp/ibc/mod.rs, crates/node/src/storage/mod.rs, crates/parameters/Cargo.toml, crates/parameters/src/lib.rs, crates/parameters/src/storage.rs, crates/proof_of_stake/src/lib.rs, crates/sdk/src/masp.rs, crates/sdk/src/queries/shell.rs, crates/sdk/src/rpc.rs, crates/state/src/lib.rs, crates/storage/src/lib.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/vm_host_env/ibc.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml, scripts/get_hermes.sh, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Remove the `max_expected_time_per_block` genesis parameter.
`v0.39.0`
=> Remove max block time param

.changelog/unreleased/bug-fixes/3375-masp-total-rewards.md, .changelog/unreleased/improvements/3375-masp-total-rewards.md, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs, crates/shielded_token/src/conversion.rs, crates/shielded_token/src/storage.rs, crates/shielded_token/src/storage_key.rs
closes #1730
Additionally, the original impl didn't increment the token total supply with the minted reward. This is fixed by using the `fn credit_tokens` that takes care of it.
v0.39.0
=> store MASP total rewards

.changelog/unreleased/bug-fixes/3378-increase-disposable-key-lifetime.md, crates/sdk/src/wallet/mod.rs
Increase the lifetime of disposable signing keys from 5 minutes to 1 week.
`v0.39.0`
=> Increase disposable key lifetime

.changelog/unreleased/improvements/3380-remove-max-sigs.md, crates/apps_lib/src/config/genesis.rs, crates/apps_lib/src/config/genesis/chain.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/apps_lib/src/config/genesis/transactions.rs, crates/core/src/parameters.rs, crates/namada/src/ledger/native_vp/masp.rs, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/wasm/host_env.rs, crates/node/src/storage/mod.rs, crates/parameters/src/lib.rs, crates/parameters/src/storage.rs, crates/proof_of_stake/src/lib.rs, crates/state/src/lib.rs, crates/tests/src/vm_host_env/mod.rs, crates/tests/src/vm_host_env/tx.rs, crates/tests/src/vm_host_env/vp.rs, crates/tx/src/types.rs, crates/tx_prelude/src/lib.rs, crates/vm_env/src/lib.rs, crates/vp_prelude/src/lib.rs, genesis/localnet/parameters.toml, wasm/tx_become_validator/src/lib.rs, wasm/tx_change_consensus_key/src/lib.rs, wasm/vp_implicit/src/lib.rs, wasm/vp_user/src/lib.rs
=> Remove max number of signatures per tx

.changelog/unreleased/improvements/3383-add-db-snapshots.md, .changelog/unreleased/improvements/3386-listsnapshots-loadsnapshotchunk.md, Cargo.lock, crates/apps_lib/src/config/mod.rs, crates/core/src/storage.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/snapshots.rs, crates/node/src/shims/abcipp_shim.rs, crates/node/src/shims/abcipp_shim_types.rs, crates/node/src/storage/mod.rs, crates/node/src/storage/rocksdb.rs, crates/sdk/src/masp/utils.rs, crates/storage/src/db.rs
Addresses the third point and part of the fourth point of Issue #3307 
- Adds chunking logic to snapshots
- Implements the `ListSnapshots` ABCI call
- Implements the `LoadSnapshotChunk` ABCI call
Built on top of #3383
=> ListSnapshots and LoadSnapshotChunk methods

.changelog/unreleased/improvements/3390-remove-multipler-check-governance.md, crates/governance/src/parameters.rs, crates/namada/src/ledger/governance/mod.rs, crates/namada/src/ledger/native_vp/ibc/mod.rs
=> governance: remove epoch multipler check 

.changelog/unreleased/improvements/3391-parameterize-gas-scale.md, crates/apps_lib/src/config/genesis.rs, crates/apps_lib/src/config/genesis/chain.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/core/src/parameters.rs, crates/gas/src/event.rs, crates/gas/src/lib.rs, crates/namada/src/ledger/mod.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/src/bench_utils.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs, crates/node/src/storage/mod.rs, crates/parameters/src/lib.rs, crates/parameters/src/storage.rs, crates/proof_of_stake/src/lib.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/state/src/lib.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tx/src/data/mod.rs, crates/tx/src/data/wrapper.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
=> Parameterize gas scale

.changelog/unreleased/testing/3401-test-batch-tx-events.md, crates/node/src/shell/finalize_block.rs, crates/tx/src/data/mod.rs
Closes #3397
Adds additional test coverage to batch tx events emission, to make sure we correctly build a batch of inner tx events from a batched tx.
`v0.39.0`
=> Test batch tx events

.changelog/unreleased/improvements/3416-uniquely-identify-inner-txs.md, Cargo.lock, Cargo.toml, crates/apps_lib/Cargo.toml, crates/apps_lib/src/client/tx.rs, crates/namada/Cargo.toml, crates/namada/src/ledger/mod.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/Cargo.toml, crates/node/src/bench_utils.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/governance.rs, crates/sdk/Cargo.toml, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/tx/Cargo.toml, crates/tx/src/data/mod.rs, crates/tx/src/lib.rs, crates/tx/src/types.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> Index batched txs via their wrapper and commitment hashes

.changelog/unreleased/bug-fixes/3432-respect-wasm-dir.md, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/utils.rs, crates/tests/src/integration/setup.rs
=> respect wasm-dir on init-network

.changelog/unreleased/improvements/2891-sdk-query-height.md, crates/node/src/bench_utils.rs, crates/node/src/shell/testing/node.rs, crates/sdk/src/masp.rs, crates/sdk/src/queries/mod.rs
Closes #2891.
Changes the `Into` trait bound for the height param of queries to `TryInto` to minimize the cast error.
`v0.39.0`
=> Fallible trait bound for queries' height param

.changelog/unreleased/improvements/3442-limit-pgf-stewards.md, crates/apps_lib/src/config/genesis/chain.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/governance/src/pgf/parameters.rs, crates/governance/src/pgf/storage/keys.rs, crates/node/src/shell/governance.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
Introduced a new genesis parameter to limit the number of pgf stewards.
0.39.0
=> Limit number of pgf stewards

.changelog/unreleased/improvements/3192-opt-recomm.md, .changelog/unreleased/improvements/3448-streamline-validation.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/apps_lib/src/config/mod.rs, crates/node/src/lib.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/governance.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs
Closes #3190.
Closes #3193.
This PR fixes some wrong documentation for the `finalize_block` and `check_proposal_tx_function`.
It also introduces a new local configuration parameter to allows a node to rerun the `process_proposal` checks before finalize block in case they don't want to blindly trust the majority of validators. This is implemented for both full nodes and validators since the latter could also skip the `process_proposal` call in some cases.
#3192 (diffs for review: https://github.com/anoma/namada/pull/3448/files/176754fbd523ec7d17a1dbbd10f59900b846aeb1..1a704b679b122656aa4ff6d0baa947054c326271)
=> Streamline validation

.github/workflows/scripts/e2e.json, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs
closes #3253
closes https://github.com/anoma/namada/issues/305
v0.40.0
- ~~[ ] I have added a changelog~~ tests only
=> masp e2e test

.changelog/unreleased/improvements/3312-outsource-masp-sig-verification.md, .changelog/unreleased/improvements/3516-reduce-masp-vp-signatures.md, crates/namada/src/ledger/native_vp/masp.rs, crates/namada/src/ledger/protocol/mod.rs, crates/trans_token/src/storage.rs, crates/tx/src/action.rs, crates/tx_prelude/src/token.rs, wasm/tx_ibc/src/lib.rs, wasm/tx_transfer/src/lib.rs, wasm/vp_implicit/src/lib.rs, wasm/vp_user/src/lib.rs
Closes #3312.
Swaps the signature verification call in the masp vp with a check on the triggered vps. Introduces a new masp `Action` to support signature verification in the affected vps since we expect them to not be triggered by the transaction itself (no changed keys).
#3516 (diffs for review: https://github.com/anoma/namada/pull/3372/files/17b9fcfa9c85f5a115646120f6595e8cf28c38a7..fc63450e3dfc2882c467d96a2600d761fb40853b)
=> Outsource masp signature verification

.changelog/unreleased/improvements/3405-phase-1-shielded-sync-refactor.md, .changelog/unreleased/improvements/3456-masp-ss-phase-2.md, Cargo.lock, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/masp.rs, crates/node/src/bench_utils.rs, crates/sdk/Cargo.toml, crates/sdk/src/args.rs, crates/sdk/src/control_flow/mod.rs, crates/sdk/src/error.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/test_utils.rs, crates/sdk/src/masp/utils.rs, crates/sdk/src/queries/mod.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Implements phase 2 of Issue #3385
Based on #3498
**Diff for review:** https://github.com/anoma/namada/compare/tiago/masp-ss-client-phase-1..tiago/masp-ss-phase-2
=> Phase 2 of Shielded Sync refactor

.changelog/unreleased/improvements/3471-remove-gov-prop-id-input.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/governance/src/cli/onchain.rs, crates/governance/src/cli/validation.rs, crates/governance/src/pgf/inflation.rs, crates/governance/src/pgf/mod.rs, crates/governance/src/pgf/storage/mod.rs, crates/governance/src/pgf/storage/steward.rs, crates/node/src/shell/governance.rs, crates/sdk/src/queries/vp/pgf.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/ledger_tests.rs, scripts/add_proposal_wasm_code.py, scripts/default_proposal_template.json, scripts/funding_proposal_template.json, scripts/steward_proposal_template.json, scripts/template_proposal.json
Minor improvements that include
- remove remnant gov proposal ID input
- template gov proposal json files
- python script to attach wasm code to default proposal
v0.40.0
=> Minor gov improvements

.changelog/unreleased/improvements/3502-without-pow.md, crates/sdk/src/tx.rs
Removed redundant build_pow_flag function.
Namada v0.40.0
=> Removed redundant build_pow_flag function.

.changelog/unreleased/improvements/3516-reduce-masp-vp-signatures.md, crates/namada/src/ledger/native_vp/masp.rs
This PR attempts to eliminate the MASP VP's requirement (mentioned in https://github.com/anoma/namada/pull/3372#issuecomment-2225421559) for all debited accounts to sign a `Tx`. This is done by requiring only those accounts whose balances are modified by the inner `Transaction` and whose balances decrease to sign the transaction. The justification for this change is that in the case of accounts not modified by the inner `Transaction`, other VPs already validate all changes pertaining to the given address.
Namada 0.40.0
=> Eliminates MASP VP's requirement for all debited accounts to sign Tx

.changelog/v0.40.0/bug-fixes/3488-fix-ibc-masp-tx-extraction.md, crates/core/src/ibc.rs, crates/events/src/extend.rs, crates/namada/src/ledger/mod.rs, crates/namada/src/ledger/protocol/mod.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/masp.rs, crates/tx/src/data/mod.rs, crates/tx/src/types.rs
=> Fix IBC MASP tx extraction

.changelog/unreleased/bug-fixes/3529-leak-workaround.md, Cargo.lock, Cargo.toml, crates/namada/Cargo.toml, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/wasm/compilation_cache/common.rs, crates/namada/src/vm/wasm/memory.rs, crates/namada/src/vm/wasm/run.rs, crates/tests/Cargo.toml, crates/tests/src/vm_host_env/tx.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
workaround for https://github.com/wasmerio/wasmer/issues/4377 and https://github.com/wasmerio/wasmer/issues/4949
v0.40.0
=> workaround wasmer leak

.changelog/unreleased/bug-fixes/3543-fix-verify-sig-panic.md, crates/tx/src/types.rs
The index op used to look-up signatures may fail if there isn't matching number of signatures.
v0.40.0
=> fix possible panic in sig verification

.changelog/unreleased/improvements/3473-opt-validation-calls.md, Cargo.lock, crates/core/src/hash.rs, crates/node/src/lib.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/queries.rs, crates/node/src/shell/testing/node.rs, crates/node/src/shell/vote_extensions/bridge_pool_vext.rs, crates/node/src/shell/vote_extensions/eth_events.rs, crates/node/src/shell/vote_extensions/val_set_update.rs, crates/node/src/shims/abcipp_shim.rs, crates/node/src/shims/abcipp_shim_types.rs, crates/state/Cargo.toml, crates/state/src/in_memory.rs, crates/state/src/lib.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
This PR tries to improve the extra calls to process proposal requested by Namada (nothing changes for the requests coming from Comet). More specifically:
- The more complete `process_proposal` is now called instead of `process_txs`
- The `InMemory` struct has been expanded with an extra field that caches the requests to `process_proposal` for a given block so that future calls can be avoided. This cache is cleared when handling a `FinalizeBlock` request
`v0.40.0`
=> Avoid multiple calls to `process_proposal`

.changelog/unreleased/improvements/3405-phase-1-shielded-sync-refactor.md, Cargo.lock, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/masp.rs, crates/sdk/Cargo.toml, crates/sdk/src/control_flow/mod.rs, crates/sdk/src/error.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/test_utils.rs, crates/sdk/src/masp/utils.rs, crates/sdk/src/queries/mod.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Supersedes #3405, #3426 (rebase of the last one on the latest release)
Implements phase 1 of Issue #3385 
- When fetching notes, connections and related failures should not halt shielded sync. Instead, the process should be restarted
-   If fetching is interrupted, the data fetched should be persisted locally so that progress isn't lost
-  A trait for fetching behavior should be added to provide modularity 
`v0.40.0`
=> MASP shielded sync client phase 1

.changelog/unreleased/bug-fixes/3540-fix-query-proposal-result-vp.md, crates/governance/src/utils.rs, crates/sdk/src/queries/vp/pos.rs, crates/sdk/src/rpc.rs
Need to use the total active voting power instead of total deltas inside `fn query_proposal_result`.
Closes #3532.
v0.40.0
=> Use total active voting power in `query_proposal_result`

scripts/get_cometbft.sh
Updated `get_cometbft.sh` script to v0.37.9. Very silly PR, but it prevents v0.37.2 to get installed when the `make install` command gets run.
=> Updated get_cometbft.sh script

.changelog/unreleased/bug-fixes/3566-fix-update-account-client-checks.md, crates/sdk/src/tx.rs
=> fix client checks on update account

.changelog/unreleased/improvements/3547-fix-fee-log-msg.md, crates/node/src/protocol.rs
Improves the trace error message in case of a failed masp fee payment.
`v0.41.0`
=> Improve fee tracing message

crates/tests/src/e2e/ledger_tests.rs
Sometimes the `epoch-sleep` command runs when the first epoch has already started and then fails. Instead just wait for a first block before running the tested cmds
0.41.0
- ~~[ ] I have added a changelog~~ - testing only
=> test/e2e/masp: wait for first block instead of epoch

.changelog/unreleased/bug-fixes/3594-client-fix.md, crates/apps_lib/src/client/tx.rs, crates/proof_of_stake/src/error.rs, crates/proof_of_stake/src/lib.rs
- Closes #3552.
- No-op instead of error if a withdraw tx is forced when no unbonds exist.
682d7ff
=> Client improvements

.changelog/unreleased/improvements/3614-implicit-addr-balances-toml.md, crates/apps_lib/src/config/genesis.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/apps_lib/src/config/genesis/transactions.rs, crates/node/src/shell/init_chain.rs, crates/tests/src/e2e/setup.rs
=> Support arbitrary addresses in `balances.toml`

crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs, crates/tests/src/lib.rs
- reduced the number of validators (and hence nodes) involved in the test
- added a retry mechanism:
- Often, the `validator_0_copy` detects the duplicate votes and doesn't report them. It then stores the sig in `priv_validator_state.json` which prevents it from attempting to double sign again
- To get around it, we try to stop the `validator_1` that owns the consensus so that it stops producing blocks while we're clearing out the signature and restarting the duplicate validator node
0.41.0
=> test/e2e: make slashing test more reliable

.changelog/unreleased/bug-fixes/3645-implicit-addr-balances-toml-fix.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/utils.rs, crates/apps_lib/src/config/genesis.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/apps_lib/src/config/genesis/transactions.rs, crates/node/src/shell/init_chain.rs, crates/tests/src/e2e/setup.rs, genesis/hardware/balances.toml, genesis/localnet/balances.toml
=> Only allow `tnam1...` addresses in `balances.toml`

.changelog/unreleased/improvements/3615-no-parallel-gas.md, .github/workflows/scripts/hermes.txt, crates/gas/src/lib.rs, crates/node/src/protocol.rs, crates/shielded_token/src/validation.rs, crates/tx/src/data/mod.rs, scripts/get_hermes.sh
Closes #3587.
Depends-On: https://github.com/anoma/namada/pull/3573
This PR removes the parallel gas dividers and the `VpsGas` type which isn't needed anymore. It also removes the gas used field from `VpsResult`.
=> Remove parallel gas

.changelog/unreleased/improvements/3632-check-masp-action.md, crates/governance/src/vp/mod.rs, crates/ibc/src/vp/mod.rs, crates/node/src/protocol.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs, crates/shielded_token/src/vp.rs, crates/state/src/wl_state.rs, crates/state/src/write_log.rs, crates/tx/src/action.rs
Changes `get_masp_section_ref` to return an error if more than one MASP action is found (MASP VP doesn't handle multiple `Transaction` objects).
Also adjusts the logic, in case of an error propagation from tx execution, to prevent committing the changes applied by the failed tx.
=> Check masp action

.changelog/unreleased/features/3653-masp-key-birthdays.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/cli/context.rs, crates/apps_lib/src/cli/wallet.rs, crates/apps_lib/src/client/masp.rs, crates/benches/native_vps.rs, crates/core/src/masp.rs, crates/node/src/bench_utils.rs, crates/sdk/src/args.rs, crates/sdk/src/masp.rs, crates/sdk/src/wallet/keys.rs, crates/sdk/src/wallet/mod.rs, crates/sdk/src/wallet/store.rs
Partially addresses Issue #2900. Viewing and spending keys can no be given birthdays in the form of block heights which are loaded into shielded sync. Shielded sync will not try to decrypt a block before a keys birthday with said key. 
=> Add birthdays to MASP keys

.changelog/unreleased/improvements/3655-speed-up-ctx-build.md, crates/apps_lib/src/cli/context.rs, crates/apps_lib/src/config/genesis/chain.rs
Speeds up client commands on networks with massive `balances.toml` files. Previously, to retrieve the native token of some network, we had to parse these giant files. Now, we only parse the necessary genesis `toml` files required to retrieve the native token.
=> Optimize building chain ctx

.changelog/unreleased/improvements/3652-ctxless-node-utils.md, .github/workflows/scripts/e2e.json, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/node/src/lib.rs, crates/node/src/shell/testing/client.rs, crates/tests/src/e2e/ledger_tests.rs
Do not load `Context` for node utils (`test-genesis`) cmds
=> ctxless cli node utils

.changelog/unreleased/features/3660-check-pre-genesis-signing.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/node/src/utils.rs, crates/tests/src/e2e/ledger_tests.rs
- added `--check-can-sign` arg to `namadan utils test-genesis`
- use in e2e test
example output from the e2e checking established addr, implicit addr and a PK:
```shell
Found a matching genesis established account tx with 1 public key(s).
Able to sign with tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha for tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu
Able to sign with tnam1qpca48f45pdtpcz06rue7k4kfdcjrvrux5cr3pwn
Able to sign with tpknam1qpg2tsrplvhu3fd7z7tq5ztc2ne3s7e2ahjl2a2cddufrzdyr752g666ytj
```
=> check pre genesis signing

.changelog/unreleased/improvements/3669-fix-masp-ident.md, crates/apps_lib/src/cli.rs, crates/node/src/protocol.rs, crates/shielded_token/src/vp.rs, crates/tests/src/integration/masp.rs
This PR addresses some minor issues:
- enforces the same order of retrieval for MASP data across protocol and the MASP VP
- ensures that, before extracting any possible MASP section reference from an Action, we verify that the tx was indeed a MASP one (the Action itself is not enough since it does not trigger the MASP VP)
- Adds an additional integration test to check that only MASP transaction can be used to pay fees when the payer's balance is not enough
- Improves the help message of `--gas-limit` which was still referring to the old logic using the multiplier
=> Fix masp events

.changelog/unreleased/improvements/3676-fix-wasm-test-deps.md, wasm_for_tests/Cargo.lock, wasm_for_tests/Makefile, wasm_for_tests/tx_fail/Cargo.toml, wasm_for_tests/tx_infinite_guest_gas/Cargo.toml, wasm_for_tests/tx_infinite_host_gas/Cargo.toml, wasm_for_tests/tx_invalid_data/Cargo.toml, wasm_for_tests/tx_memory_limit/Cargo.toml, wasm_for_tests/tx_no_op/Cargo.toml, wasm_for_tests/tx_proposal_code/Cargo.toml, wasm_for_tests/tx_proposal_ibc_client_upgrade/Cargo.toml, wasm_for_tests/tx_proposal_ibc_token_inflation/Cargo.toml, wasm_for_tests/tx_proposal_masp_reward/Cargo.toml, wasm_for_tests/tx_read_storage_key/Cargo.toml, wasm_for_tests/tx_write/Cargo.toml, wasm_for_tests/vp_always_false/Cargo.toml, wasm_for_tests/vp_always_true/Cargo.toml, wasm_for_tests/vp_eval/Cargo.toml, wasm_for_tests/vp_infinite_guest_gas/Cargo.toml, wasm_for_tests/vp_infinite_host_gas/Cargo.toml, wasm_for_tests/vp_memory_limit/Cargo.toml, wasm_for_tests/vp_read_storage_key/Cargo.toml
Closes #3606.
Removes the dev-dependencies of wasm for tests
=> Remove unused deps for `wasm_for_tests`

.changelog/unreleased/bug-fixes/3675-improve-init-proposal-validation.md, crates/trans_token/src/storage.rs
To make things easier, lets make transfer fails if `source == dest`
=> token: fix transfer to self

Makefile
fixes the `make build` recipe to avoid enabling `"testing"` feature from fuzz targets
=> make build: exclude fuzz targets

.changelog/unreleased/testing/3680-gen-localnet-fullnodes.md, scripts/gen_localnet.py, scripts/localnet-2.sh
This PR augments the functionality of `gen_localnet.py` with the ability to generate full node base directories. Moreover, adds a new `localnet-2` localnet starter kit with 2 validator nodes, and a script to start from this new localnet with either of the validator nodes or a full node.
=> Augment the functionality of `gen_localnet.py`

crates/apps_lib/src/client/rpc.rs, crates/sdk/src/rpc.rs
In `namada_sdk::rpc::` we should always use take a client as parameter and not the context. This makes integrations with other softwares easier.
=> sdk: use client instead of context

.changelog/unreleased/improvements/3689-misc-gov-fixes.md, crates/apps_lib/src/cli.rs, crates/governance/src/vp/mod.rs, wasm/vp_implicit/src/lib.rs
Addresses some minor governance issues:
- Removed the unused `PROPOSAL_ETH` cli arg
- Fixes the fact that the required `--proposal-id` arg was not shown in the help message of `proposal-vote`
- Updates the error message in the governance vp that we raise when the voter is not a validator nor delegator to also mention the epoch at which they should have been so (someone might delegate after the beginning of the voting period and struggle to understand why the transaction fails)
=> Minor fixes to governance cli/msgs

.changelog/unreleased/bug-fixes/3700-fix-error-mishandling.md, crates/governance/src/vp/mod.rs, crates/governance/src/vp/pgf.rs, crates/ibc/src/vp/mod.rs, crates/trans_token/src/vp.rs
Closes #3238.
I've reviewed the code for our native vps and removed the wrong calls to `unwrap_or_default` applied to results (those on options are fine).
⚠️ **WARNING** ⚠️
Pay attention to merging this PR cause it carries breaking changes that span multiple vps, including especially the governance one: so even in the context of the multi-stage deployment of mainnet this could cause problems.
=> Propagates error from `is_proposal_accepted`

crates/token/src/lib.rs
Adds test coverage to `Transfer` struct and its methods.
=> Add test coverage on token transfer struct

.changelog/unreleased/improvements/3687-apply-snapshots.md, crates/apps_lib/src/config/mod.rs, crates/merkle_tree/src/lib.rs, crates/node/src/lib.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/snapshots.rs, crates/node/src/shell/testing/node.rs, crates/node/src/shims/abcipp_shim.rs, crates/node/src/storage/mod.rs, crates/node/src/storage/rocksdb.rs, crates/node/src/tendermint_node.rs, crates/state/src/wl_state.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs, crates/tests/src/integration/ledger_tests.rs
Addresses the remaining points of Issue #3307 
- Adds chunking logic to snapshots
- Implements the `OfferSnapshot` ABCI call
- Implements the `ApplySnapshotChunk` ABCI call
=>  Apply snapshot for state sync

.changelog/unreleased/improvements/3701-snapshot-improvements.md, Cargo.lock, Cargo.toml, crates/node/Cargo.toml, crates/node/src/shell/mod.rs, crates/node/src/shell/snapshots.rs, crates/node/src/shims/abcipp_shim.rs, crates/node/src/shims/abcipp_shim_types.rs, crates/node/src/storage/mod.rs, crates/node/src/storage/rocksdb.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs, crates/tests/src/integration/ledger_tests.rs
These changes optimize the format of snapshots taken for state syncing purposes. Snapshots are taken over the entire RocksDB database, packaged into a `zstd` compressed `tar` archive, and split into 10 MB chunks.
=> Optimize state sync snapshot format

.github/workflows/ci.yml, Makefile, codecov.yml, crates/apps_lib/Cargo.toml, crates/apps_lib/src/config/genesis.rs, crates/core/Cargo.toml, crates/core/src/bytes.rs, crates/core/src/chain.rs, crates/core/src/ibc.rs, crates/core/src/masp.rs, crates/core/src/string_encoding.rs, crates/merkle_tree/src/lib.rs, crates/node/Cargo.toml, crates/node/src/shell/init_chain.rs, crates/node/src/shell/mod.rs, crates/sdk/Cargo.toml, crates/state/Cargo.toml, crates/tests/Cargo.toml
related to #1497
Depends-On: #3697
- add couple basic tests in core
- removes "integration" feature
=> more tests

.changelog/unreleased/improvements/3703-change-default-gov-quorum.md, crates/core/src/dec.rs, crates/governance/src/utils.rs
=> Change default proposal quorum

.changelog/unreleased/improvements/3720-batch-reveal-pk.md, crates/apps_lib/src/client/tx.rs
Closes #1879.
When the client detects that an extra `reveal_pk` transaction is needed, instead of submitting it as a separate tx before the intended one, it now groups the two (or more) transactions together and submits them as a single batch.
=> Batch `reveal_pk`

scripts/gen_localnet.py, scripts/localnet-2.sh
Improve `gen_localnet.py` script in various ways:
- Allow editing the `config.toml` of nodes, under `--edit-config`
- Rename `--edit` to `--edit-templates`
- Allow running arbitrary Python code to e.g. append new balance entries to `balances.toml` in `--edit-*` family of options
- Fix a minor bug in display paths
- Handle multiple `--edit-*` arguments in the CLI
- Support loading `--edit-*` params from a file path
With these changes, we also improve the `localnet-2.sh` script. Rather than using `sed` to assign a new balance, we use the new `gen_localnet.py` features.
=> Improve `gen_localnet.py` and `localnet-2.sh` scripts

.changelog/unreleased/improvements/3691-cli-commands.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/args.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs, crates/tests/src/e2e/setup.rs, crates/tests/src/integration/ledger_tests.rs
=> CLI queries for total supply info

.changelog/unreleased/improvements/3741-run-aux-arbitrary-tasks.md, crates/node/src/abortable.rs, crates/node/src/ethereum_oracle/mod.rs, crates/node/src/lib.rs
Closes #459
Refactors the ledger boot-up code under `run_aux`, to support a dynamic number of managed tasks.
=> Dynamic ledger managed tasks

crates/node/src/shell/testing/node.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/masp.rs
- fix `integration::ledger_tests::pgf_governance_proposal` determinism issue
- add inflation integration test
=> fix next epoch

crates/apps_lib/build.rs, crates/tests/src/integration/setup.rs
Without `archive_dir` init-network creates the archive file in the current dir (`crates/tests`) which forces recompilation.
=> use test-dir for network archive to avoid re-compilations after test run

.changelog/unreleased/improvements/3728-improve-gov-output.md, crates/apps_lib/src/client/rpc.rs, crates/apps_lib/src/client/tx.rs, crates/core/src/uint.rs, crates/governance/src/storage/proposal.rs, crates/governance/src/utils.rs, crates/governance/src/vp/mod.rs, crates/proof_of_stake/src/rewards.rs, crates/sdk/src/rpc.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/ledger_tests.rs, scripts/default_proposal_template_with_wasm.json
Closes #3474.
Also fixes the validator voting period, which was found to be slightly buggy. Fix a bug left over from #3691.
=> Improve logging for validator voting period

.changelog/unreleased/improvements/3757-better-custom-tx-error.md, crates/apps_lib/src/cli.rs, crates/sdk/src/tx.rs
=> Improve custom tx error and help msg

.changelog/unreleased/improvements/3715-improve-offline-tx-handling.md, .github/workflows/scripts/e2e.json, Cargo.lock, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/tx.rs, crates/apps_lib/src/client/utils.rs, crates/core/src/hash.rs, crates/core/src/key/common.rs, crates/core/src/key/secp256k1.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs, crates/tests/src/e2e/helpers.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/helpers.rs, crates/tests/src/integration/ledger_tests.rs, crates/tx/src/lib.rs, crates/tx/src/sign.rs, crates/tx/src/types.rs
=> improve offline tx handling

.changelog/unreleased/improvements/3735-update-tendermint-rs.md, Cargo.lock, Cargo.toml, crates/ibc/src/actions.rs, crates/ibc/src/context/common.rs, crates/ibc/src/event.rs, crates/ibc/src/lib.rs, crates/ibc/src/vp/mod.rs, crates/node/src/bench_utils.rs, crates/node/src/shell/testing/node.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs, crates/tests/src/vm_host_env/ibc.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
- Update tendermint-rs, ibc-rs (based on v0.54), prost, and tower-abci
=> Update tendermint-rs to v0.38

.changelog/unreleased/bug-fixes/3724-fix-masp-expiration.md, crates/apps_lib/src/cli.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/testing/node.rs, crates/sdk/src/args.rs, crates/sdk/src/tx.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/masp.rs, crates/tests/src/integration/setup.rs, crates/tx/src/data/mod.rs
Closes #3586.
- Fixes a bug by which the SDK would not set the correct expiration to MASP `Transaction`s
- Adds an integration test for masp expiration
- Removes some outdated assertions based on the old double-block execution scheme
- Improves assertions on `MockNode`
- Wraps `MockNode` into a single `Arc`
=> Fixes MASP tx expiration in the SDK

.changelog/unreleased/improvements/3746-fix-storage-gas-cost.md, crates/gas/src/lib.rs, crates/node/src/dry_run_tx.rs, crates/node/src/protocol.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/lib.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/masp.rs, genesis/hardware/parameters.toml, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
Recovers the fix to the storage gas cost that was done in #3510 and went lost in #3554. Adjusts the `DEFAULT_GAS_LIMIT` and the gas limits in the genesis files.
Also improves gas tracking for masp fee payment: the gas meter now does not account for the gas used up to that point (wrapper gas) which could prevent some txs that consume a lot of gas in that phase (e.g. batches) from successfully pay fees via the MASP.
=> Update storage gas cost

.changelog/unreleased/improvements/3734-query-active-validators.md, crates/sdk/src/rpc.rs
=> rpc: add query consensus validators

.changelog/unreleased/improvements/3530-balance-query-at-height.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/rpc.rs, crates/apps_lib/src/client/tx.rs, crates/light_sdk/src/reading/asynchronous/account.rs, crates/sdk/src/args.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs
This adds an `Option` argument to `get_token_balance` which permits querying for balances at specific block heights. Additionally, this feature is implemented for the `namadac` CLI via the `--height` argument.
This is needed for accounting / auditing purposes and for some upcoming enhancements I will be contributing to `namada-indexer`.
This is a breaking change to the client SDK only. (The node RPC already supports this option)
Example:
```
$ ./target/debug/namadac balance \
--node https://rpc.namada.tududes.com:443 \
--chain-id tududes-test.81efb06d86523ae4f \
--token tnam1q87wtaqqtlwkw927gaff34hgda36huk0kgry692a \
--owner tnam1qrcqrpj8r8lv6632wcwv9j0r6pp4n3xsug9hkxzx
nam: 9588921.2
$ ./target/debug/namadac balance \
--node https://rpc.namada.tududes.com:443 \
--chain-id …
```
=> [feature] Allow balance querying at specified block height

.changelog/unreleased/improvements/3758-improve-dry-run.md, crates/gas/src/lib.rs, crates/governance/src/vp/mod.rs, crates/node/src/dry_run_tx.rs, crates/node/src/protocol.rs, crates/shielded_token/src/utils.rs, crates/trans_token/src/storage.rs, crates/vm/src/host_env.rs
Reiterates on #3758 which was not merged successfully. 
=> Improve dry run rebase

.github/workflows/ci.yml
Trying to fix the "Warning: No files were found with the provided path" in e2e logs (see e.g. https://github.com/anoma/namada/actions/runs/10741598514/job/29792796240)
=> fix e2e logs

.changelog/unreleased/bug-fixes/3730-enable-hw-fallback.md, crates/sdk/src/signing.rs
Currently the transaction signing logic fails fall back to the hardware wallet if the secret key is not found in the wallet store. This is because an error is propagated as soon as the secret key lookup fails. This PR fixes that. Additionally, the signing code now checks that the number of public keys used in signing exceeds the given account's threshold.
=> Enable the signing logic to fall back to the hardware wallet if secret key is not found.

.changelog/unreleased/improvements/3779-restrict-metadat-name-len.md, crates/apps_lib/src/config/genesis/transactions.rs, crates/sdk/src/tx.rs
When we added `name`, forgot to include a check on the string length
=> Check length of validator name in metadata

.changelog/unreleased/improvements/3788-update-params-query.md, crates/apps_lib/src/client/rpc.rs
This work would not be possible without @sug0 @Fraccaman @grarco @batconjurer
=> Update parameters query

.changelog/unreleased/improvements/3805-better-conversions-logging.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/args.rs
=> Better conversions debugging

.changelog/unreleased/improvements/3806-validate-nam-masp-params.md, crates/node/src/shell/init_chain.rs
When calling init chain, we now verify that the native token alias has masp parameters set.
=> Validate genesis NAM MaspParams

.github/pull_request_template.md
A new default PR description that reminds devs about needed updates to docs, specs, and services such as indexers.
=> Update default PR description

.changelog/unreleased/improvements/3816-estimate-staking-reward-rate.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/rpc.rs, crates/proof_of_stake/src/rewards.rs, crates/sdk/src/args.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs, crates/tests/src/integration/ledger_tests.rs
=> Estimate annual staking rewards rate

.changelog/unreleased/bug-fixes/3821-fix-masp-events.md, crates/core/src/ibc.rs, crates/core/src/masp.rs, crates/events/src/extend.rs, crates/node/src/bench_utils.rs, crates/node/src/protocol.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/utilities.rs, crates/shielded_token/src/lib.rs, crates/shielded_token/src/masp/shielded_sync/dispatcher.rs, crates/shielded_token/src/masp/shielded_sync/utils.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/masp.rs, crates/tx/src/data/mod.rs, crates/tx/src/types.rs
Unifies the previous two masp refs events into a single `MaspTxBatchRefs` event: this ensures that no reordering of masp data can happen on the client side that would lead to the construction of an invalid state.
Updates the `IndexedTx` type to carry an optional pointer to a specific inner tx inside a batch. This fixes an issue for which the shielded sync command could not properly process multiple masp transactions in a same batch: it was appending the decrypted tx to a map using as an index the same block height and tx index, effectively taking into account only the last masp transaction of a batch 
TODOs:
- <s>See if there's a better way to emit the masp ref event (maybe without the need for `ExtendedTxResult`)</s> (#3824 )
- <s>Update the indexer</s>
- This will require 2 reviewers to …
=> Unify MASP refs events 

.changelog/unreleased/improvements/3826-reduce-masp-events.md, crates/events/src/extend.rs, crates/node/src/bench_utils.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/utilities.rs
Closes #3824.
Reduces the number of a tx event's masp attributes down to a single one.
- Relevant PR if applies: https://github.com/anoma/namada-masp-indexer/pull/22
=> Reduce event's masp attributes

.changelog/unreleased/improvements/3830-rem-eth-help-msg.md, crates/apps_lib/src/cli.rs
Small PR to remove them from help messages in binaries (not built anymore anyway)
=> Remove relayer and bridge pool from help msgs

crates/apps_lib/src/cli.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs
Currently, the binaries panic on trying to parse commands pertaining to the relayer binary. This fixes that.
=> [fix]: Fix clap panic on parsing relayer commands

.changelog/unreleased/improvements/3833-pre-genesis-chain-id.md, .github/workflows/scripts/e2e.json, crates/apps_lib/src/config/genesis/transactions.rs, crates/node/src/utils.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs
=> genesis: use env to configure pre-genesis chain-id

.changelog/unreleased/improvements/3833-pre-genesis-chain-id.md, .changelog/unreleased/improvements/3843-check-genesis.md, .github/workflows/scripts/e2e.json, crates/apps_lib/src/config/genesis/chain.rs, crates/apps_lib/src/config/genesis/transactions.rs, crates/core/src/chain.rs, crates/node/src/shell/init_chain.rs, crates/node/src/utils.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs
- Depends-On: #3833
On init-chain, the node should be checking that the genesis files have not been tempered with by using the Chain ID.
=> check consistency of genesis files with chain ID

crates/apps_lib/src/client/rpc.rs, crates/apps_lib/src/config/genesis/templates.rs, crates/governance/src/parameters.rs
=> Fix max proposal code size docstring

.mergify.yml
=> mergify: add backport strategy

.changelog/unreleased/testing/3857-batch-events-tests.md, crates/events/src/extend.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs, crates/test_utils/src/lib.rs, crates/tx_prelude/src/lib.rs, wasm_for_tests/Cargo.lock, wasm_for_tests/Cargo.toml, wasm_for_tests/Makefile, wasm_for_tests/tx_fail_event/Cargo.toml, wasm_for_tests/tx_fail_event/src/lib.rs, wasm_for_tests/tx_no_op_event/Cargo.toml, wasm_for_tests/tx_no_op_event/src/lib.rs
Partially addresses #3828.
- Adds unit tests for gas payment with whitelisted, non-native token
- Adds unit tests for batched txs' events
- Removes the unused `Success` event
- Misc refactor of tx signatures in unit tests
=> Batch events tests

.mergify.yml
Allows to use "merge" label with backported PRs
=> ci/mergify: add merge rule for backport to 0.44

.mergify.yml
=> mergify: add backport strategy - backport PR#3849 to 0.44

crates/tx_prelude/src/proof_of_stake.rs, wasm/tx_vote_proposal/src/lib.rs
=> governance: let validator vote even if it doesn't have a self-bond

.changelog/unreleased/improvements/3882-better-batch-construction.md, crates/sdk/src/signing.rs, crates/tx/src/types.rs
=> Avoid duplicated sections in batches

crates/tests/src/e2e/setup.rs
Some e2e tests rely on background processes, especially the IBC ones with `hermes` and `gaiad`. There are cases in which the test fails and some of these tasks (especially `gaiad`) are not affected by the crash of the Namada node. In this case the runtime drops the `NamadaBgCmd` but unfortunately dropping a `JoinHandle` only detaches the target task. This is undesired cause if we run the test again the conflicting instances of the background process will cause another test failure.
This PR attempts to run some cleanup code when dropping `NamadaBgCmd` to kill the task.   
=> Attempt to kill bg process in tests

.changelog/unreleased/bug-fixes/3860-serde-rename-batch-index.md, crates/sdk/src/masp/utilities.rs
=> feat: serde rename batch index into masp tx index

.changelog/unreleased/improvements/3899-get-validators-livenesses.md, crates/proof_of_stake/src/storage.rs, crates/proof_of_stake/src/types/mod.rs, crates/sdk/src/queries/vp/pos.rs, crates/sdk/src/rpc.rs
Hello, I'm Jeongseup from Cosmostation. I hope the Namada mainnet genesis launch is successful. 
I believe it would be beneficial for each validator to monitor their own liveness(uptime) status during the current epoch to prevent slashsing or other penalties. 
Therefore, I have implemented a new RPC query function that retrieves the liveness status of validators who are active in this epoch. 
=> feat: Add new rpc query function to check validators' liveness(uptime)

crates/node/src/shell/testing/node.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/masp.rs
Updates `assert_success` in integration tests to avoid ignoring missing results.
Fixes wrong usage of the same function in conjunction with `Client` commands that don't modify the auxiliary fields of `InnerMockNode`.
=> Fix integration tests assertions

.changelog/unreleased/testing/3840-masp-tests.md, crates/shielded_token/src/vp.rs, crates/tests/src/integration/masp.rs
Partially addresses #3836.
Partially addresses #3828.
Adds more integration test for the MASP including some tests with tx batches.
Adds some protests for the MASP vp.
=> Masp tests

.changelog/unreleased/testing/3924-testing-core-signing.md, crates/sdk/src/signing.rs, crates/wallet/src/lib.rs
Increase code coverage in crats/core/signing.rs
=> Increasing code coverage in sdk/signing

.changelog/unreleased/improvements/3928-improve-gas-msgs.md, crates/node/src/protocol.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs
Improves the gas error messages we emit from mempool validation and process proposal.
Adds two new unit tests.
=> Improve gas messages

crates/shielded_token/src/vp.rs
=> Adds comment for masp assets' epoch

.changelog/unreleased/improvements/3940-small-tings.md, crates/apps_lib/src/client/rpc.rs, crates/governance/src/cli/validation.rs, crates/proof_of_stake/src/error.rs, crates/proof_of_stake/src/rewards.rs, crates/sdk/src/queries/vp/token.rs, crates/sdk/src/rpc.rs, crates/tests/src/integration/ledger_tests.rs, genesis/hardware/parameters.toml, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
- Closes #3927 
- uses `max_block_gas = 15_000_000` in testing
- fixes an `UnbondError` variant message
- Query latest PoS inflation rate in addition to staking rewards rate
=> Small misc fixes

.changelog/unreleased/improvements/3956-adjusted-gas-prices.md, crates/benches/process_wrapper.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs, crates/sdk/src/lib.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/integration/ledger_tests.rs, crates/tests/src/integration/masp.rs, genesis/hardware/parameters.toml, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
Updates genesis local files with the most update values for mainnet. Updates the `DEFAULT_GAS_LIMIT` in the sdk. Corrects tests.
=> Updated gas

.changelog/unreleased/bug-fixes/3959-fix-masp-change.md, crates/apps_lib/src/cli.rs, crates/core/src/masp.rs, crates/core/src/token.rs, crates/core/src/uint.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/tx.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/shielded_token/src/storage.rs, crates/tests/src/integration/masp.rs
~~Based on #3954 ([DIFF](https://github.com/anoma/namada/compare/murisi/fix-masp-change..tiago+murisi/fix-masp-change))~~
Rebases commits from #3954, therefore it essentially supersedes it.
This PR accomplishes the following:
- Fixes clippy lints
- Fixes formatting
- Adds new storage functions to update the masp token map
- Adds a new masp integration test to check the behavior of enabling rewards on some asset that had already been shielded
- Adds a new masp integration test to check the behavior of interacting with tokens in the masp whose values span across multiple notes (because to represent them we need more than 64 bits)
- Adds a new masp integration test to check the behavior of initializing the token map with null rewards, shielding, then updating the rewards to some non-null …
=> Test enabling rewards after shielding and large amounts in the masp

.changelog/unreleased/improvements/3969-remove-custom-tx-arg.md, crates/apps_lib/src/cli.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/tx.rs
=> Removes `disposable-gas-payer` arg for custom txs

.changelog/unreleased/miscellaneous/3971-make-build-in-release.md, Makefile
closes #3950
The `make build` recipe now builds in release. Use `make build-debug` for a dev build.
=> make: change "make build" recipe to build in release

.changelog/unreleased/bug-fixes/3979-restore-purged-commits.md, crates/apps_lib/src/cli.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/masp.rs
Restore commits accidentally purged from #3959 (more specifically, acafd29516a90b1b3705c568781ef066ffc1e591)
=> Enforce gas spending key usage with disposable gas payers

.changelog/unreleased/bug-fixes/3971-fix-config-from-env.md, Cargo.lock, Cargo.toml, crates/apps_lib/src/config/mod.rs
fixes #3953
The config-rs prefix separator behavior had a regression introduced after 0.11 https://github.com/rust-cli/config-rs/issues/291 where instead of the previous single underscore prefix separator it was using the field separator with double underscore. The fix was introduced in https://github.com/rust-cli/config-rs/pull/292 that allows to specify prefix separator.
=> fix config from env var

.changelog/unreleased/improvements/3983-improve-masp-fee-messages.md, crates/node/src/protocol.rs, crates/node/src/shell/process_proposal.rs
Closes #3961.
Partially addresses #3964.
Improves the error logs of masp fee payment.
`try_masp_fee_payment` now short circuits and returns error on all failures (not only gas ones) avoiding the need for an extra `Option` in the returned type. This allows for a better logging of the failures to the user and makes the code simpler to follow.
=> Reworks masp fee payment error handling

.changelog/unreleased/testing/3982-test-unshields-multiple-digits.md, crates/tests/src/integration/masp.rs, genesis/hardware/parameters.toml, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
- Increase masp fee payment gas limit to `65000`
- Test NAM reward unshields in `values_spanning_multiple_masp_digits`.
=> Test NAM reward unshields in `values_spanning_multiple_masp_digits`

.mergify.yml
=> mergify: update backporting for maint-0.45 branch

about.toml
Fixes `cargo about` failing in release builds on licenses from ring crate
=> about: add new required license from ring crate

.github/workflows/ci.yml
=> CI: run on maintenance branches prefixed with "maint-"

.changelog/unreleased/improvements/4003-better-masp-balance-errors.md, crates/sdk/src/tx.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/shielded_wallet.rs
Improves MASP related SDK errors, namely insufficient balance errors.
=> Improve MASP sdk errors

.changelog/unreleased/improvements/4016-ss-ledger-client-improvements.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/masp.rs, crates/core/src/control_flow/time.rs, crates/node/src/bench_utils.rs, crates/sdk/src/args.rs, crates/sdk/src/masp/utilities.rs, crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
The shielded sync's ledger client continues to perform poorly, even after #3578. This PR introduces some optimizations to the ledger client, and improves its UX a bit.
- Fetches are now logged more frequently on the progress bar. Previously, they weren't being logged because concurrent fetches were starving each other on the first semaphore. To fix this, `fetch_shielded_transfers` now has a single semaphore point, at the top of the method, rather than two.
- Errors returned from RPC servers are no longer printed. They weren't that helpful anyway, and were spamming the screen, obfuscating the output of the progress bars.
- A linear backoff sleep has been added to the ledger client, on errors, to allow the client to recover from potential rate limiting/throttling imposed by the CometBFT RPC …
=> Improve the performance of the shielded sync ledger client

.changelog/unreleased/improvements/4004-gas-failure-error-improvements.md, crates/gas/src/lib.rs, crates/node/src/protocol.rs, crates/node/src/shell/mod.rs, crates/tests/src/native_vp/pos.rs
=> Added more info to gas errors

.changelog/unreleased/docs/4006-fix-cometbft-install-link.md, README.md
Updates the broken CometBFT installation guide link in README.md from `/docs/guides/install.md` to `/docs/tutorials/install.md` to ensure users can properly access the installation instructions.
Fixes #4006
- N/A - documentation change only
- Relevant PR if applies: N/A - README.md change only
- Relevant PR if applies: N/A - README.md change only
=> docs: Fix broken CometBFT installation guide link

.changelog/unreleased/testing/3925-test-malleability-attacks.md, crates/apps_lib/src/client/tx.rs, crates/light_sdk/src/writing/asynchronous/mod.rs, crates/light_sdk/src/writing/blocking/mod.rs, crates/node/src/protocol.rs, crates/node/src/shell/block_alloc.rs, crates/node/src/shell/block_alloc/states.rs, crates/node/src/shell/finalize_block.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs, crates/sdk/src/lib.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/test_utils/src/lib.rs, crates/tx/src/data/mod.rs, crates/tx/src/data/wrapper.rs, crates/tx/src/types.rs, wasm_for_tests/Cargo.lock, wasm_for_tests/Cargo.toml, wasm_for_tests/Makefile, wasm_for_tests/vp_verify_signature/Cargo.toml, wasm_for_tests/vp_verify_signature/src/lib.rs
- Adds property tests for malleability attacks on transactions
- Improves `test_wrapper_unknown_address`
- Removes old references to encrypted/decrypted txs
=> Test malleability attacks

.changelog/unreleased/improvements/4043-prune-more-subtree-snapshots.md, crates/node/src/storage/mod.rs, crates/node/src/storage/rocksdb.rs, crates/state/src/wl_state.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs, wasm_for_tests/Cargo.lock
The old Merkle tree snapshots for `NoDiff` and `CommitData` don't need to be saved.
The storage space was occupied by `NoDiff` Merkle tree snapshots.
This PR prunes the previous snapshots at every block commit.
- `prune_merkle_tree_stores` prunes subtree snapshots which are saved every block
- Other snapshots which are saved every epoch are pruned as before
- `read_merkle_tree_stores` returns incomplete Merkle tree if the store type isn't specified i.e. if it is requested to restore all subtrees. (When the store type is specified, it returns an error if the store type snapshot doesn't exist.) `get_merkle_tree` will rebuild the incomplete subtrees.
=> Prune more Merkle tree snapshots

.changelog/unreleased/improvements/4047-fix-help-msgs.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/args.rs
Closes #4022.
Adds a call to `arg_required_else_help` for `TxCustom`, `TxInitAccount` and `QueryFindValidator` to print the command's help message when no arguments are provided.
Modified `QueryFindValidator` to carry a single address instead of two and updated the logic of `query_find_validator` to account for this.
=> Fix client missing help messages

.changelog/unreleased/improvements/4018-update-witness-map-on-spend.md, crates/shielded_token/src/masp/shielded_sync/dispatcher.rs, crates/shielded_token/src/masp/shielded_wallet.rs
Avoid updating merkle paths of spent notes. This should optimize the synchronous path of the shielded sync on the ledger client.
=> Avoid updating merkle paths of spent notes

genesis/hardware/parameters.toml, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
Updates the `masp_fee_payment_gas_limit` in the genesis files to match the one proposed for mainnet.
=> Updates masp gas limit in genesis files

.changelog/unreleased/bug-fixes/4055-wrap-tx-by-elsewho.md, crates/apps_lib/src/cli.rs, crates/sdk/src/signing.rs, crates/tests/src/integration/ledger_tests.rs
=> wrap tx by elsewho

.changelog/unreleased/improvements/4021-dryrun-fixups.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/rpc.rs, crates/proof_of_stake/src/rewards.rs, crates/sdk/src/tx.rs
- Closes #4014.
- Fixes `namadac query-proposal` without `--proposal-id` flag
=> Fixups learned from dry-run

.changelog/unreleased/improvements/4039-adjust-tx-response-output.md, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/tests/src/e2e/ibc_tests.rs
Closes #4020.
`display_batch_resp` now logs some information at the batch level followed by the results of the single inner txs. In case of `OtherFailure` we only print the error message for that specific failure instead of the entire tx result.
=> Improve tx result message

.changelog/unreleased/bug-fixes/4061-dump-reveal-pk.md, crates/apps_lib/src/client/tx.rs
It is currently not possible to generate the `reveal_pk` transaction offline. This PR will dump the transaction when requested. 
=> dump tx output for reveal_pk transactions when requested

.changelog/unreleased/bug-fixes/3960-memo-validation-in-vp.md, crates/core/src/hash.rs, crates/node/src/protocol.rs, crates/sdk/src/lib.rs, crates/tests/src/integration/masp.rs, crates/vp_prelude/src/lib.rs, wasm/vp_implicit/src/lib.rs, wasm/vp_user/src/lib.rs, wasm_for_tests/tx_proposal_token_gas/src/lib.rs, wasm_for_tests/vp_verify_signature/src/lib.rs
Extended the `VerifySigGadget` to also check the integrity of the memo section (if present). Added wasm tests to cover this scenario.
=> Memo integrity check in validity predicates

.changelog/unreleased/improvements/4083-log-implicit-vp.md, crates/apps_lib/src/client/rpc.rs
Updates `query-protocol-parameters` to display some missing params. Also refactored it to reconstruct the `Parameters` type to ensure we don't miss any.
=> Updates `query-protocol-parameters` to display some missing params

.changelog/unreleased/improvements/4071-narrow-shielding-retry-logic.md, crates/apps_lib/src/client/tx.rs
Closes #4045.
Ensures that the retry logic for a failed shielding tx hitting an epoch boundary is applied only when the MASP vp is the only one rejecting the tx and the error is among the expected ones.
=> Narrow down shielding retry logic

crates/shielded_token/src/masp/shielded_wallet.rs
=> Adds debug trace for masp epochs in asset types

.changelog/unreleased/bug-fixes/4116-comet-genesis-validator-set.md, crates/node/src/tendermint_node.rs
Closes #4096
Only writes a dummy validator to CometBFT's genesis if the number of validators present is lower than 2.
=> Add a single CometBFT dummy validator

.mergify.yml
- Updated libs PRs backporting rule with the `"libs-"` prefix
- Added a rule for backporting apps PRs
=> mergify: add apps backport rules, add prefix for libs

.github/workflows/ci.yml
- Run CI in PRs targetting maint-libs branch
=> ci: run on maint-libs PRs

.changelog/unreleased/CI/4140-ledger-namada-unit-tests-ci.md, .github/workflows/ci.yml, crates/ibc/src/lib.rs, crates/sdk/src/lib.rs, crates/sdk/src/signing.rs
An attempt to add Ledger app unit tests to the Namada CI. These tests were created to complement the Ledger app E2E tests already in the CI at `test-e2e-with-device-automation`. Whereas the E2E tests comprehensively cover testing hardware wallet signing for a few cases, these unit tests focus on covering hardware wallet printing for hundreds of cases. More specifically, the following changes have been made:
* Made the CI automatically generate random transaction test vectors using the Namada client
* Doing this has the side benefit of preventing code rot in the test vector generation code
* The CI then runs the Ledger app unit test code on the generated test vectors
* Doing this helps automatically detect compatibility breaking changes in the transaction serializations
* Fixed regressions …
=> Add Ledger app unit tests to the Namada CI

.github/workflows/ci.yml
The image contains `cargo` (as missing here https://github.com/anoma/namada/actions/runs/12213873245/job/34073974397)
=> ci/test-ledger-app: specify container image

crates/ibc/src/lib.rs
fixes a panic in strategy when a list of generated token IDs is not unique (as seen in https://github.com/anoma/namada/actions/runs/12213873245/job/34074078139)
=> test/ibc: ensure unique token IDs

Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> deps: use published ethbridge crates

.changelog/unreleased/improvements/4205-improve-next-epoch-info.md, crates/apps_lib/src/client/rpc.rs, crates/core/src/time.rs, crates/sdk/src/rpc.rs
For example, currently on mainnet with `v1.0.0`:
```
Last committed block height: 269035, time: 2024-12-25T09:35:13.291756821+00:00
Current epoch: 87.
First block height of this epoch 87: 268949.
Minimum number of blocks in an epoch: 2700.
Minimum amount of time for an epoch: 21600 seconds.
Earliest height at which epoch 88 can begin is block 271649.
```
And with the changes:
```
Last committed block height: 269044, time: 2024-12-25T09:36:15.592519345+00:00
Current epoch: 87.
First block height of epoch 87: 268949.
Minimum number of blocks in an epoch: 2700.
Minimum amount of time for an epoch: 6h-0m-0.
Next epoch (88) begins in 5h-49m-0s or at block height 271649, whichever occurs later.
```
- Relevant PR …
=> Improve `namadac next-epoch-info`

.changelog/unreleased/bug-fixes/4146-fix-masp-rewards-estimate.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/args.rs, crates/shielded_token/src/conversion.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/masp.rs
Various adjustments to the masp rewards estimation logic:
- Fixed the logic to correctly account for rewards accrued by the native token and by assets that have been shielded in the current epoch (for which no conversions are available yet but the conversion from the previous epoch can be used as an estimate)
- Fixed the logic to allow estimating rewards for assets that have been shielded before the last epoch
- Changed the API of the estimate function to require a `ValueSum` instead of a viewing key (this is to support a UI view with the possible rewards for different tokens, cc @ChrisHoltDesign, @mateuszjasiuk)
- The function now returns a `DenominatedAmount` instead of an `i128`
- Changed the name of the cli command to `estimate-shielding-rewards`
- Updated and improved tests
- This …
=> Fix masp rewards estimate

.changelog/unreleased/bug-fixes/4224-fix-apps-version-fallback.md, Cargo.lock, Cargo.toml, crates/apps_lib/Cargo.toml, crates/apps_lib/build.rs, crates/systems/Cargo.toml
When there's no `.git` dir the build script falls back to get the version string from cargo. This should use the metadata of the apps crate, but instead it was using the workspace version, which contains version used for libs.
=> fix apps version fallback

scripts/make-package.sh
fixes `[ERROR] cargo-about should not redirect its output in powershell, please use the -o, --output-file option to redirect to a file to avoid powershell encoding issues`
=> fix make-package.sh to work on windows

.changelog/unreleased/SDK/4234-offline-sigs-in-sdk.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/utils.rs, crates/sdk/src/args.rs, crates/sdk/src/signing.rs
This PR moves the offline signing logic from the client to the SDK.
Also removes some remaining traces of  `SignTx` which is a duplicated of `OfflineSign` (I had already started removing it in #4120 but forgot to remove everything).
I've also opened #4235 with some followup tasks on this topic.
cc: @jurevans
=> Offline signatures from SDK

.changelog/unreleased/improvements/4241-client-staking-rewards-query.md, crates/apps_lib/src/client/rpc.rs
When the PoS inflation is 0 the client printed `PoS inflation and rewards are not currently enabled.` assuming it's not enabled. This PR adds additional query to print last staked ratio which may cause the inflation to go to 0 when its over the `target_staked_ratio` and changes the message to `No PoS inflation and rewards tokens were minted.` that can apply to either case.
=> client: print last stake ration and improve msg on zero inflation

.github/workflows/release.yml, Cargo.lock, Cargo.toml, Makefile
Switched back to upstream version of rocksdb and avoids enabling jemalloc feature in windows release build.
Tested in https://github.com/anoma/namada/actions/runs/12812138436 (though I broke `make-package.sh` earlier in unrelated change - fixed in #4243)
=> build with no jemalloc on windows

.changelog/unreleased/bug-fixes/4251-ibc-for-maspless-hw.md, crates/apps_lib/src/client/tx.rs
Pure IBC transaction signing currently fails on the Ledger Nano S. This is because it tries to use the hardware wallet to generate MASP build parameters even when they are not needed. This PR modifies the code to ignore MASP build parameter generation failures if they turn out to not be needed for the construction of an IBC transaction.
An alternative approach to this PR could be to determine the precise conditions under which MASP build parameters would be required, and only do generation in those circumstances. This also would work fine, but would involve making sure that the determined conditions do not fall out of sync with the transaction building code that follows its usage.
=> Support IBC signing on hardware wallets not supporting MASP

.changelog/unreleased/features/4082-ibc-pfm.md, .github/workflows/scripts/e2e.json, Cargo.lock, Cargo.toml, crates/benches/native_vps.rs, crates/ibc/Cargo.toml, crates/ibc/src/context/common.rs, crates/ibc/src/context/mod.rs, crates/ibc/src/context/nft_transfer_mod.rs, crates/ibc/src/context/pfm_mod.rs, crates/ibc/src/context/token_transfer.rs, crates/ibc/src/context/transfer_mod.rs, crates/ibc/src/context/validation.rs, crates/ibc/src/lib.rs, crates/ibc/src/vp/mod.rs, crates/tests/Cargo.toml, crates/tests/src/e2e/helpers.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/setup.rs, crates/tx_prelude/src/ibc.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Integrate with the [Packet Forward Middleware] code. Requires an [`ibc-rs` fork], in order to support asynchronous IBC packet acknowledgements.
**NOTE:** The code in the links above should also be reviewed.
[Packet Forward Middleware]: https://github.com/heliaxdev/ibc-middleware/tree/pfm/v0.6.0/crates/packet-forward
[`ibc-rs` fork]: https://github.com/heliaxdev/cosmos-ibc-rs/tree/aa229566e6bb688cc2626dab276c3849abc0c583
=> IBC Packet Forward Middleware

.changelog/unreleased/bug-fixes/4245-fix-tm-mode.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/config/mod.rs, crates/apps_lib/src/tendermint_node.rs, crates/node/src/lib.rs
closes #4139
The PR adds a new field in config `last_tendermint_mode` (non-breaking as it's optional) which will be persisted on node start-up. If the mode changes from validator to non-validator, the node will backup and replace the validator key and state in the CometBFT dir.
=> avoid running cometbft as a validator when tendermint_node is set to non-validator

.changelog/unreleased/bug-fixes/4264-fix-redeleg-err.md, crates/sdk/src/error.rs, crates/sdk/src/tx.rs
closes #4263
The args for `IncomingRedelIsStillSlashable` error were swapped. Also added the earliest redelegation epoch to help users determine when they can redelegate again.
=> PoS: fix and improve chained redelegation error msg

.changelog/unreleased/improvements/4271-masp-fee-error-msg.md, crates/node/src/protocol.rs, crates/node/src/shell/process_proposal.rs
Closes #4262.
This PR tries to improve the error message we emit in case of a failed masp fee payment by better explaining the logic applied by the protocol
=> Improve error message on failed fee payment

.mergify.yml
=> ci/mergify: update for maint-1.1 and maint-libs-0.47

.changelog/unreleased/improvements/4218-normal-mode-display-tx-fees.md, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/sdk/src/lib.rs, crates/sdk/src/signing.rs
Updated the test vector generator to require the hardware wallet to display wrapper transaction fees in normal mode. See attached the test vectors (which show what the hardware wallet will be required to display) resulting from this change: [testvecs.json](https://github.com/user-attachments/files/18320129/testvecs.json) . This PR should not be merged before hardware wallet normal mode fee display support is implemented because that would cause the hardware wallet CI tests in this Namada repository to fail.
=> Display transaction fees in normal mode

.changelog/unreleased/CI/4286-fix-ci-udev-dep.md, .github/workflows/ci.yml
Ensure that `libudev-dev` is installed by the CI before trying to generate test vectors in `test-ledger-app`. This addresses the issue that appeared only after merging https://github.com/anoma/namada/pull/4218 . See https://github.com/murisi/namada/actions/runs/13067326899/job/36461810196?pr=2 for a successful run of this fix.
=> Make sure the CI installs libudev-dev before building Namada.

.changelog/unreleased/testing/4289-multisig-tests.md, crates/tx/src/types.rs
Adds a few more cases to the multisig unit test aimed at covering some possible misbehaviors by one of the participants in the multisig account.
=> More multisig tests

.changelog/unreleased/improvements/4247-bump-ibc-rs.md, Cargo.lock, Cargo.toml, clippy.toml, crates/ibc/src/actions.rs, crates/ibc/src/context/client.rs, crates/ibc/src/context/common.rs, crates/ibc/src/context/execution.rs, crates/ibc/src/context/middlewares/pfm_mod.rs, crates/ibc/src/context/middlewares/shielded_recv.rs, crates/ibc/src/context/nft_transfer.rs, crates/ibc/src/context/nft_transfer_mod.rs, crates/ibc/src/context/token_transfer.rs, crates/ibc/src/context/transfer_mod.rs, crates/ibc/src/context/validation.rs, crates/ibc/src/event.rs, crates/ibc/src/lib.rs, crates/ibc/src/nft.rs, crates/ibc/src/vp/mod.rs, crates/node/src/bench_utils.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs, crates/storage/src/error.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/setup.rs, crates/tests/src/vm_host_env/ibc.rs, crates/tests/src/vm_host_env/mod.rs, crates/tx/build.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
NOTE: Need to update ibc-middleware with the release version
Mainly updated error types of `ibc-rs`. No logic should be changed.
=> Upgrade ibc-rs to v0.57

.changelog/unreleased/improvements/4299-up-cometbft.md, Dockerfile, README.md, scripts/get_cometbft.sh
=> update recommended CometBFT to 0.37.15

.changelog/unreleased/improvements/4307-modified-modified-zip32.md, crates/apps_lib/src/cli/wallet.rs, crates/wallet/Cargo.toml, crates/wallet/src/derivation_path.rs, crates/wallet/src/lib.rs
=> wallet: change the derivation path for modified ZIP32

.changelog/unreleased/improvements/4282-test-vectors-with-chain-ids.md, crates/sdk/src/signing.rs
An attempt to address #4282 by displaying the chain ID of the transaction in expert mode. The chain ID is still not printed in normal mode because too much information is already being displayed there. See attached what the test vectors would look like after this change:  [testvecs-formatted.json.gz](https://github.com/user-attachments/files/18672175/testvecs-formatted.json.gz) for the JSON output and [testdbgs.txt.gz](https://github.com/user-attachments/files/18672177/testdbgs.txt.gz) for the debug formatting.
=> Print the transaction's chain ID in expert mode.

.changelog/unreleased/improvements/4283-pos-claim-rewards-events.md, crates/proof_of_stake/src/lib.rs
Emit a token transfer emit with `"pos-claim-rewards"` descriptor when claiming non-zero staking rewards.
An update to a live chain with this change can be applied via a gov proposal replacing the `tx_claim_rewards` wasm
=> PoS claim rewards - add token transfer event

.changelog/unreleased/improvements/4347-tx-result-events.md, crates/sdk/src/tx.rs
Print events emitted by a tx, if any.
Example output of `namadac tx-result`:
```
Checking if tx ADCB491136F8699069A816F15111FFA984B5B768E886E077A911C00AB16BD439 is applied...
Transaction batch ADCB491136F8699069A816F15111FFA984B5B768E886E077A911C00AB16BD439 was applied at height 580.
Batch results:
Transaction DE55BEA23344962AFB8161CF73D3D8B026DD712AFBA73DC523A2FFE4DE5B0770 was successfully applied.
Events:
- tx - token/transfer:
- post-balances: [[["internal-address/tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j2fp","tnam1qxgfw7myv4dh0qna4hq0xdg6lx77fzl7dcem8h7e"],"100000000096"],[["internal-address/tnam1qyczahj5gmtsv694q2wngsl00qjpyxyyrsrtq5yk","tnam1qxgfw7myv4dh0qna4hq0xdg6lx77fzl7dcem8h7e"],"1900075012169"]]
- source-accounts: [[["internal-address/tnam1qgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqc8j …
```
=> sdk/tx-result: print tx events if any

crates/tx/build.rs, crates/tx/src/proto/generated.rs
This fixes an issue raised during publishing of namada_tx crate (caught by verification introduced from https://github.com/rust-lang/cargo/issues/5073)
=> tx: build tonic artifacts into OUT_DIR

crates/apps_lib/build.rs, crates/apps_lib/src/cli.rs
=> apps_lib: output artifacts from build script into OUT_DIR

scripts/release_bins.sh, scripts/release_libs.sh
This makes it easier to cherry-pick changelogs from maintenance releases into main
=> keep a separate commit for release changelogs

Cargo.lock, crates/apps/Cargo.toml, crates/apps/build.rs, crates/apps/src/bin/namada-client/main.rs, crates/apps/src/bin/namada-node/cli.rs, crates/apps/src/bin/namada-relayer/_main.rs, crates/apps/src/bin/namada-wallet/main.rs, crates/apps/src/bin/namada/cli.rs, crates/apps/src/lib.rs, crates/apps_lib/Cargo.toml, crates/apps_lib/src/cli.rs, crates/node/src/lib.rs, crates/node/src/tendermint_node.rs
fixes namada_node release that is not able to access namada_apps manifest as it's not in its build tree:
```
error: failed to run custom build command for `namada_apps_lib v0.47.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
process didn't exit successfully: `/namada/target/package/namada_node-0.47.1/target/debug/build/namada_apps_lib-5075df52883ad4e6/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=../../.git
```
The build script is moved into the apps crate to use its own manifest and hence avoid this issue
=> move version detection build script from apps_lib into apps

.changelog/unreleased/improvements/4282-test-vectors-with-chain-ids.md, .github/workflows/ci.yml, crates/sdk/src/signing.rs
An attempt to address #4282 by displaying the chain ID of the transaction in expert mode. The chain ID is still not printed in normal mode because too much information is already being displayed there. See attached what the test vectors would look like after this change:  [testvecs-formatted.json.gz](https://github.com/user-attachments/files/18672175/testvecs-formatted.json.gz) for the JSON output and [testdbgs.txt.gz](https://github.com/user-attachments/files/18672177/testdbgs.txt.gz) for the debug formatting.
=> Print the transaction's chain ID in expert mode. (re-opened from #4332 after revert)

.changelog/unreleased/improvements/4230-remove-duplicated-sigs.md, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs, crates/tx/src/section.rs, crates/tx/src/types.rs
Closes #4203.
This PR modifies adds a new method on the `Tx` type to remove duplicated sections. This function is then called in the signing function before producing the wrapper signature (which is computed on all the sections) and the `dump_tx` function (in case the dumped tx needed to be signed offline).
To support this logic the `PartialEq` implementation for the `Authorization` type is now manually provided and ignores the way the signer is specified, focusing instead on the targets and the actual signature.
As a side note, also the `PartialEq` implementation for `SigningTxData` has been updated to account for the shielded hash.
=> Avoid duplicated signatures when building transactions

.changelog/unreleased/improvements/4371-versioning.md, VERSIONING.md
=> add VERSIONING.md

crates/apps/release.toml
Updates the release config to allow publishing on the binaries crate
=> apps: allow to publish namada_apps to crates.io

.changelog/unreleased/bug-fixes/4403-fix-crates-build.md, Cargo.lock, crates/governance/Cargo.toml, crates/proof_of_stake/Cargo.toml, crates/wallet/Cargo.toml
In #4401 it was found that some crates released in 0.47.2 fail to build with certain features. To be able to run #4401 check reliably the baseline (i.e. last release it's comparing the API with) has to be fixed first.
=> fix crates build with some non-default features

.changelog/unreleased/testing/3890-hw-masp-auto-test.md, .github/workflows/ci.yml, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/hw_wallet_automation.rs
Adds a device automation for MASP e2e test to run in the CI.
Depends-On: #3797
=> hw masp auto test

.github/workflows/pr.yml
A new CI step "PR: can-backport" checks API compatibility of the libs against the last release (v0.47.2) and if there are API breaking changes requiring major release it will label the PR with "breaking:api", otherwise it will label it to "backport-libs-0.47" for a minor release.
Note that currently the semver-checks step fails because of couple build issues with various feature flags in libs-v0.47.2 that are fixed in here in the last 3 commits.
=> ci: check if a PR can be backported

.changelog/unreleased/testing/4418-fix-hw-speculative_context.md, crates/tests/src/integration/masp.rs
Fixed the `speculative_context` integration test for the hardware wallet by ensuring that the `--use-device` flag is applied to its commands when the environment variable `NAMADA_E2E_USE_DEVICE=true`.
=> Fixed the `speculative_context` integration test for the hardware wallet.

.github/workflows/pr.yml
fix the failing CI job to lock deps versions as one of the new ones requires rust edition2024
=> ci/pr: lock msrv deps versions

.changelog/unreleased/miscellaneous/4378-up-rocksdb.md, .github/workflows/pr.yml, Cargo.lock, Cargo.toml, crates/node/src/shims/abcipp_shim.rs, crates/node/src/storage/rocksdb.rs, crates/tests/src/integration/ledger_tests.rs
Updated rust-rocksdb dependency to v0.23 which uses RocksDB (C++) 9.9.3.
=> deps: update rocksdb

.changelog/unreleased/improvements/4369-increase-masp-minting-accuracy.md, crates/shielded_token/src/conversion.rs, crates/tests/src/integration/masp.rs
This PR is an attempt to slightly mitigate https://github.com/anoma/namada/issues/4372 by reducing the amount of unclaimable rewards created by the rewards algorithm. The approach taken is to try and reduce the amount of NAM minted for non-native tokens so that it's closer to what can actually be claimed. And this reduction is achieved by minting NAM based on the deflated rewards for non-native tokens (which is what is actually put into the allowed conversions) rather than the inflated rewards they are based on. Because clients can combine (deflated) reward NAM[0] with pre-existing NAM[0] in their balance to meet the threshold for conversion to the current epoch and because the distribution algorithm now works with deflated amounts, it no longer ignores the dust arising during the mint …
=> Increase the accuracy of rewards by minting based on the real reward.

crates/sdk/src/lib.rs
I'm doing some things with the Namada SDK and this seems like it would be useful to me.
=> Make `native_token` of `NamadaImpl` public

.github/workflows/pr.yml, Cargo.lock, Cargo.toml
follow-up to #4378 to enable a new feature to restore 0.22 build behaviour
=> enable rocksdb bindgen-runtime by default

.changelog/unreleased/improvements/4445-generate-whitelisted-addresses.md, .github/workflows/ci.yml, crates/core/src/address.rs, crates/sdk/src/lib.rs, crates/sdk/src/signing.rs, crates/token/src/lib.rs, crates/token/src/tx.rs, examples/generate_txs.rs
Adjusted the test vector generator so that it also sometimes generates tokens from the current hardware wallet whitelist. The purpose of this PR is to test hardware wallet functionality regarding printing tokens with known tickers. The following mapping is being used:
* NAM - `tnam1q9gr66cvu4hrzm0sd5kmlnjje82gs3xlfg3v6nu7`
* uOSMO - `tnam1p5z8ruwyu7ha8urhq2l0dhpk2f5dv3ts7uyf2n75`
* uATOM - `tnam1pkg30gnt4q0zn7j00r6hms4ajrxn6f5ysyyl7w9m`
* uTIA - `tnam1pklj3kwp0cpsdvv56584rsajty974527qsp8n0nm`
* ustOSMO - `tnam1p4px8sw3am4qvetj7eu77gftm4fz4hcw2ulpldc7`
* ustATOM - `tnam1p5z5538v3kdk3wdx7r2hpqm4uq9926dz3ughcp7n`
* ustTIA - `tnam1ph6xhf0defk65hm7l5ursscwqdj8ehrcdv300u4g`
See attached the generated test vectors: [testvecs_formatted.json](https://github.com/user-attachments/files/19072563/testv …
=> Adjusted test vector generator to also generate tokens in whitelist.

.changelog/unreleased/improvements/4472-generalize-amount-comparison.md, crates/core/src/token.rs
Generalized comparison of `DenominatedAmount`s to support the case where the difference between the denominations of the operands exceeds 77 (the maximum power of 10 that can be contained by an unsigned 256-bit integer type). This change is necessary to make proptests that generate arbitrary `DenominatedAmount`s pass in extreme cases.
=> Prevent DenominatedAmount comparison from overflowing.

.changelog/unreleased/improvements/4452-load-conversion-migration.md, crates/sdk/src/migrations.rs
This PR tries to ensure that conversion state migrations are written directly into memory in addition to database storage. This would make conversion state migrations similar to those that happen in the subspace column family, which do already have their values written to both memory and database storage.
This is required because migrations are done after the conversion state is loaded into memory, meaning that the migration conversion state would not have an effect on the shielded rewards algorithm in the currently running `namadan` instance. Furthermore, the conversion state in memory overwrites that in storage when shutting down, meaning that a conversion migration state would never not survive in storage beyond the shutting down of the currently running `namadan` instance. Hence all …
=> Make sure that the conversion state is also written into memory.

crates/ibc/src/context/middlewares/pfm_mod.rs, crates/sdk/src/rpc.rs
This PR implements two of the three recommendations from the Informal Systems audit for shielded swap.
* When querying Osmosis for a route of liquidity pools, we explicitly limit the result to a single one.
* We remove the logic that makes the address parseable as the governance address.
We have not implemented IBC size limits. If we do so, it will be in another PR. However, these are implicitly limited by Namada tx size limits anyways.
=> Informal Systems shielded swaps audit

.changelog/unreleased/bug-fixes/4449-fix-masp-events.md, crates/events/src/extend.rs, crates/node/src/bench_utils.rs, crates/node/src/dry_run_tx.rs, crates/node/src/protocol.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/utilities.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/shielded_sync/dispatcher.rs, crates/shielded_token/src/masp/shielded_sync/utils.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/shielded_token/src/masp/test_utils.rs, crates/tx/src/data/mod.rs, crates/tx/src/event.rs, crates/tx/src/types.rs
Supersedes #4449.
Partially addresses #3824 (removes `ExtendedTxResult`).
Partially addresses #3827 as we take events out of `BatchedTxResult` in case of masp fee payment.
Ensures that events for masp fee payment txs are emitted as soon as the storage changes are committed
- ~https://github.com/anoma/namada-masp-indexer/pull/50~ ->https://github.com/anoma/namada-masp-indexer/pull/64
- https://github.com/anoma/namada-indexer/pull/331
=> Fix masp events [rebase]

.changelog/unreleased/improvements/4423-configurable-masp-precision.md, Cargo.lock, Cargo.toml, crates/migrations/src/foreign_types.rs, crates/shielded_token/src/conversion.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/shielded_token/src/storage_key.rs, crates/tests/src/integration/masp.rs, crates/token/src/lib.rs, examples/make-db-migration.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
An attempt to address https://github.com/anoma/namada/issues/4422 by introducing new storage keys to hold the shielded reward precision for each token and reading that instead of deducting it. More precisely, the changes are as follows:
* Made a new storage key to hold the shielded rewards precision for each token
* The function for obtaining a token's reward precision now reads this new storage key
* And if the storage key is uninitialized, it initializes it using the old algorithm: `10^(max(denom,3)-3)`
* Implements as an example a migration that sets the precision for existing IBC tokens
* Alternatively, for an example of a governance upgrade taking advantage of this PR, see: https://github.com/anoma/namada-governance-upgrades/pull/38 .
This PR should be backwards compatible in the …
=> Allow the shielded reward precision for tokens to be explicitly set.

.changelog/unreleased/improvements/4489-sorted-tx-results.md, crates/tx/src/data/mod.rs
Closes #3873.
Changes the `BTreeSet` of `TxResult` for a `IndexSet` to preserve the order of inner txs' results in the events.
=> Sorted tx results in events

.changelog/unreleased/testing/4491-test-auto-compounding.md, crates/tests/src/integration/masp.rs
Added an integration test to check that the automatic compounding of a shielded account balance is the same as manually compounding a shielded account balance. Here, manual compounding refers to a shielded pool user immediately unshielding shielded rewards they receive (thereby applying/realizing rewards at that point in time) and then reshielding them (with the timestamp of the current MASP epoch). Though this means that different allowed conversions (from the protocol) are now applied onto the automatically and manually compounded accounts, the results of shielded balance queries are expected to be the approximately the same for all MASP epochs.
See the results of compounding a principal amount of 0.1 BTC below:
| Ep.| Auto Compounding | Manual Compounding | Claimable | MASP Balance | …
=> Added integration test for auto-compounding.

.changelog/unreleased/improvements/4457-sdk-override-rewards-target.md, crates/apps_lib/src/cli/client.rs
`namadac epoch` now prints e.g.:
```
Last committed epoch: 2200
Last committed masp epoch: 550
```
=> client: also query and print masp epoch

.changelog/unreleased/improvements/4497-no-duplicated-events.md, .github/workflows/scripts/hermes.txt, crates/apps_lib/src/client/rpc.rs, crates/light_sdk/src/reading/asynchronous/tx.rs, crates/node/src/bench_utils.rs, crates/node/src/protocol.rs, crates/node/src/shell/finalize_block.rs, crates/sdk/src/events/log/dumb_queries.rs, crates/sdk/src/queries/shell.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/tests/src/integration/ledger_tests.rs, crates/tx/src/data/mod.rs
Closes #3827.
Avoid serializing the `events` field of `BatchedTxResult` so that we don't get the same events that we can find in the block results inside every `tx/applied` event.
To achieve this we now attach the tx hash and inner tx hash attribute (introduced in #4454) to the new masp events introduced in #4475: without this change the retrieval of these events based on the transaction's hash alone would be quite convoluted (if not impossible). This change also goes into the direction of #3824: if in the future we were to produce the masp events directly in wasm, we would perfectly match the current structure of the events emitted in protocol (no need for a migration of the events).
The rpc code has also been updated to reconstruct the complete `BatchedTxResult` (with `events`) so that …
=> Remove duplicated events

.changelog/libs-v0.48.3/miscellaneous/4561-ci-workflow-fixes.md, .changelog/libs-v0.48.3/summary.md, CHANGELOG.md
=> Changelog: Release libs 0.48.3

crates/core/CONSENSUS_VERSION, crates/core/build.rs
Adds symlink to `CONSENSUS_VERSION` from workspace root to `crates/core`. This change is needed for publishing `namada_core` to crates.io (I published libs-v0.149.1 using this patch)
=> fix core release by symlinking CONSENSUS_VERSION

.changelog/unreleased/bug-fixes/4580-fix-vm-env-tests.md, crates/tests/Cargo.toml, crates/vm_env/Cargo.toml, crates/vm_env/src/lib.rs
Change ABI to `C-unwind` in `vm_env` when running natively. This fixes tests aborting, instead of unwinding the stack.
=> Change ABI to C-unwind in vm_env when running natively

crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/hw_wallet_automation.rs, crates/tests/src/lib.rs
Trying to see if it has any effect on the flakey test failures:
- disabled unused speculos REST API
- added a speculos cmd wrapper with process clean-up on drop
=> test/e2e: hw-wallet-automation improvements

.changelog/unreleased/bug-fixes/4582-use-correct-ibc-denom-calc.md, crates/ibc/src/trace.rs, crates/sdk/src/args.rs, crates/sdk/src/rpc.rs
=> fix: use correct denom calc for osmosis swaps

.github/workflows/pr.yml
Fixes the can-backport job, which may be affected by PRs previously backported to the lib maint branch. To avoid this issue, the `cargo-semver-checks` is set to use `--baseline-root` directory to the maint branch used as a base so that the previously merged PRs don't affected the results of the PR that's being checked.
Note that I had to switch to a fork of the github action (https://github.com/anoma/cargo-semver-checks-action) as the support for `--baseline-root` is not yet merged upstream (the functionality is implemented but it still needs some tests).
=> CI: fix can-backport

.changelog/unreleased/testing/4566-test-masp-events.md, crates/node/src/shell/testing/node.rs, crates/tests/src/integration/masp.rs
Adds an integration test to check the new masp events: it verifies that the protocol emits these events correctly and that the client can reconstruct the correct shielded state (specifically, the correct order in which the output notes were committed).
Adds an integration test to verify that even in a failing atomic batch the masp fee paying transaction is guaranteed to be committed.
Fixes a minor bug in the integration tests for which arbitrary events were casted to `tx/applied` events.
=> Test masp events

.changelog/unreleased/SDK/4579-map-signing-tx-data.md, crates/apps_lib/src/config/genesis/transactions.rs, crates/sdk/src/signing.rs, crates/tests/src/integration/masp.rs
Closes #4238.
Makes the `public_keys` field of `SigningTxData` a map instead of a vector to ensure uniqueness and simplify some of the logic.
=> Unique public keys for signing

.changelog/unreleased/testing/4540-migrate-wasms.md, Cargo.lock, examples/Cargo.toml, examples/make-db-migration.rs
Implemented hard-fork migration code to update WASM code storage.
=> Implemented logic to update transaction WASMs in hard-fork migration.

.changelog/unreleased/testing/4631-fix-flaky-tricky_masp_txs.md, crates/tests/src/integration/masp.rs
The `tricky_masp_txs` integration test sometimes fails because the epoch transitions happen too quickly. This causes `Transaction`s to be rejected because their asset types are outdated at their time of application. This PR slows down the epochs in `tricky_masp_txs` to make sure that this doesn't happen.
=> Slow down the epochs in tricky_masp_txs.

.changelog/unreleased/improvements/4541-better-masp-fee-payment-vp-err.md, crates/node/src/protocol.rs
Rather than just including the address of the VP rejecting a MASP fee payment, the address and error messages are returned, which are helpful both for users and devs alike.
**This change shouldn't be consensus breaking.**
=> Improve MASP fee payment errors

.changelog/unreleased/improvements/4651-combine-inputs.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/tx.rs, crates/node/src/bench_utils.rs, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/tx.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/masp.rs
This PR vectorizes the processing of shielded transfer inputs to reduce the chances that change is unnecessarily sent back to the sender. More precisely, for a given extended spending key, the required amount is now a (exhaustive) vector of the amounts of each token that are required. This way the note accumulator now has to exceed this vectorial amount before the change computations even begin.
Additionally, analogous to https://github.com/anoma/namada/pull/3459 , this PR supports a CLI where the number of inputs to a transfer do not match the number of its outputs. Furthermore this PR allows for a CLI where transfer inputs and outputs do not occur in balancing pairs.
=> Combined transfer inputs and outputs.

.changelog/unreleased/improvements/4659-soft-limit-tx-transfer-targets.md, crates/token/src/lib.rs, crates/tx_prelude/src/token.rs, wasm/tx_ibc/src/lib.rs, wasm/tx_transfer/src/lib.rs
Limit the number of unique transfer targets (sources + targets) to 20, in `tx_transfer` and `tx_ibc`.
=> Soft limit the number of wasm transfer targets

.changelog/unreleased/bug-fixes/4667-governance-non-native-transfer-fix.md, crates/governance/src/vp/mod.rs, crates/governance/src/vp/pgf.rs, crates/sdk/src/validation.rs
=> pgf/governance disallow non-native transfers

.changelog/unreleased/bug-fixes/4684-fix-gov-gas-cost.md, crates/governance/src/vp/mod.rs
=> fix: remove redundant reads from governance vp

.changelog/unreleased/testing/4573-shielded-rewards-example.md, Cargo.lock, crates/core/src/token.rs, examples/Cargo.toml, examples/shielded_rewards.rs
Wrote a Cargo example that derives constraints on shielded reward parameters in order to ensure that end-users get non-zero rewards. Essentially this example takes the native token supply, incentivisation threshold, target locked amount, and locked amount tolerance and computes bounds on inflation, token precision, and nominal proportional gain sufficient to yield non-zero rewards. See the formulas upon which this example program is based at: https://hackmd.io/oqLHjyvwRMaxSD5JJNrB2w#Setting-parameters-to-ensure-non-zero-rewards . This program can be run with the following command: `cargo run --example shielded-rewards`.
=> Added an example program to derive constraints on shielded reward parameters

.changelog/unreleased/bug-fixes/4695-add-multisig-signature-custom-tx.md, crates/tx/src/types.rs
=> Add custom multisig signature

.changelog/unreleased/improvements/4702-indexer-client-backoff-sleep.md, crates/apps_lib/src/client/masp.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/utilities.rs
Add backoff sleep between MASP indexer client failed requests.
=> Indexer client backoff sleep

.github/workflows/pr.yml, .mergify.yml
=> CI: bump maint version libs-v0.251 and apps-201.0

.changelog/unreleased/improvements/bump-arse-merkle-tree-version-4791.md, Cargo.lock, Cargo.toml
Uses the new published version of our sparse merkle tree that speeds up validation times. This should speed up the time it takes to start a node.
=> Bumping version of arse merkle tree

.changelog/unreleased/improvements/4800-clear-tx-gas-map.md, crates/state/src/wl_state.rs
=> clear the tx gas map after block commit

.changelog/unreleased/bug-fixes/4822-fix-timeout-unlimited.md, crates/ibc/src/vp/mod.rs, crates/tests/src/e2e/ibc_tests.rs
=> Fix timeout refund on an unlimited channel

crates/tests/src/e2e/ledger_tests.rs
=> test/e2e: fix flakey e2e init-validator test

.changelog/unreleased/improvements/4817-change-masp-zk-backend.md, Cargo.lock, Cargo.toml, crates/benches/Cargo.toml, crates/benches/native_vps.rs, crates/node/src/shell/init_chain.rs, crates/sdk/Cargo.toml, crates/shielded_token/src/conversion.rs, crates/shielded_token/src/masp.rs, crates/shielded_token/src/storage_key.rs, crates/shielded_token/src/vp.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
The masp now uses the bellperson backend to synthesize circuits and build zk proofs. Benchmarking this indicates substantial speed ups in proving time.
=> Change MASP zk backend to bellperson

.changelog/unreleased/bug-fixes/4878-update-to-masp-v3.0.6.md, Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
https://crates.io/crates/masp_proofs/3.0.6
This version integrates an updated `nam-bellperson` that fixes issues in wasm, namely the usage of `std::time::Instant`, which has been replaced with `wasmtimer::std::Instant`. It also silences a lot of the `INFO` logs previously sent to the CLI, when generating proofs.
=> Update masp to `v3.0.8`

.changelog/unreleased/improvements/4776-query-conversions-requires-masp-epoch.md, crates/apps_lib/src/client/masp.rs, crates/apps_lib/src/client/rpc.rs, crates/sdk/src/queries/shell.rs, crates/sdk/src/rpc.rs
Querying the conversion state becomes more difficult as nodes progress to higher and higher epochs. For instance, on a mainnet clone running on accelerated epochs, client queries for conversions always timeout (even after modifying `timeout_broadcast_tx_commit`) when the node goes beyond a certain MASP epoch. This happens because the conversion state grows linearly with the MASP epoch counter. This PR attempts to address this problem by making the conversions RPC endpoint require that clients specify the MASP epoch they want conversions from. This implies two things: first the size of the response from the conversions RPC endpoint should now be constant (equal to the number of tokens in the shielded rewards program), and second a client requiring all conversions now has to do a separate …
=> The MASP conversions query now requires a MASP epoch to be specified.

.changelog/unreleased/SDK/4789-no-zero-reward-convs.md, crates/benches/Cargo.toml, crates/benches/native_vps.rs, crates/node/src/bench_utils.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/tests/src/integration/masp.rs
Closes #4789.
Modifies `apply_conversion` to skip conversions that don't carry any rewards (i.e. conversions that only update the epoch of the asset). 
=> Skip conversions with no rewards
