shared/src/types/ethereum_events.rs
This is mostly from PR https://github.com/anoma/namada/pull/229 (relates to issue https://github.com/anoma/namada/issues/140) but wanted to nail it down in this PR.
We will represent the storage keys for wrapped ERC20 tokens like:
```
#EthBridge
/erc20
/0x6b175474e89094c44da98b954eedeac495271d0f
/balances
/atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt 
```
i.e. the ERC20 address is a lower case hex string ("0x6b175474e89094c44da98b954eedeac495271d0f"). Alternatively we could represent it as a checksummed hex string like "0x6B175474E89094C44Da98b954EedeAC495271d0F", in which case we'll need to find a crate to map our `EthAddress` to this.
=> Standardize on a way to represent `EthAddress` in storage keys

.github/workflows/build-and-test.yml
=> run CI on PRs with conflicts

.github/workflows/checks.yml, .github/workflows/docs.yml
follow-up to and based on #346
=> ci: update docs and checks to also run on conflicts

.github/workflows/build-and-test.yml
follow-up to and based on https://github.com/anoma/namada/pull/349
=> ci/build-and-test: add missing ref to PRs on other steps

apps/src/lib/node/ledger/shell/vote_extensions/ethereum_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/validator_set_update.rs
Closes https://github.com/anoma/namada/issues/402
=> Use current epoch's voting powers when compressing validator set updates

documentation/specs/src/interoperability/ethereum-bridge/proofs.md, documentation/specs/src/interoperability/ethereum-bridge/transfers_to_namada.md
=> Fix broken links in the specs

documentation/specs/src/interoperability/ethereum-bridge/bootstrapping.md
Preliminary spec for how the bootstrapping of the bridge could work
Relates to https://github.com/anoma/namada/issues/280
=> Add spec for bootstrapping the Ethereum bridge

apps/src/lib/node/ledger/protocol/mod.rs, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/process_proposal.rs
The ledger wasn't able to propose the genesis block
- let `ProcessProposal` accept genesis blocks without vote extension transactions
- let `FinalizeBlock` accept validator set update protocol transactions
=> Make the ledger accept validator set update protocol transactions

apps/src/lib/wallet/pre_genesis.rs
This is a simple PR that simply fixes the build of the docs generated by `cargo doc`.
=> Fix cargo doc (ethbridge)

documentation/specs/assets/mdbook-admonish.css, documentation/specs/book.toml
Relates to https://github.com/anoma/namada/issues/518
Same as https://github.com/anoma/namada/pull/519 but for `eth-bridge-integration`
=> Enable mdbook-admonish for the specs mdbook (`eth-bridge-integration`)

Cargo.lock, shared/Cargo.toml, shared/src/ledger/ibc/handler.rs, wasm/wasm_source/Cargo.lock
- ibc-rs `yuji/v0.14.0_abciplus` depends on tendermint-rs `bat/abciplus`
- ibc-rs `yuji/v0.14.0_abcipp_rebase_master` depends on tendermint-rs `95c524`
=> update ibc-rs for ethbridge branch

apps/src/lib/node/ledger/shell/vote_extensions.rs
=> Fix cargo doc

apps/src/lib/node/ledger/tendermint_node.rs
Fixes https://github.com/anoma/namada/issues/535
If we can't parse the output of `tendermint version` as a semantic version, log a warning with the raw output rather than panicking
=> Log a warning when an unreleased version of Tendermint is used

apps/src/lib/node/ledger/protocol/mod.rs, shared/src/ledger/ibc/handler.rs, shared/src/ledger/ibc/storage.rs, shared/src/ledger/ibc/vp/denom.rs, shared/src/ledger/ibc/vp/mod.rs, shared/src/ledger/ibc/vp/packet.rs, shared/src/ledger/ibc/vp/token.rs, shared/src/types/address.rs, shared/src/types/token.rs, tests/src/vm_host_env/ibc.rs, tests/src/vm_host_env/mod.rs, vm_env/src/ibc.rs
closes https://github.com/anoma/namada/issues/117
=> support multitoken and relay transfer

documentation/specs/src/interoperability/ethereum-bridge/bootstrapping.md, documentation/specs/src/interoperability/ethereum-bridge/ethereum_smart_contracts.md
Relates to https://github.com/anoma/namada/issues/448
This PR is a preliminary updated spec for how the Ethereum bridge smart contracts will work, covering:
- at a high level, the five contracts that will make up the bridge
- how we store details of controlling validator sets
- transfers of power 
c.f. code/docs in https://github.com/anoma/ethereum-bridge
=> Updated specs for Ethereum bridge smart contracts

apps/src/lib/node/ledger/mod.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shims/abcipp_shim.rs
Based on https://github.com/anoma/namada/pull/534
Completes the first task of issue https://github.com/anoma/namada/issues/563
=> Add event log sender to the Shell

apps/src/bin/anoma-client/cli.rs, apps/src/lib/cli.rs, apps/src/lib/client/rpc.rs
Added a subcommand to query all conversions.
=> Wrote code to print out all conversions.

apps/src/lib/node/ledger/protocol/transactions/validator_set_update/mod.rs, shared/src/ledger/eth_bridge/storage/vote_tallies.rs
=> Remove `'static` lifetime constraint from `Keys`

documentation/docs/src/user-guide/ledger/masp.md
The docs were still in specs mode, considered changing it before testnet launch
=> updated masp docs to actually be docs

.github/workflows/build-and-test-bridge.yml, .github/workflows/build-and-test.yml, .github/workflows/scripts/e2e.json, .github/workflows/scripts/schedule-e2e.py
=> CI: general improvements

apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, apps/src/lib/node/ledger/shims/abcipp_shim.rs, shared/src/ledger/protocol/mod.rs, shared/src/ledger/protocol/transactions/ethereum_events/mod.rs, shared/src/ledger/protocol/transactions/validator_set_update/mod.rs, shared/src/types/transaction/protocol.rs, shared/src/types/vote_extensions.rs, shared/src/types/vote_extensions/ethereum_events.rs, shared/src/types/vote_extensions/validator_set_update.rs
=> Remove protocol tx vote extension digests

documentation/docs/src/testnets/run-your-genesis-validator.md, documentation/docs/src/testnets/running-a-full-node.md, documentation/docs/src/user-guide/install/README.md
=> added chain id and fixed install docs

documentation/docs/src/user-guide/ibc.md
I'd like to update Hermes commit hash and add an explanation for the fee for IBC transactions for Namada v0.13.0.
=> Update doc for IBC relayer

shared/src/ledger/queries/shell/eth_bridge.rs
Once a transfer has timed out or been relayed, we should no longer be able to generate a proof for it. This covers this case with teses.
=> Test expired Bridge pool transfers

apps/src/bin/namada-client/cli.rs, apps/src/bin/namada-relayer/cli.rs, apps/src/bin/namada/cli.rs, apps/src/lib/cli.rs, apps/src/lib/cli/context.rs, apps/src/lib/client/eth_bridge.rs, apps/src/lib/client/eth_bridge/bridge_pool.rs, apps/src/lib/client/eth_bridge/validator_set.rs, apps/src/lib/client/mod.rs, apps/src/lib/client/rpc.rs, core/src/types/eth_abi.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/setup.rs
* Fetch active set of validators.
* Fetch proof of next set of validators.
=> Add validator set update CLI commands

apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
Added some small clarifying doc strings
=> Doc strings for Issue 5 of Eth Bridge Audit

apps/src/lib/node/ledger/shell/prepare_proposal.rs, apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/bridge_pool_vext.rs, apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs
Addresses https://github.com/anoma/namada/issues/239
=> Remove issued at genesis vote extension error

shared/src/ledger/protocol/mod.rs
Simple PR that addresses issue #313 on GitHub.
=> Document all NOOP executions in FinalizeBlock

ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs, ethereum_bridge/src/protocol/transactions/votes/storage.rs, ethereum_bridge/src/protocol/transactions/votes/update.rs, ethereum_bridge/src/storage/vote_tallies.rs, ethereum_bridge/src/test_utils.rs
https://github.com/anoma/namada/issues/693
https://github.com/anoma/namada/issues/181
=> Eth event timeout

apps/src/lib/node/ledger/ethereum_oracle/test_tools/events_endpoint.rs, apps/src/lib/node/ledger/mod.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/e2e/ibc_tests.rs, tests/src/e2e/ledger_tests.rs, tests/src/e2e/setup.rs
Addresses https://github.com/anoma/namada/issues/1055
=> Configure the self-hosted eth events endpoint listen addr

core/src/ledger/storage/mod.rs, core/src/ledger/storage/wl_storage.rs, shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs, shared/src/ledger/native_vp/mod.rs
Undoes the changes introduced by #1193
=> Remove `WlStorageRef`

apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge.rs, apps/src/lib/client/eth_bridge/bridge_pool.rs, apps/src/lib/client/eth_bridge/validator_set.rs, apps/src/lib/node/ledger/abortable.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/mod.rs
Required by https://github.com/anoma/namada/issues/1208
=> Synchronize with Ethereum before performing relays

documentation/specs/src/economics/inflation-system.md
This pr is a minor change on the document file:
https://specs.namada.net/economics/inflation-system.html
I hope it makes the intent a bit more clear.
=> Changing the inflation system documentation to be a bit more clear

Cargo.lock, apps/Cargo.toml, apps/src/lib/cli.rs, apps/src/lib/client/eth_bridge.rs, apps/src/lib/client/eth_bridge/validator_set.rs
https://github.com/anoma/namada/issues/1208
=> Implement a validator set update relayer daemon

ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
=> Handle invalid transfer to Ethereum events

apps/src/lib/node/ledger/shell/vote_extensions.rs, apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
Based on #1301 (review that PR first)
Sign validator set updates from genesis onwards.
=> Validator set updates at genesis

apps/src/lib/node/ledger/shell/finalize_block.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, shared/src/ledger/native_vp/ethereum_bridge/vp.rs, shared/src/ledger/queries/shell/eth_bridge.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/e2e/helpers.rs
Closes https://github.com/anoma/namada/issues/1289
=> Burn ERC20s

core/src/types/storage.rs, ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, ethereum_bridge/src/protocol/transactions/utils.rs, ethereum_bridge/src/protocol/transactions/validator_set_update/mod.rs, proof_of_stake/src/pos_queries.rs, shared/src/ledger/protocol/mod.rs, shared/src/ledger/queries/shell/eth_bridge.rs
Follow-up PR to https://github.com/anoma/namada/pull/1303
Some logic still had to be updated in `FinalizeBlock`.
=> Accept validator set updates from previous epochs (pt. 2)

ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
Closes https://github.com/anoma/namada/issues/1312
=> Time out old Ethereum events before acting on any new events

documentation/docs/src/testnets/running-a-full-node.md
Fixes the old `ANOMA` prefixed env vars
=> Fixes env variable names in docs

documentation/docs/src/user-guide/ledger/staking.md
A PR to contain various updates regarding PoS to the documentation and specs.
Closes #476
=> Update PoS docs and specs

apps/src/lib/client/eth_bridge.rs, apps/src/lib/client/eth_bridge/validator_set.rs, apps/src/lib/client/rpc.rs, apps/src/lib/control_flow/timeouts.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/ethereum_oracle/test_tools/mod.rs
Closes https://github.com/anoma/namada/issues/1348
=> Keep oracle running if the Ethereum node is still available

apps/src/lib/config/genesis.rs, apps/src/lib/node/ledger/shell/mod.rs, core/src/ledger/eth_bridge/storage/mod.rs, core/src/types/ethereum_structs.rs, documentation/specs/src/interoperability/ethereum-bridge/bootstrapping.md, ethereum_bridge/src/parameters.rs, ethereum_bridge/src/test_utils.rs, shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs, shared/src/ledger/native_vp/ethereum_bridge/vp.rs, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/eth_bridge_tests/helpers.rs, tests/src/native_vp/eth_bridge_pool.rs
Closes https://github.com/anoma/namada/issues/1296
=> Oracle start height governance parameter

.changelog/unreleased/improvements/1407-tx-validation-log.md, apps/src/lib/node/ledger/shell/finalize_block.rs, apps/src/lib/node/ledger/shell/process_proposal.rs, apps/src/lib/node/ledger/shell/stats.rs, tests/src/e2e/ledger_tests.rs
Improves error logging.
Prevents double hashing in `SigningTx`
=> Logs validation error in `process_proposal`

apps/src/lib/cli.rs
follow-up to https://github.com/anoma/namada/pull/925
=> cli: add missing `--wallet-alias-force` and `--alias-force`

shared/src/ledger/tx.rs
follow-up to https://github.com/anoma/namada/pull/925
=> shared/tx: fix err variant typos

Cargo.lock, apps/src/lib/client/rpc.rs, apps/src/lib/client/signing.rs, apps/src/lib/client/tx.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, shared/Cargo.toml, shared/src/ledger/eth_bridge.rs, shared/src/ledger/eth_bridge/bridge_pool.rs, shared/src/ledger/masp.rs, shared/src/ledger/rpc.rs, shared/src/ledger/signing.rs, shared/src/ledger/tx.rs, shared/src/types/control_flow.rs, shared/src/types/control_flow/time.rs, shared/src/vm/wasm/compilation_cache/common.rs, tests/src/e2e/eth_bridge_tests.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Closes https://github.com/anoma/namada/issues/1507
=> Refactor timeout logic

Cargo.lock, apps/Cargo.toml, apps/src/bin/namada-relayer/cli.rs, apps/src/lib/cli.rs, apps/src/lib/node/ledger/ethereum_oracle/mod.rs, apps/src/lib/node/ledger/ethereum_oracle/test_tools/mod.rs, apps/src/lib/node/ledger/mod.rs, shared/Cargo.toml, shared/src/ledger/args.rs, shared/src/ledger/eth_bridge.rs, shared/src/ledger/eth_bridge/bridge_pool.rs, shared/src/ledger/eth_bridge/validator_set.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
=> Remove `web30` crate and fix Namada interface Ethereum bridge code

wasm/wasm_source/src/vp_implicit.rs, wasm/wasm_source/src/vp_user.rs, wasm/wasm_source/src/vp_validator.rs
=> fix: wasm unit remove hardcoded vp hash

apps/src/bin/namada-wallet/cli.rs, apps/src/lib/client/tx.rs, apps/src/lib/client/utils.rs, shared/src/ledger/wallet/mod.rs, shared/src/ledger/wallet/store.rs
=> fix: do not panic if the user skips the changes

genesis/e2e-tests-single-node.toml
Fix `proposal submission` e2e test
=> e2e: increase the genesis parameter

scripts/generator.sh
Remove the deprecated `--mode` argument in the generator script.
=> fix: remove deprecated --mode argument in scripts

.github/workflows/build-and-test.yml
Pre download the masp parameters before executing e2e tests.
=> ci: pre-download masp parameters

.github/workflows/scripts/e2e.json, tests/src/e2e/ledger_tests.rs
re-adding a simplified happy-path masp e2e test to cover transfers:
- shielding
- shielded -> shielded
- unshielding
=> test/e2e/ledger_tests: add a happy-path masp txs and queries test

genesis/e2e-tests-single-node.toml
Adds some comments to the e2e toml that can improve migration to testnet tomls
Branched of `base`
=> just some more comments in the e2e toml

README.md
=> Mention CometBFT in the README.md

shared/src/ledger/tx.rs
We make the erroing a bit more explicit in the crash here
=> Properly Error on imporper Jailing

scripts/build_network.sh, scripts/utils/add_validator_shard.py, scripts/utils/clean_config.py
Improved build-network script
None
=> `build_network.sh` no need to pass the genesis config

.changelog/unreleased/bug-fixes/1887-fix-client-can-be-voted-check.md, core/src/ledger/governance/storage/proposal.rs
=> Fix lower bound in client proposal vote check

.github/workflows/build-and-test.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/release.yml
- upgrade mold to v2.1.0
- use mozilla action to install `sccache`
- minor changes
=> ci: upgrade ci tools

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/triggerable.yml, docker/docs/nginx.conf
=> [ci skip] caching, fix nginx docker config, minors

.github/workflows/build-and-test.yml, .github/workflows/scripts/schedule-e2e.py, docker/docs/nginx.conf
=> ci: change e2e workflow

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, Makefile
- switch s3 to minio
- re-introduce `--timing` to `make build-release`
=> ci: use minio

.github/workflows/build-and-test.yml, .github/workflows/checks.yml
=> ci: minor fixes

.github/workflows/build-and-test.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/triggerable.yml
=> ci: change cache

.github/workflows/build-and-test.yml, .github/workflows/release.yml
=> ci: fix change cache

.github/workflows/build-and-test.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/triggerable.yml
=> ci: fix cache again

.github/workflows/build-and-test.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/triggerable.yml
=> ci: cache fix again 

scripts/build_network.sh
=> Fix build network script

sdk/src/args.rs, sdk/src/lib.rs, sdk/src/tx.rs
Added missing methods to the sdk
0.24.0
=> sdk: added missing methods

.changelog/unreleased/bug-fixes/2125-fix-duplicate-balance.md, apps/src/lib/client/rpc.rs
=> Fix balance query not to return duplicate results

apps/src/lib/wasm_loader/mod.rs
=> fix: wasm env variables

.changelog/unreleased/bug-fixes/2166-fix-proof-height.md, core/src/ledger/storage/mod.rs
=> fix to get proofs even if no height is specified

apps/src/lib/cli.rs, apps/src/lib/node/ledger/shell/init_chain.rs, genesis/localnet/README.md, proof_of_stake/src/lib.rs, proof_of_stake/src/rewards.rs
Various very minor changes to the PoS code and elsewhere, sometimes in response to comments on PRs that were merged in v0.27.0.
v0.27.0
=> Misc PoS updates

Cargo.lock, Cargo.toml
The commit we used is from a branch that's been yanked, we should be using this one instead.
v0.27.0
- ~~[ ] I have added a changelog~~
=> deps: upgrade ledger-namada version

Makefile
Should improve flakiness of integration tests.
=> makefile: use single thread to run integration test

.github/workflows/build-and-test.yml
Update Hermes to `1.7.1-namada-beta5` for Namada v0.28.x
`v0.28.1`
=> Update Hermes in CI

.github/workflows/build-and-test.yml
=> Update CI Hermes for Namada v0.29.0

.changelog/unreleased/improvements/2377-governance-cleanup.md, core/src/ledger/governance/utils.rs
Shared function to compute the total power that voted on a governance proposal.
Modifies bad naming on a local variable when displaying the result of a proposal
v0.29.0
=> Governance misc refactors

.changelog/unreleased/bug-fixes/2384-wasmer-alignment-fixes.md, Cargo.lock, shared/Cargo.toml, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
=> Wasmer alignment fixes

.changelog/v0.30.0/improvements/2374-fix-bond-amount.md, CHANGELOG.md, CONTRIBUTING.md, apps/src/lib/node/ledger/broadcaster.rs, apps/src/lib/node/ledger/shell/init_chain.rs, core/src/ledger/governance/cli/onchain.rs, core/src/ledger/governance/storage/proposal.rs, core/src/ledger/governance/utils.rs, core/src/ledger/storage/mod.rs, documentation/dev/src/README.md, documentation/dev/src/explore/design/ledger/storage/data-schema.md, encoding_spec/src/main.rs, examples/README.md, light_sdk/src/reading/tx.rs, proof_of_stake/src/lib.rs, proof_of_stake/src/slashing.rs, proof_of_stake/src/tests/test_helper_fns.rs
Some of these were brought up by random github users that may appear to be airdrop farming. We can keep this PR around to add any legitimate miscellaneous edits to documentation.
v0.30.0
=> Miscellaneous grammatical fixes

.changelog/unreleased/testing/2398-fix-e2e-pgf-ibc.md, tests/src/e2e/ibc_tests.rs
=> Fix E2E test for PGF over IBC by waiting before the balance check

.changelog/unreleased/SDK/2400-sdk-rpc-queries.md, apps/src/lib/client/rpc.rs, core/src/ledger/governance/utils.rs, core/src/ledger/storage_api/governance.rs, sdk/src/queries/shell.rs, sdk/src/queries/vp/governance.rs, sdk/src/queries/vp/token.rs, sdk/src/rpc.rs
=> sdk: more rpc

.changelog/unreleased/bug-fixes/2401-tx-host-env.md, Cargo.lock, crates/namada/src/ledger/vp_host_fns.rs, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/wasm/compilation_cache/common.rs, crates/namada/src/vm/wasm/memory.rs, crates/tests/Cargo.toml, crates/tests/src/vm_host_env/tx.rs
=> tx host env panics fixes

crates/tests/src/integration/setup.rs, genesis/localnet/tokens.toml, genesis/starter/tokens.toml
Change the configuration values for some MASP inflation parameters.
v0.30.1
- ~~[ ] I have added a changelog~~
=> Adjust MASP inflation param values

.changelog/unreleased/bug-fixes/2440-pgf-minors.md, .github/workflows/scripts/e2e.json, crates/governance/src/pgf/cli/steward.rs, crates/governance/src/pgf/mod.rs, crates/governance/src/pgf/storage/steward.rs, crates/namada/src/ledger/pgf/mod.rs, crates/tests/src/e2e/ledger_tests.rs
- limit the number of reward distribution a steward can set
- fix a minor bug in pgf vp
=> pgf: added reward distribution limit for stewards

.changelog/unreleased/bug-fixes/2447-restrict-ascii-router-paths.md, crates/sdk/src/queries/router.rs, crates/sdk/src/queries/types.rs
=> restrict ascii router paths

apps/src/lib/config/genesis.rs, apps/src/lib/config/genesis/templates.rs, apps/src/lib/node/ledger/shell/mod.rs, apps/src/lib/node/ledger/storage/mod.rs, apps/src/lib/wallet/defaults.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml, tests/src/e2e/eth_bridge_tests.rs, tests/src/e2e/setup.rs
Rename for now given deadlines.
=> NAM -> NAAN

crates/core/src/types/token.rs, crates/sdk/src/masp.rs
=> various fixes

Cargo.lock, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/api.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/cli/context.rs, crates/apps/src/lib/cli/relayer.rs, crates/apps/src/lib/client/utils.rs, crates/apps/src/lib/config/genesis/transactions.rs, crates/apps/src/lib/node/ledger/shell/testing/client.rs, crates/sdk/Cargo.toml, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
=> client: use node address from config if not specified

.changelog/unreleased/improvements/2467-cli-native-token.md, Cargo.lock, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/api.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/cli/context.rs, crates/apps/src/lib/cli/relayer.rs, crates/apps/src/lib/client/utils.rs, crates/apps/src/lib/config/genesis/transactions.rs, crates/apps/src/lib/node/ledger/shell/testing/client.rs, crates/sdk/Cargo.toml, crates/sdk/src/args.rs, crates/sdk/src/lib.rs, crates/sdk/src/tx.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
#2466 - diff https://github.com/anoma/namada/pull/2467/files/a520b7896557dd5da4c60d9f3123e17298c62490..1cef89c457a8c1380006650524d51db482bef851
=> cli: add address arg that defaults to native token

wasm/wasm_source/src/tx_redelegate.rs
as caught here https://github.com/anoma/namada/actions/runs/7667039752/job/20896195576
0.30.2
- ~~[ ] I have added a changelog~~ - tests only
=> test/tx_redelegate: prevent redelegation delegator from being validator

.changelog/unreleased/improvements/2476-masp-checked-ops.md, Cargo.lock, Cargo.toml, crates/namada/Cargo.toml, crates/namada/src/ledger/native_vp/masp.rs, wasm/Cargo.lock, wasm_for_tests/wasm_source/Cargo.lock
Uses checked operations on `I128Sum` in the masp vp.
v0.30.3
=> `I128Sum` checked ops

crates/apps/src/lib/client/tx.rs
=> add missing memo in become validator and change consensus keys

.changelog/unreleased/features/2511-test-sync.md, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/client/rpc.rs, crates/tests/src/e2e/ledger_tests.rs
Adds an e2e test for a chain sync with a given chain ID.
Run with e.g. `NAMADA_ADD_PEER=tcp://48d3626f425e44192f4ecf4f9f777b4d17c66ba6@54.195.145.177:26656 NAMADA_CHAIN_ID=shielded-expedition.b40d8e9055 cargo test e2e::ledger_tests::test_sync_chain -- --exact --nocapture --ignored`
0.31.1
=> test chain sync

.changelog/unreleased/features/2511-test-sync.md, .github/workflows/triggerable_pos.yml, .github/workflows/triggerable_sync.yml, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/client/rpc.rs, crates/tests/src/e2e/ledger_tests.rs
#2511 - diff https://github.com/anoma/namada/pull/2526/commits/0a6890d34d281f850b882835fb23218518f9f80d
- ~~[ ] I have added a changelog~~ - CI only
=> CI: add triggerable chain sync test

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: fix commit sha usage

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: fix var syntax

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: fix binaries d/l src path

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: fix nightly version syntax

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: fix env vars syntax

.github/workflows/triggerable_sync.yml
=> gh/action/triggerable_sync: add CometBFT bin

.changelog/unreleased/improvements/2543-wallet-internal-addresses.md, crates/apps/src/lib/config/genesis/chain.rs, crates/sdk/src/wallet/store.rs
=> Add internal addresses to wallet upon `join-network`

.changelog/unreleased/bug-fixes/2578-superset-valset-bug.md, crates/apps/src/lib/node/ledger/shell/mod.rs, crates/apps/src/lib/node/ledger/shell/vote_extensions/val_set_update.rs, crates/ethereum_bridge/src/protocol/validation.rs, crates/ethereum_bridge/src/protocol/validation/validator_set_update.rs
Reject validator set updates signing over a superset of the next validator set.
`v0.31.2`
=> Reject validator set updates with a superset of the next validator set

.changelog/unreleased/bug-fixes/2573-fix-query-proposal-result.md, crates/apps/src/lib/client/rpc.rs, crates/governance/src/utils.rs, crates/tests/src/e2e/ledger_tests.rs
=> Fix query-proposal-result

docker/namada/Dockerfile
=> Update docker image

.github/workflows/triggerable_sync.yml, crates/tests/src/e2e/ledger_tests.rs
allow to specify "seed_nodes" for the triggerable fullnode sync test
0.31.6
- ~~[ ] I have added a changelog~~ - tests only
=> test/e2e/test_sync_chain: add seed_nodes param

.changelog/unreleased/bug-fixes/2739-router-no-pat-match.md, crates/sdk/src/queries/router.rs
=> Bail from router if a nested router segment is not matched

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/triggerable_sync.yml
=> ci: downgrade nightly to 2024-01-20

.github/workflows/build-and-test.yml, .github/workflows/checks.yml, .github/workflows/cron.yml, .github/workflows/docs.yml, .github/workflows/triggerable_sync.yml
=> ci: fix the nightly version to 2024-02-10

.changelog/unreleased/improvements/2757-wasm-cache-versioning.md, crates/namada/src/vm/wasm/compilation_cache/common.rs
=> wasm-cache: add versioning

.changelog/unreleased/testing/2765-fix-e2e-pgf-ibc.md, crates/tests/src/e2e/ibc_tests.rs
The PGF over IBC worked well, but the balance was increased by crossing another epoch.
`v0.31.7`
=> Fix e2e test for PGF over IBC

.changelog/unreleased/improvements/2776-update-rocksdb.md, Cargo.lock, Cargo.toml
=> update rocksdb to 0.22.0

.github/workflows/build-and-test.yml, .github/workflows/scripts/hermes.json
=> ci: change hermes version per branch

.changelog/unreleased/improvements/2894-aesthetic-edits.md, crates/proof_of_stake/src/rewards.rs, crates/proof_of_stake/src/tests/test_pos.rs, crates/shielded_token/src/storage_key.rs
Closes #2864. Also adds total supply to logs for PoS inflation.
v0.31.9
=> Quick aesthetic edits

.changelog/unreleased/improvements/2902-shielded-sync-start-height.md, crates/apps/src/lib/bench_utils.rs, crates/apps/src/lib/cli.rs, crates/apps/src/lib/cli/client.rs, crates/apps/src/lib/client/masp.rs, crates/sdk/src/args.rs, crates/sdk/src/masp.rs
Added an optional starting block argument for shielded sync
=> Added an optional starting block argument for shielded sync

.changelog/unreleased/bug-fixes/2628-fix-validator-voting-period.md, crates/apps/src/lib/client/rpc.rs, crates/core/src/storage.rs, crates/governance/src/storage/proposal.rs, crates/governance/src/utils.rs, crates/namada/src/ledger/governance/mod.rs, crates/sdk/src/tx.rs
=> Fix validator voting period

Makefile, examples/make-db-migration.rs
=> Build migrations in release off of 0.32.0

.github/workflows/build-and-test.yml, codecov.yml
- update codecov action to `v4`
- added `codecov.yml`
=> ci: update codecov 

.changelog/unreleased/sdk/3039-sdk-update-account.md, crates/sdk/src/lib.rs
=> sdk: improve update_account

.changelog/unreleased/bug-fixes/2790-fix-masp-tx-identification.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/shielded_token/src/utils.rs
=> Fix how masp tx's are identified

.changelog/unreleased/bug-fixes/2730-fix-ibc-transfer-dry-run.md, crates/ibc/src/context/common.rs
=> Fix ibc-transfer dry-run

.changelog/unreleased/improvements/3031-various-pos.md, README.md, crates/apps/src/lib/bench_utils.rs, crates/apps/src/lib/client/rpc.rs, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/governance/src/storage/keys.rs, crates/governance/src/utils.rs, crates/light_sdk/src/reading/asynchronous/pos.rs, crates/proof_of_stake/src/types/mod.rs, crates/sdk/src/queries/vp/pos.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs
Closes #3022.
- improve validator state query
- improve validator commission query
v0.33.0
=> Various small PoS improvements

.changelog/unreleased/bug-fixes/3085-fix-pgf-ibc-denom.md, crates/ibc/src/actions.rs, crates/tests/src/e2e/ibc_tests.rs
=> Fix denom in PGF over IBC

.changelog/unreleased/improvements/3107-governance-latency.md, crates/apps/src/lib/config/genesis/chain.rs, crates/apps/src/lib/config/genesis/templates.rs, crates/governance/src/parameters.rs, crates/governance/src/pgf/storage/steward.rs, crates/governance/src/storage/keys.rs, crates/governance/src/storage/mod.rs, crates/namada/src/ledger/governance/mod.rs, genesis/localnet/parameters.toml, genesis/starter/parameters.toml
=> Governance: add `latency` to genesis parameters

.changelog/unreleased/improvements/3031-various-pos.md, .changelog/unreleased/improvements/3116-fix-some-client-logging.md, README.md, crates/apps/src/lib/bench_utils.rs, crates/apps/src/lib/client/rpc.rs, crates/apps/src/lib/node/ledger/shell/governance.rs, crates/governance/src/storage/keys.rs, crates/governance/src/utils.rs, crates/light_sdk/src/reading/asynchronous/pos.rs, crates/proof_of_stake/src/types/mod.rs, crates/sdk/src/queries/vp/pos.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs
Closes #2608
Based on #3031, which is based on v0.33
=> Small client log fixes

.changelog/unreleased/improvements/2868-borsh-serialize.md, crates/apps/src/lib/node/ledger/shell/finalize_block.rs, crates/apps/src/lib/node/ledger/shell/init_chain.rs, crates/apps/src/lib/node/ledger/shell/prepare_proposal.rs, crates/apps/src/lib/node/ledger/shell/vote_extensions/eth_events.rs, crates/benches/txs.rs, crates/ethereum_bridge/src/protocol/transactions/bridge_pool_roots.rs, crates/ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs, crates/ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs, crates/ethereum_bridge/src/protocol/transactions/read.rs, crates/ethereum_bridge/src/protocol/transactions/update.rs, crates/ethereum_bridge/src/protocol/transactions/votes/storage.rs, crates/ethereum_bridge/src/storage/eth_bridge_queries.rs, crates/ethereum_bridge/src/storage/parameters.rs, crates/governance/src/storage/mod.rs, crates/namada/src/ledger/governance/mod.rs, crates/namada/src/ledger/mod.rs, crates/namada/src/ledger/protocol/mod.rs, crates/namada/src/vm/wasm/run.rs, crates/parameters/src/lib.rs, crates/tests/src/vm_host_env/mod.rs, wasm/tx_init_proposal/src/lib.rs
=> Borsh serialization

.changelog/unreleased/bug-fixes/3130-gen-in-current-era.md, crates/sdk/src/lib.rs, crates/tests/fixtures/README.md, crates/tx/src/types.rs, examples/generate_txs.rs
=> Test tx decoding via fixture

scripts/merge_pr.sh
A helper for re-merging PRs from draft
=> scripts: add merge_pr.sh

genesis/localnet/README.md
=> fixing command to generate localnet files on readme

.changelog/unreleased/bug-fixes/3181-fix-wasm-cache-pre-compile.md, crates/namada/src/vm/wasm/compilation_cache/common.rs
=> namada/wasm/cache: write the file to cache before updating progress

crates/token/Cargo.toml, crates/token/src/lib.rs, crates/tx_prelude/Cargo.toml, crates/tx_prelude/src/token.rs, wasm/tx_bond/Cargo.toml, wasm/tx_redelegate/Cargo.toml, wasm/tx_unbond/Cargo.toml, wasm/tx_withdraw/Cargo.toml
0.35.0
- ~~[ ] I have added a changelog~~ testing only
=> fix wasm tests imports

.changelog/unreleased/improvements/3195-make-internals-value-sum-private.md, Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Make the internals of ValueSum (in the masp crate) private so we know that invariants of representation are maintained
=> Make the internals of ValueSum private

.changelog/unreleased/improvements/3258-dont-export-wasm-mem.md, .changelog/unreleased/improvements/3273-host-ref-refactor.md, crates/namada/src/vm/host_env.rs, crates/namada/src/vm/mod.rs, crates/namada/src/vm/wasm/host_env.rs, crates/namada/src/vm/wasm/run.rs, crates/tests/src/vm_host_env/tx.rs
Refactor WASM host references code.
#3258
**Diff for review:** https://github.com/anoma/namada/compare/tiago/dont-export-wasm-mem..tiago/host-ref-refactor
=> Refactor WASM host references

crates/tx_prelude/src/ibc.rs
=> export more ibc storage keys to wasm

crates/benches/Cargo.toml
Uncomment the benchmarks.
`v0.38.1`
=> Brings back the benchmarks

.changelog/unreleased/improvements/3348-allow-protocol-nam-transf.md, crates/namada/src/ledger/native_vp/multitoken.rs
=> Allow NAM transfers for protocol actions in Multitoken VP

.changelog/unreleased/improvements/3349-gas-payer-from-implicit-addr.md, crates/apps_lib/src/cli/context.rs, crates/sdk/src/wallet/mod.rs
=> Select gas payer from implicit address

.changelog/unreleased/improvements/3351-masp-adjustments.md, crates/shielded_token/src/conversion.rs
closes #2722 - most comments were outdated, only 2 that still applied was checked arithmetic in conversions and inflation overflow warning.
0.38.1
=> masp adjustments

.changelog/unreleased/bug-fixes/3358-fix-dry-run-writelog.md, crates/namada/src/ledger/mod.rs
=> Fix write log when dry-run

.changelog/unreleased/bug-fixes/3404-fix-ibc-message.md, crates/ibc/src/lib.rs
=> Fix unwrapped IBC message decoding

.changelog/unreleased/improvements/3412-upgrade-ledger-namada-rs-dep.md, Cargo.lock, Cargo.toml
Upgrade `ledger-namada-rs` dependency to 0.0.24.
Namada v0.39.0.
=> Upgrade ledger-namada-rs to 0.0.24.

.changelog/unreleased/improvements/3192-opt-recomm.md, crates/node/src/shell/governance.rs, crates/node/src/shell/prepare_proposal.rs, crates/node/src/shell/process_proposal.rs
Closes #3192.
Implements some small code optimizations suggested in the last audit.
`v0.39.0`
=> Misc optimizations

.changelog/unreleased/improvements/3506-tendermint-0.37.md, Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> Bump tendermint-rs to 0.37

.changelog/unreleased/bug-fixes/3518-sdk-builder-fix.md, crates/sdk/src/args.rs
=> sdk: add impl to shielding transfer

.mergify.yml
=> ci: add mergify

.github/workflows/ci.yml
=> ci: fix fmt-check

.changelog/unreleased/bug-fixes/3576-remove-load-shed.md, crates/node/src/lib.rs, crates/sdk/src/tx.rs
=> ledger: avoid load shedding tower info service

.changelog/unreleased/improvements/3592-improve-signers-sdk.md, crates/apps_lib/src/client/tx.rs, crates/sdk/src/eth_bridge/bridge_pool.rs, crates/sdk/src/signing.rs, crates/sdk/src/tx.rs
Minor refactor to how signing data is fetched.
=> minor refactor to signing method

.changelog/unreleased/improvements/3589-misc-improvements.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/client/rpc.rs, crates/core/src/address.rs, crates/core/src/uint.rs, crates/node/src/ethereum_oracle/events.rs, crates/parameters/src/lib.rs, crates/proof_of_stake/src/tests/test_validator.rs, crates/tests/src/e2e/ledger_tests.rs, crates/vm/src/wasm/compilation_cache/common.rs
=> Various misc improvements

.changelog/unreleased/improvements/3629-improve-init-proposal-validation.md, crates/apps_lib/src/client/rpc.rs, crates/governance/src/cli/onchain.rs, crates/governance/src/cli/validation.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/tests/src/integration/ledger_tests.rs
=> Improve governance client validation

README.md, crates/ethereum_bridge/src/storage/eth_bridge_queries.rs, crates/sdk/src/masp.rs, crates/sdk/src/masp/shielded_sync/dispatcher.rs
=> fix rustdoc issues

crates/apps_lib/src/config/genesis/transactions.rs
=> Amend comment in genesis sign txs

.changelog/unreleased/bug-fixes/3694-fix-join-network-wasm-dir.md, crates/apps_lib/src/client/utils.rs
=> fix wasm dir during join-network

.github/workflows/ci.yml
- increase integration tests timeout
- add job to check for cargo docs correctness
- avoid running changelog job on release candidate branches
=> ci: improvements/fixes

.github/workflows/ci.yml
follow-up to #3704 to fix code cov upload
=> ci: fix coverage files paths

.github/workflows/ci.yml, Makefile, wasm/Makefile
runs wasm tests via llvm-cov and adds the coverage to codecov report
=> include wasm tests in code cov

.changelog/unreleased/improvements/3751-upgrade-cometbft-0.37.11.md, Dockerfile, README.md
=> set cometbft to 0.37.11

crates/tests/src/e2e/setup.rs
fixes the `test_node_connectivity_and_consensus` to avoid `ERROR: failed to start node: failed to listen on 127.0.0.1:26657: listen tcp 127.0.0.1:26657: bind: address already in use`
=> test/e2e: offset non-validator node ports to avoid conflict with gaia

.github/workflows/ci.yml, crates/tests/src/e2e/ledger_tests.rs, crates/tests/src/e2e/setup.rs, genesis/hardware/README.md
follow-up to #3719 to fix the path to `speculos`
=> automate an e2e test with Ledger hardware wallet emulator - 1st follow-up

crates/sdk/src/args.rs
=> add memo builder fun to tx builder

crates/node/src/tendermint_node.rs
=> try to strip namada version from moniker

.github/pull_request_template.md
=> Update PR desc again

.github/workflows/ci.yml, crates/sdk/src/lib.rs, crates/tests/src/vm_host_env/tx.rs, crates/tests/src/vm_host_env/vp.rs
=> toolchain update follow-up

scripts/get_cometbft.sh
=> Update CometBFT version in `get_cometbft.sh`

.mergify.yml
=> mergify: unquote base branch name

crates/tests/src/e2e/ibc_tests.rs
=> test/e2e/ibc: try to killall gaiad before running it

crates/core/src/masp.rs
Increases the test coverage report in the affected files.
=> Add a bunch of low hanging fruit masp tests

.changelog/unreleased/improvements/3968-derive-ibc-token-address.md, crates/apps_lib/src/cli.rs, crates/apps_lib/src/cli/client.rs, crates/apps_lib/src/client/utils.rs
- Derive IBC token address from `transfer/channel-X/<denom>` string - closes #3951
- Derive implicit address from raw public key (tpknam)
=> New client utils

crates/node/src/shell/prepare_proposal.rs
=> Remove fixme comment

.github/workflows/ci.yml
=> ci: increase test integration step timeout

scripts/release.sh
=> fix release.sh script

.changelog/unreleased/bug-fixes/4025-ibc-nft-e2e.md, .changelog/unreleased/testing/4025-ibc-nft-e2e.md, .github/workflows/ci.yml, .github/workflows/scripts/e2e.json, Cargo.lock, crates/ibc/src/lib.rs, crates/tests/Cargo.toml, crates/tests/src/e2e/helpers.rs, crates/tests/src/e2e/ibc_tests.rs, crates/tests/src/e2e/setup.rs
Need the CI update
based on #4027 
Depends-On: #4027
Diff: https://github.com/anoma/namada/compare/yuji/fix-ibc-nft-unshielding...yuji/ibc-nft-e2e
=> E2E tests for IBC NFT transfers

about.toml
=> add new required ring licenses

scripts/gen_localnet.py
=> Fix `gen_localnet.py` json exception

crates/sdk/src/tx.rs
=> governance client fix proposal type

README.md
=> Update hermes release info in ReadMe

.github/workflows/ci.yml
=> ci/test-ledger-app: undo previous changes and run on ubuntu image

Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> deps: switch to released clru version

Cargo.lock, Cargo.toml
related to https://github.com/anoma/namada/issues/4143
=> deps: Switch to released tower-abci

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/storage.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> switch to published usize-set (previously index-set)

crates/apps_lib/src/client/rpc.rs
A quick follow-up for unresolved threads from #4205
=> client/rpc: small improvements

crates/sdk/src/args.rs
=> add missing trait to `TxUnshieldingTransfer`

Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> deps: switch to released sparse-merkle-tree fork

scripts/make-package.sh
=> scripts/make-package.sh - fix typo

.github/workflows/ci.yml
=> ci: testing ci improvements

.changelog/unreleased/miscellaneous/4280-update-hermes.md, .github/workflows/ci.yml, .github/workflows/scripts/hermes.txt, README.md, scripts/get_hermes.sh
=> Hermes for v1.1.0

crates/tests/src/hw_wallet_automation.rs
=> test/e2e: fix the test with HW wallet automation

.github/workflows/ci.yml, crates/benches/Cargo.toml, crates/benches/mempool_validate.rs, crates/node/src/shell/mod.rs, crates/node/src/shell/process_proposal.rs, crates/tx/src/section.rs, wasm/Cargo.lock, wasm/tx_become_validator/Cargo.toml, wasm/tx_become_validator/src/lib.rs
=> sa fixes tests

.changelog/unreleased/bug-fixes/4441-rust-1.85.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/node/src/lib.rs, crates/node/src/shell/mod.rs, crates/node/src/tendermint_node.rs, crates/tests/src/e2e/ledger_tests.rs
=> fix node reset

about.toml
see e.g. output of https://github.com/anoma/namada/actions/runs/13834877886/job/38707685341
=> add newly required 3rd party licenses

crates/shielded_token/src/masp/shielded_sync/dispatcher.rs
=> Improve shielded sync tx fetch errors

.changelog/unreleased/features/4481-dry-run-proposal.md, crates/apps/src/bin/namada-node/cli.rs, crates/apps_lib/src/cli.rs, crates/node/src/dry_run_tx.rs, crates/node/src/storage/rocksdb.rs, crates/node/src/utils.rs, crates/sdk/src/rpc.rs, crates/sdk/src/tx.rs, crates/state/src/wl_state.rs, crates/storage/src/db.rs, crates/storage/src/mockdb.rs
=> allow to dry run a proposal code

.changelog/unreleased/improvements/4493-perm-gov-masp-vp.md, crates/shielded_token/src/vp.rs
=> shielded_token/vp: allow any changes by a gov proposal

crates/shielded_token/Cargo.toml
fixes standalone tests build of this crate (e.g. `cargo test --package namada_shielded_token`)
=> shielded_token: fix standalone test build

.changelog/unreleased/bug-fixes/4545-upgrade-tendermint-rs.md, Cargo.lock, Cargo.toml, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
=> Upgrade to tendermint 0.40.3

.changelog/unreleased/miscellaneous/4554-maint-lib-ci.md, .github/workflows/ci.yml, .github/workflows/release.yml
=> ci: fix images

.changelog/libs-v0.48.2/miscellaneous/4554-maint-lib-ci.md, .changelog/libs-v0.48.2/summary.md, CHANGELOG.md
=> Changelog: Release libs 0.48.2

.github/workflows/ci.yml
=> ci: use nextest to run hardwallet e2e tests

.changelog/unreleased/improvements/4666-optimize-claim-rewards.md, crates/proof_of_stake/src/lib.rs, crates/proof_of_stake/src/rewards.rs, crates/proof_of_stake/src/slashing.rs, crates/proof_of_stake/src/tests/test_helper_fns.rs
=> optimize claim rewards tx

.changelog/unreleased/testing/4553-test-ci-ibc.md, crates/tests/src/e2e/setup.rs
=> Avoid flakiness in IBC e2e tests

crates/state/proptest-regressions/write_log.txt, crates/state/src/write_log.rs
as caught in https://github.com/namada-net/namada/actions/runs/16346697856/job/46182572632
=> fix write-log iters test

.changelog/unreleased/improvements/4778-withdraw-tx-event.md, crates/proof_of_stake/src/lib.rs, crates/proof_of_stake/src/tests/mod.rs
=> PoS: add a token transfer event to withdraw-tokens tx

.changelog/unreleased/bug-fixes/4843-fix-rm-tx-gas-map.md, .github/workflows/ci.yml, .github/workflows/release.yml, crates/proof_of_stake/src/rewards.rs, crates/proof_of_stake/src/tests/test_pos.rs, crates/proof_of_stake/src/tests/test_slash_and_redel.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/state/src/wl_state.rs
=> merge #4839, #4843, #4844

.changelog/unreleased/improvements/4785-bridge-tree-shielded-wallet.md, Cargo.lock, Cargo.toml, Makefile, crates/apps_lib/Cargo.toml, crates/apps_lib/src/client/masp.rs, crates/sdk/Cargo.toml, crates/sdk/src/masp/utilities.rs, crates/shielded_token/Cargo.toml, crates/shielded_token/src/masp.rs, crates/shielded_token/src/masp/bridge_tree.rs, crates/shielded_token/src/masp/shielded_sync/dispatcher.rs, crates/shielded_token/src/masp/shielded_sync/mod.rs, crates/shielded_token/src/masp/shielded_sync/utils.rs, crates/shielded_token/src/masp/shielded_wallet.rs, crates/shielded_token/src/masp/test_utils.rs, crates/shielded_token/src/masp/wallet_migrations.rs, wasm/Cargo.lock, wasm_for_tests/Cargo.lock
Backport of #4785
Supersedes #4902
=> Improve shielded sync (backport #4785)
